#!/usr/bin/env python3
"""
artifacts.py - Extracted from Orchestrator/app.py

This module was automatically extracted using byte-offset manifest refactoring.
Original location: Lines 2012-2192

Extraction date: 2025-12-10T21:12:53.094874+00:00
Original SHA-256: a097c60c4b2494335c9d05822e7abf6ab59c573afd1cae31c4d86e779d0d6445
"""

# Standard library imports
import re
import uuid
from pathlib import Path
from typing import Dict, Any, Optional
import html
import traceback

# External library imports
import docx
import reportlab

# Additional imports (auto-generated by dependency audit)
from Orchestrator.config import ARTIFACTS_DIR


def generate_pdf(content: str, output_path: Path):
    """Generate PDF from markdown content with rich formatting using reportlab."""
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
    from reportlab.lib.units import inch
    import html

    doc = SimpleDocTemplate(str(output_path), pagesize=letter,
                           leftMargin=inch, rightMargin=inch,
                           topMargin=inch, bottomMargin=inch)
    styles = getSampleStyleSheet()

    # Add custom styles for bullets
    styles.add(ParagraphStyle(name='BulletText', parent=styles['Normal'],
                              leftIndent=20, bulletIndent=10))
    story = []

    def escape_xml(text):
        """Escape XML special characters for reportlab."""
        # Escape &, <, > but preserve our markup tags
        text = text.replace('&', '&amp;')
        text = text.replace('<', '&lt;')
        text = text.replace('>', '&gt;')
        return text

    def process_inline_formatting(text):
        """Convert markdown inline formatting to reportlab markup."""
        # First escape XML special characters
        text = escape_xml(text)
        # Bold: **text** or __text__ -> <b>text</b>
        text = re.sub(r'\*\*(.+?)\*\*', r'<b>\1</b>', text)
        text = re.sub(r'__(.+?)__', r'<b>\1</b>', text)
        # Italic: *text* or _text_ -> <i>text</i>
        text = re.sub(r'(?<!\*)\*([^*]+)\*(?!\*)', r'<i>\1</i>', text)
        text = re.sub(r'(?<!_)_([^_]+)_(?!_)', r'<i>\1</i>', text)
        # Code: `text` -> <font face="Courier">text</font>
        text = re.sub(r'`(.+?)`', r'<font face="Courier">\1</font>', text)
        return text

    lines = content.split('\n')
    for line in lines:
        # Headers
        if line.startswith('# '):
            story.append(Paragraph(process_inline_formatting(line[2:]), styles['Heading1']))
        elif line.startswith('## '):
            story.append(Paragraph(process_inline_formatting(line[3:]), styles['Heading2']))
        elif line.startswith('### '):
            story.append(Paragraph(process_inline_formatting(line[4:]), styles['Heading3']))
        # Bullet points
        elif line.strip().startswith('- ') or line.strip().startswith('* '):
            bullet_text = process_inline_formatting(line.strip()[2:])
            story.append(Paragraph(f'• {bullet_text}', styles['BulletText']))
        # Numbered lists
        elif re.match(r'^\d+\.\s', line.strip()):
            list_text = process_inline_formatting(re.sub(r'^\d+\.\s', '', line.strip()))
            num = re.match(r'^(\d+)\.', line.strip()).group(1)
            story.append(Paragraph(f'{num}. {list_text}', styles['BulletText']))
        # Empty lines
        elif not line.strip():
            story.append(Spacer(1, 0.15*inch))
        # Regular paragraphs
        else:
            story.append(Paragraph(process_inline_formatting(line), styles['Normal']))

    doc.build(story)

def generate_csv(content: str, output_path: Path):
    """Generate CSV file from content.
    Content should be comma-separated values with newlines between rows.
    """
    # CSV is just text - write directly
    output_path.write_text(content, encoding='utf-8')

def generate_docx(content: str, output_path: Path):
    """Generate DOCX from markdown-like content using python-docx."""
    from docx import Document
    from docx.shared import Pt, Inches
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    doc = Document()

    lines = content.split('\n')
    for line in lines:
        # Headers
        if line.startswith('# '):
            p = doc.add_heading(line[2:], level=1)
        elif line.startswith('## '):
            p = doc.add_heading(line[3:], level=2)
        elif line.startswith('### '):
            p = doc.add_heading(line[4:], level=3)
        # Bullet points
        elif line.strip().startswith('- ') or line.strip().startswith('* '):
            p = doc.add_paragraph(line.strip()[2:], style='List Bullet')
        # Numbered lists
        elif re.match(r'^\d+\.\s', line.strip()):
            list_text = re.sub(r'^\d+\.\s', '', line.strip())
            p = doc.add_paragraph(list_text, style='List Number')
        # Empty lines - add paragraph break
        elif not line.strip():
            doc.add_paragraph()
        # Regular paragraphs
        else:
            p = doc.add_paragraph()
            # Process inline formatting
            remaining = line
            while remaining:
                # Bold: **text**
                bold_match = re.search(r'\*\*(.+?)\*\*', remaining)
                # Italic: *text*
                italic_match = re.search(r'(?<!\*)\*([^*]+)\*(?!\*)', remaining)

                if bold_match and (not italic_match or bold_match.start() <= italic_match.start()):
                    # Add text before bold
                    if bold_match.start() > 0:
                        p.add_run(remaining[:bold_match.start()])
                    # Add bold text
                    run = p.add_run(bold_match.group(1))
                    run.bold = True
                    remaining = remaining[bold_match.end():]
                elif italic_match:
                    # Add text before italic
                    if italic_match.start() > 0:
                        p.add_run(remaining[:italic_match.start()])
                    # Add italic text
                    run = p.add_run(italic_match.group(1))
                    run.italic = True
                    remaining = remaining[italic_match.end():]
                else:
                    # No more formatting, add rest as plain text
                    p.add_run(remaining)
                    break

    doc.save(str(output_path))

def parse_and_process_artifacts(ui_reply: str, operator: str) -> str:
    """
    Parse [ARTIFACT:...] blocks, generate files, replace with download links.
    Returns modified ui_reply with download buttons.
    """
    pattern = r'\[ARTIFACT:([^:]+):([^\]]+)\](.*?)\[/ARTIFACT\]'

    def process_match(match):
        filename = match.group(1).strip()
        artifact_type = match.group(2).strip().lower()
        content = match.group(3).strip()

        print(f"[ARTIFACT] Processing: filename={filename}, type={artifact_type}, content_len={len(content)}")

        # Generate unique filename with operator prefix
        artifact_id = f"{operator}_{uuid.uuid4().hex[:8]}_{filename}"
        artifact_path = ARTIFACTS_DIR / artifact_id

        try:
            if artifact_type == 'text':
                artifact_path.write_text(content, encoding='utf-8')
            elif artifact_type == 'pdf':
                generate_pdf(content, artifact_path)
            elif artifact_type == 'csv':
                generate_csv(content, artifact_path)
            elif artifact_type == 'docx':
                generate_docx(content, artifact_path)
            elif artifact_type == 'image_placeholder':
                # Special handling for image generation placeholders created by AI models
                # Don't create a file - just return empty string since the image_task event handles the actual display
                print(f"[ARTIFACT] Ignoring image_placeholder artifact - handled by task manager")
                return ''
            else:
                return f'<div class="artifact-error" style="color: #ff6b6b; padding: 8px; background: #1a1a1a; border-radius: 4px;">⚠️ Unsupported artifact type: {artifact_type}</div>'

            # Return download button HTML
            size_kb = artifact_path.stat().st_size / 1024
            print(f"[ARTIFACT] Success: {filename} ({size_kb:.1f} KB)")
            return f'<div class="artifact-download"><a href="/artifacts/{artifact_id}" download="{filename}" class="btn artifact-btn">📥 Download {filename} ({size_kb:.1f} KB)</a></div>'
        except Exception as e:
            print(f"[ARTIFACT] Error generating {filename} (type={artifact_type}): {e}")
            import traceback
            traceback.print_exc()
            # Show more helpful error in UI
            error_msg = str(e)
            if len(error_msg) > 200:
                error_msg = error_msg[:200] + "..."
            return f'<div class="artifact-error" style="color: #ff6b6b; padding: 12px; background: #1a1a1a; border-radius: 4px; margin: 8px 0;">⚠️ Failed to generate {filename}: {error_msg}</div>'

    return re.sub(pattern, process_match, ui_reply, flags=re.DOTALL)

