#!/usr/bin/env python3
from __future__ import annotations

"""
checkpoint.py - Extracted from Orchestrator/app.py

This module was automatically extracted using byte-offset manifest refactoring.
Original location: Lines 3417-3701

Extraction date: 2025-12-10T22:35:07.423902+00:00
Original SHA-256: eb8ebd2c2ddbc5f9e823e21e7e5996b0d7f3609478bf09692f8adce4e6b01326
"""

# Standard library imports
import json
import hashlib
import threading
from datetime import datetime, timezone
from typing import Dict, Any, Optional, List
from pathlib import Path

# External library imports
import traceback
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from starlette.middleware.gzip import GZipMiddleware

# Additional imports (auto-generated by dependency audit)
from Orchestrator.config import CHECKPOINT_AUTO_CREATE_INTERVAL, CHECKPOINT_MIN_SNAPSHOTS, CHECKPOINT_TURNS_TO_COMPRESS, VOL_PATH
from Orchestrator.fossils import get_recent_fossils_for_operator, update_snapshot_index
from Orchestrator.monitoring import drift_state_for, generate_embedding, render_snapshot_body_v71
from Orchestrator.state import get_state, save_operator_state, mint_lock
from Orchestrator.volume import append_snapshot_text, archive_volume, next_snap_id_from_tail, now_utc_iso, parse_tail, verify_gm_or_halt, read_text_safe


def create_checkpoint_async(operator: str, manual: bool = False):
    """Create a compressed checkpoint snapshot for an operator.

    This function:
    1. Retrieves recent snapshots for the operator (count configured in [checkpoint] section)
    2. Sends them to Gemini 3.1 Pro for compression
    3. Saves the compressed summary as a checkpoint snapshot

    Args:
        operator: The operator name (e.g., "Brandon", "Anna")
        manual: Whether this is a manual checkpoint (vs automatic at configured intervals)
    """
    try:
        s = get_state(operator)
        vol_txt = read_text_safe(VOL_PATH)

        # Get recent snapshots for this operator (configured in [checkpoint] section)
        recent_snapshots = get_recent_fossils_for_operator(vol_txt, operator, count=CHECKPOINT_TURNS_TO_COMPRESS, cap_chars_each=10000)

        if len(recent_snapshots) < CHECKPOINT_MIN_SNAPSHOTS:
            print(f"[CHECKPOINT] Not enough snapshots for {operator} to create checkpoint ({len(recent_snapshots)}/{CHECKPOINT_TURNS_TO_COMPRESS})")
            return

        print(f"[CHECKPOINT] Creating checkpoint for {operator} with {len(recent_snapshots)} snapshots")

        # Prepare compression prompt
        snapshots_text = "\n\n" + "="*80 + "\n\n".join(recent_snapshots)

        compression_prompt = f"""Compress the following {len(recent_snapshots)} conversation turns into a detailed, coherent summary that preserves key context, decisions, technical details, and conversation flow.

Maintain enough detail that someone reading only this summary could continue the conversation meaningfully.

Focus on:
- Main topics discussed
- Decisions made
- Technical implementations
- User preferences expressed
- Important context that should be remembered
- Key problems solved
- System architecture details
- Feature requests and requirements

Provide a comprehensive, structured summary:

{snapshots_text}"""

        # Call Gemini 3.1 Pro for compression (largest context window)
        messages = [{"role": "user", "content": compression_prompt}]

        # Use Gemini 3.1 Pro for maximum context window (lazy import to avoid circular import)
        from Orchestrator.routes.chat_routes import call_gemini
        compressed_summary, usage, _ = call_gemini(messages, model="gemini-3.1-pro-preview", operator=operator)

        if not compressed_summary:
            print(f"[CHECKPOINT] Failed to generate compression for {operator}")
            return

        # Create checkpoint snapshot
        with mint_lock:
            utc = now_utc_iso()
            vol1 = read_text_safe(VOL_PATH)
            info1 = parse_tail(vol1)
            snap_id = next_snap_id_from_tail(info1["tail_id"])

            # Determine source range
            source_start = s.total_turns - len(recent_snapshots)
            source_end = s.total_turns

            reason = "MANUAL_CHECKPOINT" if manual else f"AUTO_CHECKPOINT_TURN_{s.total_turns}"

            # Build checkpoint snapshot body
            log_lines = [
                f"[CHECKPOINT] Compressed summary of {len(recent_snapshots)} snapshots",
                f"[CHECKPOINT] Source range: turns {source_start}-{source_end}",
                f"[CHECKPOINT] Operator: {operator}",
                "",
                compressed_summary
            ]

            gauges = {
                "drift": "green",
                "p": 0,
                "c": len(compressed_summary),
                "t": len(compressed_summary),
                "model": "gemini-3.1-pro-preview",
                "operator": operator
            }

            provenance = {
                "gm": True,
                "recent": [],
                "relevant": []
            }

            # Render checkpoint snapshot with special metadata
            body = render_snapshot_body_v71(
                info=info1,
                snap_id=snap_id,
                utc=utc,
                reason=reason,
                log_lines=log_lines,
                gauges=gauges,
                provenance=provenance
            )

            # Add checkpoint-specific metadata
            body = body.replace("MODE: Normal", "MODE: Checkpoint")
            body = body.replace(f"OPERATOR: {operator}", f"OPERATOR: {operator}\nTYPE: checkpoint\nSOURCE_RANGE: {source_start}-{source_end}")

            # Append checkpoint to volume
            byte_start = VOL_PATH.stat().st_size if VOL_PATH.exists() else 0
            append_snapshot_text(body)
            byte_end = VOL_PATH.stat().st_size

            # Generate embedding for semantic search
            print(f"[EMBEDDING] Generating embedding for checkpoint {snap_id}...")
            embedding = generate_embedding(body)
            if embedding:
                print(f"[EMBEDDING] Successfully generated embedding ({len(embedding)} dimensions)")
            else:
                print(f"[EMBEDDING] Warning: Failed to generate embedding for {snap_id}")

            # Update index with embedding
            update_snapshot_index(
                snap_id=snap_id,
                byte_start=byte_start,
                byte_end=byte_end,
                operator=operator,
                timestamp=utc,
                snap_type="checkpoint",
                embedding=embedding
            )

            # Update operator state
            s.last_checkpoint_turn = s.total_turns
            s.last_checkpoint_id = snap_id

            print(f"[CHECKPOINT] Created {snap_id} for {operator} at turn {s.total_turns} ({len(compressed_summary)} chars)")

            # Save operator state after checkpoint creation
            save_operator_state()

    except Exception as e:
        print(f"[CHECKPOINT] Error creating checkpoint for {operator}: {e}")
        import traceback
        traceback.print_exc()


def should_create_checkpoint(operator: str) -> bool:
    """Check if a checkpoint should be created for this operator.

    Creates checkpoints when turns_since_last_checkpoint >= auto_create_interval.
    This matches the UI countdown timer (when it hits 0).
    """
    s = get_state(operator)

    # Calculate turns since last checkpoint (this is what the UI countdown shows)
    turns_since_last_checkpoint = s.total_turns - s.last_checkpoint_turn
    turns_remaining = CHECKPOINT_AUTO_CREATE_INTERVAL - turns_since_last_checkpoint

    # Debug logging
    print(f"[CHECKPOINT-CHECK] Operator: {operator}, total_turns: {s.total_turns}, last_checkpoint_turn: {s.last_checkpoint_turn}")
    print(f"[CHECKPOINT-CHECK] Turns since last checkpoint: {turns_since_last_checkpoint}, Turns remaining: {turns_remaining}, Interval: {CHECKPOINT_AUTO_CREATE_INTERVAL}")

    # Create checkpoint when we've reached or exceeded the interval (countdown hits 0 or below)
    if turns_since_last_checkpoint >= CHECKPOINT_AUTO_CREATE_INTERVAL:
        print(f"[CHECKPOINT-CHECK] Checkpoint needed! (counter hit 0)")
        return True
    else:
        print(f"[CHECKPOINT-CHECK] Not yet - {turns_remaining} turns remaining until checkpoint")
        return False

# -----------------------------------------------------------------------------
# Mint
# -----------------------------------------------------------------------------
def perform_mint(operator: str, reason: str = "MANUAL") -> Dict[str, Any]:
    verify_gm_or_halt()
    s = get_state(operator)

    with mint_lock:
        vol1 = read_text_safe(VOL_PATH)
        info1 = parse_tail(vol1)
        utc = now_utc_iso()
        snap_id = next_snap_id_from_tail(info1["tail_id"])

        new_items = s.conversation_log[s.last_mint_index:]

        def _render_log_line(it: dict) -> str:
            if it.get("role") == "user":
                t = it.get("text", "")
            else:
                t = it.get("snap_text") or it.get("text", "")
            return f"{it['utc']} operator={operator} {it['role']}: {t}"

        log_lines = [_render_log_line(it) for it in new_items]

        usage_last = s.last_context_meta.get("usage_last", {})
        p = usage_last.get("prompt_tokens", 0)
        c = usage_last.get("completion_tokens", 0)
        t = usage_last.get("total_tokens", p + c)
        model_name = s.last_context_meta.get("model", "")
        drift = drift_state_for(s)

        gm_flag = s.last_context_meta.get("gm_excerpt", True)
        recent_ids = s.last_context_meta.get("recent_ids", [])
        relevant_ids = s.last_context_meta.get("relevant_ids", [])

        # DEBUG: Log what provenance is being saved to snapshot
        print(f"[MINT] Creating snapshot {snap_id} for operator {operator}")
        print(f"[MINT] Provenance - Recent: {recent_ids}")
        print(f"[MINT] Provenance - Relevant: {relevant_ids}")

        body = render_snapshot_body_v71(
            info1, snap_id, utc, reason, log_lines,
            gauges={"drift": drift, "p": p, "c": c, "t": t, "model": model_name, "operator": operator},
            provenance={"gm": gm_flag, "recent": recent_ids, "relevant": relevant_ids},
        )

        vol2 = read_text_safe(VOL_PATH)
        info2 = parse_tail(vol2)
        if info2["tail_id"] != info1["tail_id"]:
            info1 = info2
            snap_id = next_snap_id_from_tail(info1["tail_id"])
            body = render_snapshot_body_v71(
                info1, snap_id, utc, reason, log_lines,
                gauges={"drift": drift, "p": p, "c": c, "t": t, "model": model_name, "operator": operator},
                provenance={"gm": gm_flag, "recent": recent_ids, "relevant": relevant_ids},
            )

        # Get file size before append to calculate byte offsets
        byte_start = VOL_PATH.stat().st_size if VOL_PATH.exists() else 0

        append_snapshot_text(body)

        # Get file size after append
        byte_end = VOL_PATH.stat().st_size if VOL_PATH.exists() else 0

        # Generate embedding for semantic search
        print(f"[EMBEDDING] Generating embedding for snapshot {snap_id}...")
        embedding = generate_embedding(body)
        if embedding:
            print(f"[EMBEDDING] Successfully generated embedding ({len(embedding)} dimensions)")
        else:
            print(f"[EMBEDDING] Warning: Failed to generate embedding for {snap_id}")

        # Collect media artifacts from recent tasks for this operator
        # Lazy import to avoid circular dependency
        from Orchestrator.tasks import collect_pending_media_artifacts
        media_artifacts = collect_pending_media_artifacts(operator)
        if media_artifacts:
            print(f"[MINT] Collected {len(media_artifacts)} media artifact(s) for {snap_id}")

        # Update the snapshot index with embedding and media artifacts
        update_snapshot_index(snap_id, byte_start, byte_end, operator, utc, snap_type="normal", embedding=embedding, media_artifacts=media_artifacts if media_artifacts else None)

        arc_path, digest, arc_utc = archive_volume()

        s.last_mint_index = len(s.conversation_log)
        s.conv_turns_since  = 0
        s.conv_tokens_since = 0
        s.ctx_tokens_since  = 0
        s.context_used      = 0

        # Save operator state after mint
        save_operator_state()

        return {"snap_id": snap_id, "assert_sha256": digest, "archived": Path(arc_path).name}


def mint_with_content(operator: str, content: str, reason: str = "DIRECT", snap_type: str = "normal") -> Dict[str, Any]:
    """Mint a snapshot with provided content (for MCP tools, CLI agents, etc.).

    Unlike perform_mint which pulls from conversation log, this creates a snapshot
    directly from the provided content string.

    Args:
        operator: The operator name (e.g., "Brandon-DEV")
        content: The content to save in the snapshot
        reason: Reason for minting (e.g., "DIRECT", "MCP", "AGENT")
        snap_type: Type of snapshot ("normal", "checkpoint", "summary")

    Returns:
        Dict with snap_id and archive info
    """
    verify_gm_or_halt()

    with mint_lock:
        vol1 = read_text_safe(VOL_PATH)
        info1 = parse_tail(vol1)
        utc = now_utc_iso()
        snap_id = next_snap_id_from_tail(info1["tail_id"])

        # Convert content to log lines format
        # Each line prefixed with timestamp and operator
        log_lines = [f"{utc} operator={operator} content: {content}"]

        print(f"[MINT-CONTENT] Creating snapshot {snap_id} for operator {operator}")
        print(f"[MINT-CONTENT] Content length: {len(content)} chars")

        body = render_snapshot_body_v71(
            info1, snap_id, utc, reason, log_lines,
            gauges={"drift": "green", "p": 0, "c": 0, "t": 0, "model": "direct-content", "operator": operator},
            provenance={"gm": False, "recent": [], "relevant": []},
        )

        # Handle race condition
        vol2 = read_text_safe(VOL_PATH)
        info2 = parse_tail(vol2)
        if info2["tail_id"] != info1["tail_id"]:
            info1 = info2
            snap_id = next_snap_id_from_tail(info1["tail_id"])
            body = render_snapshot_body_v71(
                info1, snap_id, utc, reason, log_lines,
                gauges={"drift": "green", "p": 0, "c": 0, "t": 0, "model": "direct-content", "operator": operator},
                provenance={"gm": False, "recent": [], "relevant": []},
            )

        # Get file size before append
        byte_start = VOL_PATH.stat().st_size if VOL_PATH.exists() else 0

        append_snapshot_text(body)

        # Get file size after append
        byte_end = VOL_PATH.stat().st_size if VOL_PATH.exists() else 0

        # Generate embedding for semantic search
        print(f"[EMBEDDING] Generating embedding for snapshot {snap_id}...")
        embedding = generate_embedding(body)
        if embedding:
            print(f"[EMBEDDING] Successfully generated embedding ({len(embedding)} dimensions)")
        else:
            print(f"[EMBEDDING] Warning: Failed to generate embedding for {snap_id}")

        # Update the snapshot index
        update_snapshot_index(snap_id, byte_start, byte_end, operator, utc, snap_type=snap_type, embedding=embedding)

        arc_path, digest, arc_utc = archive_volume()

        return {"snap_id": snap_id, "assert_sha256": digest, "archived": Path(arc_path).name, "byte_range": [byte_start, byte_end]}


# -----------------------------------------------------------------------------
# FastAPI Application Instance
# -----------------------------------------------------------------------------
# The FastAPI app is defined here and exported to app.py via `from Orchestrator.checkpoint import *`
# This placement avoids circular imports since checkpoint.py is imported early in the module chain.
# Routes are registered by decorators in the route modules.
app = FastAPI(title="BlackBox Orchestrator", version="2.0")

# Gzip compress all responses > 500 bytes (huge win over Tailscale)
app.add_middleware(GZipMiddleware, minimum_size=500)

# CORRECTED: Add CORS middleware for Android/Tailscale compatibility
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Allows all origins
    allow_credentials=True,
    allow_methods=["*"],  # Allows all methods
    allow_headers=["*"],  # Allows all headers
)

# Graceful shutdown handler for systemd
