#!/usr/bin/env python3
from __future__ import annotations

"""
fossils - Extracted from Orchestrator/app.py

This module was automatically extracted using byte-offset manifest refactoring.
Original location: Lines 2585-3409

Extraction date: 2025-12-10T21:33:20.741333+00:00
Original SHA-256: 0726d788188cc925e02f384fcfabda2515a19d2c571076dc7f35d3208886dcfb
"""

# Standard library imports
import json
import math
import re
import os
import time
from pathlib import Path
from typing import Dict, Any, List, Optional, Tuple
import traceback

# Local imports
from Orchestrator.config import SNAPSHOT_INDEX, CFG, VOL_PATH, START_RX, END_RX, SNAP_RE
from Orchestrator.volume import read_volume_bytes, read_text_safe

# Additional imports (auto-generated by dependency audit)
from Orchestrator.config import CFG, INCLUDE_OTHERS
from Orchestrator.volume import read_volume_bytes


def cap_chars(text: str, max_chars: int) -> str:
    """Truncate text to max_chars, preserving snapshot structure."""
    if len(text) <= max_chars:
        return text
    lines = text.splitlines()
    if not lines:
        return text[:max_chars]
    start_line = lines[0]
    end_line = lines[-1] if lines[-1].startswith("=== END SNAPSHOT") else ""
    body_lines = lines[1:-1] if end_line else lines[1:]
    body = "\n".join(body_lines)
    budget = max_chars - len(start_line) - len(end_line) - 8
    if budget <= 0:
        return start_line[:max_chars]
    trimmed = body[:budget]
    parts = [start_line, trimmed]
    if end_line: parts.append(end_line)
    return "\n".join(parts)


def hybrid_retrieve(vol_txt: str, query: str, k: int = 3, operator: str = "") -> List[str]:
    """Hybrid retrieval combining keyword (TF-IDF) + semantic (embeddings) search.

    Combines both approaches for best results:
    - Keyword search: Fast, precise for specific terms
    - Semantic search: Understands intent and context

    Returns top k snapshots ranked by combined score.
    """
    # Get more candidates from each method, then combine
    candidate_k = min(k * 5, 20)  # Get 5x candidates from each (up to 20)

    # 1. Keyword search (TF-IDF + n-grams)
    keyword_results = []
    if operator:
        keyword_results = keyword_retrieve_for_operator(vol_txt, query, candidate_k, operator)
    else:
        keyword_results = keyword_retrieve(vol_txt, query, candidate_k)

    # 2. Semantic search (embeddings) - lazy import to avoid circular dependency
    from Orchestrator.monitoring import semantic_search
    semantic_results = semantic_search(query, operator=operator, k=candidate_k)

    # Create snapshot ID to text mapping for keyword results
    snap_to_text = {}
    index = load_snapshot_index()
    vol_bytes = read_volume_bytes(VOL_PATH)

    for snap_id, meta in index.items():
        # Filter by operator if specified - "system" sees all operators
        if operator and operator != "system" and meta.get("operator") != operator:
            continue

        start = meta["byte_start"]
        end = meta["byte_end"]
        if start < len(vol_bytes) and end <= len(vol_bytes):
            snap_bytes = vol_bytes[start:end]
            snap_text = snap_bytes.decode('utf-8', errors='replace')
            snap_to_text[snap_id] = snap_text

    # Normalize keyword scores (map rank to score)
    keyword_scores = {}
    for rank, text in enumerate(keyword_results):
        # Find snap_id for this text
        for snap_id, snap_text in snap_to_text.items():
            if snap_text == text:
                # Score decreases with rank: 1.0 for first, 0.0 for last
                keyword_scores[snap_id] = 1.0 - (rank / max(len(keyword_results), 1))
                break

    # Normalize semantic scores (already 0-1 from cosine similarity)
    semantic_scores = {snap_id: score for snap_id, score in semantic_results}

    # Combine scores with weights
    KEYWORD_WEIGHT = 0.4   # 40% keyword
    SEMANTIC_WEIGHT = 0.6  # 60% semantic

    combined_scores = {}
    all_snap_ids = set(keyword_scores.keys()) | set(semantic_scores.keys())

    for snap_id in all_snap_ids:
        kw_score = keyword_scores.get(snap_id, 0.0)
        sem_score = semantic_scores.get(snap_id, 0.0)
        combined_scores[snap_id] = (KEYWORD_WEIGHT * kw_score) + (SEMANTIC_WEIGHT * sem_score)

    # Sort by combined score and return top k
    sorted_snaps = sorted(combined_scores.items(), key=lambda x: x[1], reverse=True)[:k]

    # Convert back to text
    results = []
    for snap_id, score in sorted_snaps:
        if snap_id in snap_to_text:
            results.append(snap_to_text[snap_id])

    print(f"[HYBRID] Combined {len(keyword_results)} keyword + {len(semantic_results)} semantic results → {len(results)} final")
    return results


def semantic_retrieve(query: str, operator: str = "", k: int = 15, threshold: float = 0.7) -> List[str]:
    """Pure semantic retrieval with threshold filtering.

    Returns snapshots where semantic similarity >= threshold, up to k results.
    Uses embeddings for meaning-based search, separate from keyword search.

    Args:
        query: Search query text
        operator: Filter by operator (empty string = all operators)
        k: Maximum number of results to return
        threshold: Minimum similarity score (0.0-1.0), default 0.7

    Returns:
        List of snapshot texts, sorted by similarity (highest first)
    """
    from Orchestrator.monitoring import semantic_search

    # Get semantic results with scores
    semantic_results = semantic_search(query, operator=operator, k=k * 2)  # Get extra candidates for threshold filtering

    # Filter by threshold
    filtered_results = [(snap_id, score) for snap_id, score in semantic_results if score >= threshold]

    # Limit to k results
    filtered_results = filtered_results[:k]

    if not filtered_results:
        print(f"[SEMANTIC] No results above threshold {threshold} (had {len(semantic_results)} candidates)")
        return []

    # Load index and volume for text retrieval
    index = load_snapshot_index()
    vol_bytes = read_volume_bytes(VOL_PATH)

    # Convert snap_ids to text
    results = []
    for snap_id, score in filtered_results:
        if snap_id in index:
            meta = index[snap_id]
            start = meta["byte_start"]
            end = meta["byte_end"]

            if start < len(vol_bytes) and end <= len(vol_bytes):
                snap_bytes = vol_bytes[start:end]
                snap_text = snap_bytes.decode('utf-8', errors='replace')
                results.append(snap_text)

    print(f"[SEMANTIC] Retrieved {len(results)} snapshots above threshold {threshold} (scores: {[f'{s:.3f}' for _, s in filtered_results[:5]]}{'...' if len(filtered_results) > 5 else ''})")
    return results


# -----------------------------------------------------------------------------
# Retrieval
# -----------------------------------------------------------------------------
# Stop words to filter out (common English words that add noise)
STOP_WORDS = set([
    # Articles & determiners
    'the', 'a', 'an', 'this', 'that', 'these', 'those',
    # Pronouns
    'i', 'you', 'he', 'she', 'it', 'we', 'they', 'me', 'him', 'her', 'us', 'them',
    'my', 'your', 'his', 'her', 'its', 'our', 'their', 'mine', 'yours', 'hers', 'ours', 'theirs',
    'myself', 'yourself', 'himself', 'herself', 'itself', 'ourselves', 'themselves',
    # Prepositions
    'in', 'on', 'at', 'to', 'for', 'with', 'from', 'by', 'about', 'into', 'through',
    'after', 'before', 'between', 'under', 'over', 'above', 'below',
    # Conjunctions
    'and', 'or', 'but', 'because', 'if', 'when', 'while', 'although', 'though', 'unless',
    # Verbs (common auxiliary & copula)
    'be', 'is', 'am', 'are', 'was', 'were', 'been', 'being',
    'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing',
    'will', 'would', 'shall', 'should', 'can', 'could', 'may', 'might', 'must',
    # Question words
    'what', 'where', 'when', 'why', 'how', 'who', 'which', 'whose', 'whom',
    # Common verbs
    'get', 'got', 'gotten', 'go', 'going', 'gone', 'went', 'make', 'made', 'making',
    'take', 'took', 'taken', 'taking', 'come', 'came', 'coming', 'see', 'saw', 'seen', 'seeing',
    'know', 'knew', 'known', 'knowing', 'think', 'thought', 'thinking', 'look', 'looked', 'looking',
    'want', 'wanted', 'wanting', 'give', 'gave', 'given', 'giving', 'use', 'used', 'using',
    'find', 'found', 'finding', 'tell', 'told', 'telling', 'ask', 'asked', 'asking',
    'work', 'worked', 'working', 'seem', 'seemed', 'seeming', 'feel', 'felt', 'feeling',
    'try', 'tried', 'trying', 'leave', 'left', 'leaving', 'call', 'called', 'calling',
    # Adverbs
    'not', 'no', 'yes', 'so', 'just', 'now', 'then', 'there', 'here', 'up', 'down', 'out',
    'only', 'also', 'back', 'even', 'well', 'still', 'too', 'very', 'really', 'quite',
    'rather', 'much', 'more', 'most', 'less', 'least', 'too', 'enough', 'already', 'yet',
    # Quantifiers
    'all', 'some', 'any', 'many', 'few', 'several', 'both', 'each', 'every', 'either', 'neither',
    'one', 'two', 'three', 'first', 'second', 'last', 'next', 'other', 'another',
    # Filler words & discourse markers
    'thing', 'stuff', 'yeah', 'ok', 'okay', 'right', 'actually', 'basically', 'literally',
    'like', 'guess', 'maybe', 'perhaps', 'probably', 'sure', 'anyway', 'whatever',
    # Time references
    'time', 'day', 'year', 'today', 'yesterday', 'tomorrow',
    # Common nouns (too generic)
    'people', 'person', 'man', 'woman', 'child', 'way', 'place', 'thing',
    # Others
    'of', 'as', 'say', 'said', 'says', 'saying', 'something', 'anything', 'everything', 'nothing',
    # Contraction fragments (from apostrophe splitting)
    't', 's', 're', 've', 'll', 'd', 'm',
    'don', 'doesn', 'didn', 'isn', 'aren', 'wasn', 'weren', 'hasn', 'haven', 'hadn',
    'won', 'wouldn', 'shouldn', 'couldn', 'mightn', 'mustn', 'needn', 'shan', 'ain'
])

# Technical terms that should be weighted more heavily in searches
TECHNICAL_TERMS = set([
    'byte', 'bytes', 'index', 'snapshot', 'snap', 'error', 'warning',
    'debug', 'fix', 'bug', 'issue', 'retrieve', 'retrieval', 'context',
    'offset', 'character', 'string', 'decode', 'encode', 'utf',
    'cache', 'file', 'read', 'write', 'mint', 'fossil', 'operator',
    'api', 'endpoint', 'function', 'method', 'class', 'variable',
    'log', 'trace', 'stack', 'exception', 'timeout', 'race', 'condition',
    'lock', 'thread', 'async', 'sync', 'database', 'query', 'sql',
    'hash', 'sha', 'checksum', 'verify', 'validate', 'parse', 'regex'
])

def fossil_operator(text: str) -> str:
    m = OP_RX.search(text or "")
    return (m.group(1).strip() if m else "")

def filter_by_operator(fossils: List[str], op: str) -> List[str]:
    if not fossils: return []
    keep = []
    for f in fossils:
        op_in_fossil = fossil_operator(f)
        if op_in_fossil == op:
            keep.append(f)
        elif INCLUDE_OTHERS and not op_in_fossil:
            keep.append(f)
    return keep

# -----------------------------------------------------------------------------
# Snapshot Index Management (Byte Offset Optimization)
# -----------------------------------------------------------------------------
# In-memory index cache — avoids re-parsing 254MB JSON on every call
_index_cache: Optional[Dict[str, Dict[str, Any]]] = None
_index_cache_mtime: float = 0.0


def load_snapshot_index() -> Dict[str, Dict[str, Any]]:
    """Load the snapshot index, using in-memory cache when possible.

    The cache is invalidated when the file's mtime changes (i.e., after save).
    This avoids parsing 254MB of JSON on every search/mint/status call.
    """
    global _index_cache, _index_cache_mtime
    try:
        if not SNAPSHOT_INDEX.exists():
            return {}
        current_mtime = SNAPSHOT_INDEX.stat().st_mtime
        if _index_cache is not None and current_mtime == _index_cache_mtime:
            return _index_cache
        with open(SNAPSHOT_INDEX, 'r', encoding='utf-8') as f:
            _index_cache = json.load(f)
        _index_cache_mtime = current_mtime
        return _index_cache
    except Exception as e:
        print(f"[WARNING] Failed to load snapshot index: {e}")
    return {}


def get_snapshot_by_id(snap_id: str) -> Optional[Dict[str, Any]]:
    """
    Retrieve a specific snapshot by its ID.

    Args:
        snap_id: Snapshot ID (e.g., "SNAP-20251207-1234")

    Returns:
        Dict with 'content', 'metadata' (operator, timestamp, type), or None if not found
    """
    index = load_snapshot_index()

    if snap_id not in index:
        return None

    meta = index[snap_id]
    vol_bytes = read_volume_bytes(VOL_PATH)

    start = meta.get("byte_start", 0)
    end = meta.get("byte_end", 0)

    if start >= len(vol_bytes) or end > len(vol_bytes):
        return None

    snap_bytes = vol_bytes[start:end]
    content = snap_bytes.decode('utf-8', errors='replace')

    return {
        "snap_id": snap_id,
        "content": content,
        "metadata": {
            "operator": meta.get("operator"),
            "timestamp": meta.get("timestamp"),
            "type": meta.get("type", "normal"),
            "byte_start": start,
            "byte_end": end
        }
    }


def save_snapshot_index(index: Dict[str, Dict[str, Any]]):
    """Save the snapshot index to disk atomically and update the in-memory cache."""
    global _index_cache, _index_cache_mtime
    try:
        SNAPSHOT_INDEX.parent.mkdir(parents=True, exist_ok=True)
        tmp_path = SNAPSHOT_INDEX.with_suffix('.tmp')
        with open(tmp_path, 'w', encoding='utf-8') as f:
            json.dump(index, f, indent=2)
        os.replace(tmp_path, SNAPSHOT_INDEX)
        # Update cache directly — avoid re-reading the file we just wrote
        _index_cache = index
        _index_cache_mtime = SNAPSHOT_INDEX.stat().st_mtime
    except Exception as e:
        print(f"[ERROR] Failed to save snapshot index: {e}")

def rebuild_snapshot_index() -> Dict[str, Dict[str, Any]]:
    """Rebuild the entire snapshot index by scanning the volume file.

    CRITICAL: Works directly on BYTES using byte-compiled regexes so that
    byte offsets are true file positions — no O(n²) char-to-byte conversion.

    IMPORTANT: Preserves existing embeddings when rebuilding to avoid losing
    expensive embedding data.
    """
    print("[INDEX] Rebuilding snapshot index from volume file...")
    start_time = time.time()

    # Load existing index to preserve embeddings
    old_index = load_snapshot_index()
    embeddings_preserved = 0

    index = {}
    if not VOL_PATH.exists():
        return index

    # Read as BYTES — regex directly on bytes gives true byte offsets (O(n))
    vol_bytes = read_volume_bytes(VOL_PATH)

    # Byte-level regexes for START and END markers
    # START captures snap_id and UTC timestamp (always present and consistent)
    START_RX_B = re.compile(rb'=== START SNAPSHOT \xe2\x80\x94 UTC (?P<utc>\d{4}-\d{2}-\d{2}T[\d:]+Z) \xe2\x80\x94 (?P<snap>SNAP-\d{8}-\d+)')
    # END uses snap_id-specific match to avoid cross-boundary jumps
    OP_RX_B = re.compile(rb'OPERATOR:\s*([^\n]+)')

    pos = 0
    count = 0

    while True:
        m_start = START_RX_B.search(vol_bytes, pos)
        if not m_start:
            break
        snap_id = m_start.group("snap").decode('utf-8')
        utc = m_start.group("utc").decode('utf-8')

        # Search for THIS snapshot's specific END marker
        end_pattern = rb'=== END SNAPSHOT \xe2\x80\x94 ' + re.escape(snap_id.encode()) + rb'.*?==='
        m_end = re.search(end_pattern, vol_bytes[m_start.end():m_start.end() + 200000])
        if not m_end:
            # Skip this snapshot — no matching END found
            pos = m_start.end()
            continue

        # Byte positions — m_end is relative to the slice, convert to absolute
        byte_start = m_start.start()
        byte_end = m_start.end() + m_end.end()

        # Extract operator from snapshot bytes
        snap_bytes = vol_bytes[byte_start:byte_end]
        operator = "Unknown"
        op_match = OP_RX_B.search(snap_bytes)
        if op_match:
            operator = op_match.group(1).strip().decode('utf-8', errors='replace')

        # Detect if this is a checkpoint snapshot
        snap_type = "checkpoint" if b"[CHECKPOINT]" in snap_bytes else "normal"

        index[snap_id] = {
            "byte_start": byte_start,
            "byte_end": byte_end,
            "operator": operator,
            "timestamp": utc,
            "type": snap_type
        }

        # Preserve embedding from old index if it exists
        if snap_id in old_index and "embedding" in old_index[snap_id]:
            index[snap_id]["embedding"] = old_index[snap_id]["embedding"]
            embeddings_preserved += 1

        pos = byte_end
        count += 1

        if count % 500 == 0:
            print(f"[INDEX] Processed {count} snapshots...")

    save_snapshot_index(index)
    elapsed = time.time() - start_time
    print(f"[INDEX] Rebuilt index with {count} snapshots in {elapsed:.2f}s")
    if embeddings_preserved > 0:
        print(f"[INDEX] Preserved {embeddings_preserved} embeddings from previous index")
    return index

def update_snapshot_index(snap_id: str, byte_start: int, byte_end: int, operator: str, timestamp: str, snap_type: str = "normal", embedding: Optional[List[float]] = None, media_artifacts: Optional[List[Dict[str, Any]]] = None):
    """Update the index with a newly minted snapshot, including optional embedding and media artifacts.

    Args:
        snap_id: Snapshot ID (e.g., SNAP-20260123-456)
        byte_start: Starting byte offset in volume file
        byte_end: Ending byte offset in volume file
        operator: Operator/user name
        timestamp: UTC timestamp
        snap_type: Type of snapshot ("normal", "checkpoint", etc.)
        embedding: Optional embedding vector for semantic search
        media_artifacts: Optional list of media artifact metadata dicts containing:
            - type: "image", "video", or "music"
            - url: URL path (e.g., /ui/uploads/sunset-over-mountains_abc123.png)
            - task_id: Task ID that generated this media
            - prompt: Prompt used for generation
            - model: Model used for generation
            - aspect_ratio: For images/videos
            - resolution: For images/videos
            - created_at: ISO timestamp
    """
    try:
        print(f"[INDEX] Updating index with {snap_id} (operator: {operator}, type: {snap_type})")
        index = load_snapshot_index()
        print(f"[INDEX] Loaded existing index with {len(index)} entries")
        index[snap_id] = {
            "byte_start": byte_start,
            "byte_end": byte_end,
            "operator": operator,
            "timestamp": timestamp,
            "type": snap_type
        }

        # Add embedding if provided
        if embedding:
            index[snap_id]["embedding"] = embedding
            print(f"[INDEX] Stored embedding for {snap_id} ({len(embedding)} dimensions)")

        # Add media artifacts if provided
        if media_artifacts:
            index[snap_id]["media_artifacts"] = media_artifacts
            print(f"[INDEX] Stored {len(media_artifacts)} media artifact(s) for {snap_id}")

        save_snapshot_index(index)
        print(f"[INDEX] Successfully updated index with {snap_id}, now {len(index)} entries")
    except Exception as e:
        print(f"[ERROR] Failed to update snapshot index: {e}")
        import traceback
        traceback.print_exc()

def split_snapshots(vol_txt: str) -> List[Tuple[str, int, int]]:
    snaps = []
    pos = 0
    while True:
        m_start = START_RX.search(vol_txt, pos)
        if not m_start:
            break
        m_end = END_RX.search(vol_txt, m_start.end())
        if not m_end:
            break
        s = m_start.start()
        e = m_end.end()
        snaps.append((vol_txt[s:e], s, e))
        pos = e
    return snaps

def extract_snap_ids(blocks: List[str]) -> List[str]:
    """Extract snapshot IDs from snapshot text blocks.

    IMPORTANT: Must extract from START marker, not just any SNAP-ID occurrence!
    Snapshots contain provenance references to other snapshots, so a simple
    SNAP_ID_RX.search() will find the wrong ID (from provenance, not header).
    """
    out: List[str] = []
    for b in blocks or []:
        # Extract from START marker specifically
        m = START_RX.search(b)
        if m:
            out.append(m.group("snap"))
        else:
            # Fallback to simple pattern if no START marker (shouldn't happen)
            m = SNAP_ID_RX.search(b)
            if m:
                out.append(m.group(1))
    return out

def get_recent_fossils_for_operator(vol_txt: str, op: str, count: int, cap_chars_each: int) -> List[str]:
    """Get recent snapshots for an operator. Uses index if available for O(1) access.

    IMPORTANT: Byte offsets in the index are BYTE positions, not character positions.
    We must read the file as bytes, slice using byte offsets, then decode individual snapshots.

    Special case: "system" operator can see ALL snapshots from all operators.
    This is needed for outbound calls where the AI needs context from prior conversations.
    """
    index = load_snapshot_index()

    if index:
        # Use index for fast retrieval - MUST use bytes for byte-offset slicing
        # Read file as bytes to allow proper byte-offset indexing
        vol_bytes = read_volume_bytes(VOL_PATH)

        # Filter by operator - "system" sees all operators
        if op == "system":
            matching = [(snap_id, meta) for snap_id, meta in index.items()]
        else:
            matching = [(snap_id, meta) for snap_id, meta in index.items() if meta.get("operator") == op]

        # Sort by snap_id with proper numeric comparison on date and sequence
        def snapshot_sort_key(snap_id: str) -> tuple:
            """Parse SNAP-YYYYMMDD-NNN and return (date_int, seq_int) for proper sorting."""
            try:
                parts = snap_id.split('-')
                date_part = int(parts[1]) if len(parts) > 1 else 0
                seq_part = int(parts[2]) if len(parts) > 2 else 0
                return (date_part, seq_part)
            except (ValueError, IndexError):
                # Fallback for malformed IDs: sort them at the beginning
                return (0, 0)

        matching.sort(key=lambda x: snapshot_sort_key(x[0]))

        # Validate index consistency
        if matching:
            max_byte_end = max(meta["byte_end"] for _, meta in matching)
            if max_byte_end > len(vol_bytes):
                print(f"[WARNING] Index expects file to be at least {max_byte_end} bytes, but vol_bytes is only {len(vol_bytes)} bytes")

        # Get all snapshots (no limit)
        recent = matching[:]
        texts = []

        for snap_id, meta in recent:
            start = meta["byte_start"]
            end = meta["byte_end"]
            # Direct byte-range read using BYTE offsets on BYTES
            if start < len(vol_bytes) and end <= len(vol_bytes):
                snap_bytes = vol_bytes[start:end]
                # Decode the snapshot bytes to text
                snap_text = snap_bytes.decode('utf-8', errors='replace')

                # Verify snapshot integrity
                m = START_RX.search(snap_text)
                if m:
                    extracted_id = m.group("snap")
                    if extracted_id != snap_id:
                        print(f"[ERROR] Index mismatch! Expected {snap_id} at bytes {start}-{end}, but got {extracted_id}")
                else:
                    print(f"[ERROR] No START marker found for {snap_id} at bytes {start}-{end}")

            elif start < len(vol_bytes):
                # Partial snapshot available
                snap_bytes = vol_bytes[start:]
                snap_text = snap_bytes.decode('utf-8', errors='replace')
                print(f"[WARNING] Snapshot {snap_id} byte_end ({end}) exceeds vol_bytes length ({len(vol_bytes)}), text may be incomplete")
            else:
                snap_text = ""
                print(f"[WARNING] Snapshot {snap_id} byte_start ({start}) exceeds vol_bytes length ({len(vol_bytes)})")

            texts.append(cap_chars(snap_text, cap_chars_each))

        final_texts = texts[-count:] if count > 0 else texts
        return final_texts
    else:
        # Fallback to old method if index not available
        snaps = split_snapshots(vol_txt)
        texts = [t for (t, _s, _e) in snaps[:]]  # Get all snapshots (no limit)
        texts = [cap_chars(t, cap_chars_each) for t in texts]
        texts = filter_by_operator(texts, op)
        return texts[-count:] if count>0 else texts

def _simple_stem(word: str) -> str:
    """Improved suffix-based stemming for common English patterns.

    More conservative approach that avoids over-stemming and creating odd stems.
    """
    # Don't stem very short words (< 4 chars)
    if len(word) < 4:
        return word

    # Protected words that should never be stemmed
    protected = {
        'snapshot', 'checkpoint', 'error', 'index', 'bytes', 'fossil',
        'endpoint', 'database', 'async', 'status', 'process'
    }
    if word in protected:
        return word

    # Handle suffixes in order of specificity (longest first to avoid conflicts)
    # Only stem if the root will be meaningful (>= 4 chars)
    suffixes = [
        ('ication', 'ify'),   # modification → modify
        ('ational', 'ate'),   #ational → nate
        ('ization', 'ize'),   # realization → realize
        ('ousness', 'ous'),   # consciousness → conscious
        ('fulness', 'ful'),   # usefulness → useful
        ('iveness', 'ive'),   # effectiveness → effective
        ('ation', 'ate'),     # creation → create
        ('ition', 'it'),      # condition → condit (but protected above)
        ('ement', ''),        # replacement → replac
        ('ment', ''),         # deployment → deploy
        ('ness', ''),         #ingness → ing
        ('ity', ''),          # complexity → complex
        ('ful', ''),          # successful → success
        ('less', ''),         # endless → end
        ('ing', ''),          # indexing → index
        ('ed', ''),           # indexed → index
        ('es', ''),           # indexes → index
        ('s', ''),            # snapshots → snapshot (but be careful)
    ]

    for suffix, replacement in suffixes:
        if word.endswith(suffix) and len(word) > len(suffix) + 2:
            # Calculate what the stem would be
            stem_base = word[:-len(suffix)]
            stemmed = stem_base + replacement

            # Only apply stemming if:
            # 1. The stem is at least 3 characters
            # 2. For 's' suffix, only remove if the word is plural (ends in 's' but not 'ss', 'us', 'is')
            if suffix == 's':
                # Don't remove 's' from: class, bus, this, analysis, etc.
                if word.endswith(('ss', 'us', 'is', 'as', 'os')) or len(stem_base) < 3:
                    continue

            if len(stemmed) >= 3:
                return stemmed

    return word

def _extract_terms(query: str) -> List[str]:
    """Extract meaningful terms from query, filtering stop words and applying stemming."""
    # Use word boundary regex to preserve complete words (including apostrophes and hyphens)
    # This prevents "don't" from becoming ["don", "t"]
    words = [w.lower() for w in re.findall(r"\b[a-zA-Z][a-zA-Z0-9''\-]*[a-zA-Z0-9]\b|\b[a-zA-Z]\b", query or "")]

    # Filter out stop words and very short words (< 3 chars after removing punctuation)
    filtered = []
    for w in words:
        # Remove trailing/leading apostrophes and hyphens for comparison
        clean_word = w.strip("'-'")

        # Skip if it's a stop word or too short
        if clean_word not in STOP_WORDS and len(clean_word) >= 3:
            filtered.append(clean_word)

    # Apply simple stemming to normalize terms
    stemmed = [_simple_stem(w) for w in filtered]

    # Remove duplicates while preserving order
    seen = set()
    unique_terms = []
    for term in stemmed:
        if term not in seen and term not in STOP_WORDS:
            seen.add(term)
            unique_terms.append(term)

    return unique_terms

def _generate_ngrams(query: str, n: int = 2) -> List[str]:
    """Generate n-grams (phrases) from the query for exact phrase matching.

    Filters out n-grams that consist entirely of stop words or contain mostly stop words.
    """
    # Extract words using the same regex as _extract_terms to be consistent
    words = [w.lower() for w in re.findall(r"\b[a-zA-Z][a-zA-Z0-9''\-]*[a-zA-Z0-9]\b|\b[a-zA-Z]\b", query or "")]

    ngrams = []
    for i in range(len(words) - n + 1):
        phrase_words = words[i:i+n]
        phrase = " ".join(phrase_words)

        # Clean words for stop word checking
        clean_words = [w.strip("'-'") for w in phrase_words]

        # Count non-stop words in the phrase
        non_stop_count = sum(1 for w in clean_words if w not in STOP_WORDS and len(w) >= 3)

        # Only keep phrases that:
        # 1. Have at least one meaningful (non-stop) word
        # 2. Don't consist entirely of stop words
        # 3. Have reasonable length (>= 6 characters)
        if non_stop_count >= 1 and len(phrase) >= 6:
            # Further filter: for bigrams, require at least 1 non-stop word
            # For trigrams, require at least 2 non-stop words
            if (n == 2 and non_stop_count >= 1) or (n >= 3 and non_stop_count >= 2):
                ngrams.append(phrase)

    return ngrams

def _compute_tfidf_scores(texts: List[str], terms: List[str]) -> List[float]:
    """Compute TF-IDF scores for each text based on query terms."""
    if not terms:
        return [1.0] * len(texts)
    
    # Document frequency: how many documents contain each term
    df = {}
    for term in terms:
        df[term] = sum(1 for text in texts if term in text.lower())
    
    # Compute TF-IDF score for each document
    scores = []
    num_docs = len(texts)
    for text in texts:
        lc = text.lower()
        score = 0.0
        for term in terms:
            tf = lc.count(term)  # Term frequency in this document
            if tf > 0 and df[term] > 0:
                idf = math.log(num_docs / df[term])  # Inverse document frequency
                score += tf * idf
        scores.append(score)
    return scores

def keyword_retrieve(vol_txt: str, query: str, k: int = 3) -> List[str]:
    """Enhanced keyword retrieval with stop-word filtering, TF-IDF, and n-gram matching."""
    terms = _extract_terms(query)
    bigrams = _generate_ngrams(query, 2)
    trigrams = _generate_ngrams(query, 3)
    
    if not terms and not bigrams and not trigrams:
        return []

    snaps = split_snapshots(vol_txt)
    texts = [text for (text, _s, _e) in snaps[:]]  # Get all snapshots (no limit)
    
    # Compute TF-IDF scores
    tfidf_scores = _compute_tfidf_scores(texts, terms)
    
    # Score each snapshot
    scored = []
    for i, text in enumerate(texts):
        lc = text.lower()
        
        # Base TF-IDF score
        score = tfidf_scores[i]
        
        # Boost for exact phrase matches (n-grams)
        for bigram in bigrams:
            if bigram in lc:
                score += 5.0  # Significant boost for 2-word phrase match
        
        for trigram in trigrams:
            if trigram in lc:
                score += 10.0  # Even larger boost for 3-word phrase match
        
        if score > 0:
            scored.append((score, text))
    
    scored.sort(key=lambda x: x[0], reverse=True)
    return [t for _, t in scored[:k]]

def keyword_retrieve_for_operator(vol_txt: str, query: str, k: int, op: str) -> List[str]:
    """Operator-aware wrapper for enhanced keyword retrieval. Uses index for O(1) operator filtering.

    Special case: "system" operator can see ALL snapshots from all operators.
    """
    index = load_snapshot_index()

    if index:
        # Use index to pre-filter by operator - "system" sees all
        if op == "system":
            matching = [(snap_id, meta) for snap_id, meta in index.items()]
        else:
            matching = [(snap_id, meta) for snap_id, meta in index.items() if meta.get("operator") == op]
        matching.sort(key=lambda x: x[0])
        recent = matching[:]  # Get all snapshots (no limit)

        # FIX 1: Read as BYTES to use byte offsets correctly (not string slicing)
        vol_bytes = read_volume_bytes(VOL_PATH)

        # Extract texts using byte offsets
        texts = []
        for snap_id, meta in recent:
            start = meta["byte_start"]
            end = meta["byte_end"]
            # Use byte-based extraction instead of string slicing
            if start < len(vol_bytes) and end <= len(vol_bytes):
                snap_bytes = vol_bytes[start:end]
                snap_text = snap_bytes.decode('utf-8', errors='replace')
            else:
                snap_text = ""
            texts.append(snap_text)

        # Now run keyword matching on pre-filtered snapshots
        terms = _extract_terms(query)
        bigrams = _generate_ngrams(query, 2)
        trigrams = _generate_ngrams(query, 3)

        if not terms and not bigrams and not trigrams:
            return []

        tfidf_scores = _compute_tfidf_scores(texts, terms)
        scored = []

        num_texts = len(texts)

        for i, text in enumerate(texts):
            lc = text.lower()
            score = tfidf_scores[i]

            # Add technical term boost: if query contains technical terms, boost score
            technical_term_count = sum(1 for term in terms if term in TECHNICAL_TERMS)
            if technical_term_count > 0:
                # Check if this snapshot contains those technical terms
                matched_technical = sum(1 for term in terms if term in TECHNICAL_TERMS and term in lc)
                if matched_technical > 0:
                    technical_boost = (matched_technical / technical_term_count) * 3.0  # Up to +3.0
                    score += technical_boost

            # FIX 2: Add recency bonus - newer snapshots rank higher
            # i=0 is oldest in recent[] list, i=num_texts-1 is newest
            if num_texts > 1:
                recency_factor = i / (num_texts - 1)  # 0.0 to 1.0
                recency_bonus = recency_factor * 2.0  # Up to +2.0 for most recent
                score += recency_bonus

            for bigram in bigrams:
                if bigram in lc:
                    score += 5.0

            for trigram in trigrams:
                if trigram in lc:
                    score += 10.0

            if score > 0:
                scored.append((score, text))

        scored.sort(key=lambda x: x[0], reverse=True)
        base = [t for _, t in scored[:k]]
    else:
        # Fallback to old method if index not available
        base = keyword_retrieve(vol_txt, query, k=999999) if query else []  # Get all results (no limit)
        base = filter_by_operator(base, op)
    
    # Re-score after operator filtering (optional refinement)
    terms = _extract_terms(query)
    bigrams = _generate_ngrams(query, 2)
    trigrams = _generate_ngrams(query, 3)
    
    scored = []
    for t in base:
        lc = t.lower()
        score = sum(lc.count(w) for w in terms) if terms else 1
        
        # Boost for phrases
        for bigram in bigrams:
            if bigram in lc:
                score += 5.0
        for trigram in trigrams:
            if trigram in lc:
                score += 10.0
        
        if score > 0:
            scored.append((score, t))
    
    scored.sort(key=lambda x: x[0], reverse=True)
    return [t for _, t in scored[:k]]

# -----------------------------------------------------------------------------
# Checkpoint System (Per-Operator Memory Compression)
# -----------------------------------------------------------------------------
def get_latest_checkpoint_for_operator(vol_txt: str, op: str) -> Optional[str]:
    """Retrieve the most recent checkpoint snapshot for an operator.

    Checkpoints are special snapshots with type="checkpoint" that contain
    compressed summaries of the last 50 conversation turns.
    """
    index = load_snapshot_index()

    if not index:
        # Fallback: parse volume text to find checkpoints
        blocks = split_snapshots(vol_txt)
        checkpoints = []
        for snap_id, start, end in blocks:
            meta_match = re.search(r'OPERATOR:\s*(\S+)', vol_txt[start:end])
            type_match = re.search(r'TYPE:\s*(\S+)', vol_txt[start:end])

            if meta_match and type_match:
                snap_op = meta_match.group(1)
                snap_type = type_match.group(1)
                if snap_op == op and snap_type == "checkpoint":
                    checkpoints.append((snap_id, vol_txt[start:end]))

        if checkpoints:
            # Return the most recent checkpoint
            checkpoints.sort(key=lambda x: x[0])
            return checkpoints[-1][1]
        return None

    # Use index for fast retrieval
    matching = [
        (snap_id, meta)
        for snap_id, meta in index.items()
        if meta.get("operator") == op and meta.get("type") == "checkpoint"
    ]

    if not matching:
        return None

    # Sort by snap_id and get most recent
    matching.sort(key=lambda x: x[0])
    snap_id, meta = matching[-1]

    # Read the checkpoint snapshot
    vol_bytes = read_volume_bytes(VOL_PATH)
    byte_start = meta.get("byte_start", 0)
    byte_end = meta.get("byte_end", len(vol_bytes))

    try:
        snapshot_bytes = vol_bytes[byte_start:byte_end]
        return snapshot_bytes.decode('utf-8', errors='replace')
    except Exception as e:
        print(f"[CHECKPOINT] Error reading checkpoint {snap_id}: {e}")
        return None


def get_recent_checkpoints_for_operator(vol_txt: str, op: str, count: int = 1) -> list[str]:
    """Retrieve the N most recent checkpoint snapshots for an operator.

    Args:
        vol_txt: Volume text content
        op: Operator name
        count: Number of checkpoints to retrieve (default: 1)

    Returns:
        List of checkpoint snapshot texts, ordered from oldest to newest
    """
    if count <= 0:
        return []

    index = load_snapshot_index()

    if not index:
        # Fallback: parse volume text to find checkpoints
        blocks = split_snapshots(vol_txt)
        checkpoints = []
        for snap_id, start, end in blocks:
            meta_match = re.search(r'OPERATOR:\s*(\S+)', vol_txt[start:end])
            type_match = re.search(r'TYPE:\s*(\S+)', vol_txt[start:end])

            if meta_match and type_match:
                snap_op = meta_match.group(1)
                snap_type = type_match.group(1)
                if snap_op == op and snap_type == "checkpoint":
                    checkpoints.append((snap_id, vol_txt[start:end]))

        if checkpoints:
            # Sort by snap_id and return N most recent
            checkpoints.sort(key=lambda x: x[0])
            return [snap for _, snap in checkpoints[-count:]]
        return []

    # Use index for fast retrieval
    matching = [
        (snap_id, meta)
        for snap_id, meta in index.items()
        if meta.get("operator") == op and meta.get("type") == "checkpoint"
    ]

    if not matching:
        return []

    # Sort by snap_id and get N most recent
    matching.sort(key=lambda x: x[0])
    recent_matches = matching[-count:]

    # Read the checkpoint snapshots
    vol_bytes = read_volume_bytes(VOL_PATH)
    checkpoints = []

    for snap_id, meta in recent_matches:
        byte_start = meta.get("byte_start", 0)
        byte_end = meta.get("byte_end", len(vol_bytes))

        try:
            snapshot_bytes = vol_bytes[byte_start:byte_end]
            checkpoint_text = snapshot_bytes.decode('utf-8', errors='replace')
            checkpoints.append(checkpoint_text)
        except Exception as e:
            print(f"[CHECKPOINT] Error reading checkpoint {snap_id}: {e}")

    return checkpoints
