"""Media artifact retrieval — neutral module to avoid cross-route circular imports.

Single-responsibility module: query recent media artifacts (images, videos,
music) generated by completed tasks for a given operator. Extracted from
``Orchestrator/routes/chat_routes.py`` so that ``Orchestrator/context_builder.py``
(and future voice / agent-WS callers) can import it without pulling in the
chat-routes module graph.

Per-operator scoping is preserved: results merge the operator's own tasks with
``"system"``-operator tasks (which is where tool-generated media is owned).
"""
from __future__ import annotations

from typing import Dict, List

from Orchestrator.models import TaskStatus, TaskType, task_db


def get_recent_media_artifacts(operator: str, limit: int = 10) -> List[Dict]:
    """Get recent media artifacts (images, videos, music) for an operator.

    Returns list of artifacts with URLs that the model can reference for
    subsequent operations like image-to-video conversion.
    """
    artifacts: List[Dict] = []
    media_task_types = {
        TaskType.IMAGE_GENERATION,
        TaskType.VIDEO_GENERATION,
        TaskType.LYRIA_MUSIC,
    }

    # Get all tasks for this operator (or system operator for tool-generated media)
    all_tasks = task_db.get_all_tasks(operator=operator)
    system_tasks = task_db.get_all_tasks(operator="system")

    for task in (all_tasks + system_tasks)[:50]:  # Check last 50 tasks
        if task.task_type not in media_task_types:
            continue
        if task.status != TaskStatus.COMPLETED:
            continue
        if not task.result_url:
            continue

        # Build artifact info
        artifact = {
            "type": task.task_type.value.replace("_generation", "").replace("lyria_", ""),
            "url": task.result_url,
            "prompt": task.prompt[:100] if task.prompt else "",
            "task_id": task.task_id,
            "created_at": task.created_at,
        }

        # Include artifact metadata if available
        if task.result_data and "artifact" in task.result_data:
            artifact.update(task.result_data["artifact"])

        artifacts.append(artifact)

        if len(artifacts) >= limit:
            break

    # Sort by created_at descending (most recent first)
    artifacts.sort(key=lambda x: x.get("created_at", ""), reverse=True)
    return artifacts[:limit]
