#!/usr/bin/env python3
"""
models.py - Extracted from Orchestrator/app.py

This module was automatically extracted using byte-offset manifest refactoring.
Original location: Lines 504-730

Extraction date: 2025-12-10T20:41:49.154024+00:00
Original SHA-256: f5b863cc422c23f88fd7cfa3527f711bfdc37f3ef3a58a318c3cde2ab718a6c9
"""

# Standard library imports
from dataclasses import dataclass, field
from typing import Optional, Any, List, Dict
from enum import Enum
import sqlite3
import json
import re
from pathlib import Path

# Additional imports (auto-generated by dependency audit)
from Orchestrator.config import CFG
from Orchestrator.volume import now_utc_iso


# -----------------------------------------------------------------------------
# Claude Code Agent Session Management
# -----------------------------------------------------------------------------
@dataclass
class AgentSession:
    """Represents a Claude Code CLI session for an operator."""
    session_id: str
    operator: str = ""
    process: Optional[Any] = None  # subprocess.Popen
    pty_master: Optional[int] = None  # PTY file descriptor (for interactive mode)
    mode: str = "streaming"  # "streaming" (print mode) or "interactive" (PTY mode)
    status: str = "idle"  # idle, running, waiting_permission, waiting_ready, completed
    output_buffer: List[str] = field(default_factory=list)
    pending_permission: Optional[Dict] = None
    pending_prompt: str = ""  # Prompt to send after Claude is ready
    working_directory: str = ""
    created_at: str = ""
    last_activity: str = ""
    apps: List[Dict] = field(default_factory=list)  # Registered apps from this session
    is_ready: bool = False  # Whether Claude has shown its ready prompt
    claude_session_id: str = ""  # Claude Code's internal session ID for continuity
    message_count: int = 0  # Number of messages sent in this session
    model: str = "sonnet"  # Claude model to use (opus, sonnet, haiku)
    skip_permissions: bool = True  # Whether to skip permission prompts (default: safe mode)
    # Background execution support
    background_reader: Optional[Any] = None  # Background thread reading process output
    websocket_clients: List[Any] = field(default_factory=list)  # Active WebSocket connections
    output_cursor: int = 0  # Cursor for output buffer position (for reconnection)
    # Snapshot retrieval provenance from build_fossil_context (Plan Task 4)
    provenance: Dict[str, List[str]] = field(default_factory=dict)

@dataclass
class RegisteredApp:
    """Represents a web app created by Claude Code."""
    app_id: str
    name: str
    port: int
    directory: str
    session_id: str
    operator: str
    created_at: str
    status: str = "running"

# Global storage for agent sessions and apps
AGENT_SESSIONS: Dict[str, AgentSession] = {}
APP_REGISTRY: Dict[str, RegisteredApp] = {}
# Persisted agent sessions loaded from disk (operator -> session data dict)
# This is populated by load_operator_state() and used to restore sessions after restart
PERSISTED_AGENT_SESSIONS: Dict[str, dict] = {}

# -----------------------------------------------------------------------------
# GPT-4o Realtime API Session Management
# -----------------------------------------------------------------------------
@dataclass
class RealtimeSession:
    """Represents a GPT-4o Realtime API session for an operator."""
    session_id: str
    operator: str = ""
    openai_ws: Optional[Any] = None      # websockets connection to OpenAI Realtime API
    portal_ws: Optional[Any] = None      # FastAPI WebSocket connection from Portal
    status: str = "idle"                 # idle, connecting, connected, responding, error
    created_at: str = ""
    last_activity: str = ""
    context_injected: bool = False       # Whether initial context has been sent
    audio_format: str = "pcm16"          # Audio format (pcm16 at 24kHz)
    sample_rate: int = 24000             # Audio sample rate
    is_recording: bool = False           # Whether client is currently recording
    is_speaking: bool = False            # Whether AI is currently speaking
    transcript_buffer: str = ""          # Buffer for current response transcript
    conversation: List[Dict] = field(default_factory=list)  # Full conversation log for BlackBox snapshot
    # Reconnection state
    last_ai_message_time: float = 0.0          # For stale connection detection
    reconnect_count: int = 0                   # Track reconnection attempts
    max_reconnects: int = 5                    # Max before giving up
    is_reconnecting: bool = False              # Guard against concurrent reconnects
    intentional_disconnect: bool = False       # User clicked disconnect
    provenance: Dict[str, List[str]] = field(default_factory=dict)  # Snapshot retrieval provenance from build_fossil_context

# Global storage for Realtime sessions
REALTIME_SESSIONS: Dict[str, RealtimeSession] = {}

# -----------------------------------------------------------------------------
# Gemini Live API Session Management
# -----------------------------------------------------------------------------
@dataclass
class GeminiLiveSession:
    """Represents a Gemini Live API session for an operator."""
    session_id: str
    operator: str = ""
    gemini_ws: Optional[Any] = None      # websockets connection to Gemini Live API
    portal_ws: Optional[Any] = None      # FastAPI WebSocket connection from Portal
    status: str = "idle"                 # idle, connecting, connected, responding, error
    created_at: str = ""
    last_activity: str = ""
    context_injected: bool = False       # Whether BidiGenerateContentSetup has been sent
    audio_format: str = "pcm16"          # Audio format
    input_sample_rate: int = 16000       # Gemini expects 16kHz input
    output_sample_rate: int = 24000      # Gemini outputs 24kHz
    is_recording: bool = False           # Whether client is currently recording
    is_speaking: bool = False            # Whether AI is currently speaking
    transcript_buffer: str = ""          # Buffer for current response transcript
    voice: str = "Charon"                # Selected voice for this session
    pending_tool_call: bool = False      # Whether waiting for tool call to complete (prevents duplicate responses)
    user_audio_buffer: List[str] = field(default_factory=list)  # Buffer for user audio chunks (base64 PCM16) for Whisper transcription
    conversation: List[Dict] = field(default_factory=list)  # Full conversation log for BlackBox snapshot
    # Reconnection state
    resumption_handle: Optional[str] = None    # Gemini session resumption token
    last_ai_message_time: float = 0.0          # For stale connection detection
    reconnect_count: int = 0                   # Track reconnection attempts
    max_reconnects: int = 5                    # Max before giving up
    is_reconnecting: bool = False              # Guard against concurrent reconnects
    intentional_disconnect: bool = False       # User clicked disconnect
    provenance: Dict[str, List[str]] = field(default_factory=dict)  # Snapshot retrieval provenance from build_fossil_context

# Global storage for Gemini Live sessions
GEMINI_LIVE_SESSIONS: Dict[str, GeminiLiveSession] = {}

# -----------------------------------------------------------------------------
# xAI Grok Voice Agent API Session Management
# -----------------------------------------------------------------------------
@dataclass
class GrokLiveSession:
    """Represents a xAI Grok Voice Agent API session for an operator."""
    session_id: str
    operator: str = ""
    grok_ws: Optional[Any] = None        # websockets connection to xAI Grok Voice API
    portal_ws: Optional[Any] = None      # FastAPI WebSocket connection from Portal
    status: str = "idle"                 # idle, connecting, connected, responding, error
    created_at: str = ""
    last_activity: str = ""
    context_injected: bool = False       # Whether session.update has been sent
    audio_format: str = "pcm16"          # Audio format
    sample_rate: int = 24000             # Audio sample rate
    is_recording: bool = False           # Whether client is currently recording
    is_speaking: bool = False            # Whether AI is currently speaking
    transcript_buffer: str = ""          # Buffer for current response transcript
    voice: str = "Ara"                   # Selected voice for this session (Ara, Rex, Sal, Eve, Leo)
    conversation: List[Dict] = field(default_factory=list)  # Full conversation log for BlackBox snapshot
    # Reconnection state
    last_ai_message_time: float = 0.0          # For stale connection detection
    reconnect_count: int = 0                   # Track reconnection attempts
    max_reconnects: int = 5                    # Max before giving up
    is_reconnecting: bool = False              # Guard against concurrent reconnects
    intentional_disconnect: bool = False       # User clicked disconnect
    provenance: Dict[str, List[str]] = field(default_factory=dict)  # Snapshot retrieval provenance from build_fossil_context

# Global storage for Grok Live sessions
GROK_LIVE_SESSIONS: Dict[str, GrokLiveSession] = {}

# Permission detection patterns for Claude Code CLI
AGENT_PERMISSION_PATTERNS = [
    re.compile(r"Allow\s+.+\?\s*\([yYnN]/[yYnN]\)", re.I),
    re.compile(r"Do you want to\s+.+\?", re.I),
    re.compile(r"Allow\s+(edit|write|bash|execute|Bash|Edit|Write)", re.I),
    re.compile(r"Yes\s*/\s*No", re.I),
]

# Patterns for auto-approval (file reads only)
AGENT_AUTO_APPROVE_PATTERNS = [
    re.compile(r"Allow\s+read", re.I),
    re.compile(r"Allow\s+Read", re.I),
    re.compile(r"file read", re.I),
]

# ANSI escape code stripper
ANSI_ESCAPE = re.compile(r'\x1B(?:[@-Z\\-_]|\[[0-?]*[ -/]*[@-~])')


class TaskStatus(str, Enum):
    PENDING = "pending"
    PROCESSING = "processing"
    COMPLETED = "completed"
    FAILED = "failed"

class TaskType(str, Enum):
    IMAGE_GENERATION = "image_generation"
    VIDEO_GENERATION = "video_generation"
    AUDIO_ANALYSIS = "audio_analysis"
    GOOGLE_TTS = "google_tts"
    GEMINI_TTS = "gemini_tts"
    LYRIA_MUSIC = "lyria_music"  # Google Lyria-002 music generation
    CHAT = "chat"
    CHECKPOINT = "checkpoint"
    AGENT_CHAT = "agent_chat"  # Claude Code CLI sessions
    BROWSER_USE = "browser_use"  # Legacy — kept for backward compat with old DB rows
    USE_COMPUTER = "use_computer"  # Computer Use agent (Anthropic CU on Linux desktop)
    GEMINI_CU = "gemini_cu"      # Gemini Computer Use (Android/browser via gemini_cu_routes)

@dataclass
class Task:
    task_id: str
    task_type: TaskType
    status: TaskStatus
    created_at: str
    updated_at: str
    prompt: Optional[str] = None
    input_file: Optional[str] = None
    result_url: Optional[str] = None
    result_data: Optional[Dict] = None
    error_message: Optional[str] = None
    progress: int = 0
    operator: Optional[str] = None
    image_data: Optional[Dict] = None  # For image-to-video (stores base64 + mime_type)
    google_video_uri: Optional[str] = None  # Original Google video URI for extensions

class TaskDatabase:
    """SQLite-based task persistence"""
    def __init__(self, db_path: str = "Portal/tasks.db"):
        self.db_path = db_path
        Path(db_path).parent.mkdir(parents=True, exist_ok=True)
        self._init_db()
    
    def _connect(self):
        """Create a SQLite connection with WAL mode and optimized PRAGMAs for concurrent access."""
        conn = sqlite3.connect(self.db_path, timeout=30)
        conn.execute("PRAGMA journal_mode=WAL")
        conn.execute("PRAGMA synchronous=NORMAL")
        conn.execute("PRAGMA cache_size=-64000")
        conn.execute("PRAGMA busy_timeout=5000")
        conn.execute("PRAGMA temp_store=MEMORY")
        return conn

    def _init_db(self):
        conn = self._connect()
        cursor = conn.cursor()
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS tasks (
                task_id TEXT PRIMARY KEY,
                task_type TEXT NOT NULL,
                status TEXT NOT NULL,
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL,
                prompt TEXT,
                input_file TEXT,
                result_url TEXT,
                result_data TEXT,
                error_message TEXT,
                progress INTEGER DEFAULT 0,
                operator TEXT,
                image_data TEXT,
                google_video_uri TEXT
            )
        """)

        # Add image_data column if it doesn't exist (for existing databases)
        try:
            cursor.execute("ALTER TABLE tasks ADD COLUMN image_data TEXT")
            conn.commit()
        except sqlite3.OperationalError:
            pass  # Column already exists

        # Add google_video_uri column if it doesn't exist (for existing databases)
        try:
            cursor.execute("ALTER TABLE tasks ADD COLUMN google_video_uri TEXT")
            conn.commit()
        except sqlite3.OperationalError:
            # Column already exists
            pass

        conn.close()
    
    def save_task(self, task: Task):
        conn = self._connect()
        cursor = conn.cursor()
        cursor.execute("""
            INSERT OR REPLACE INTO tasks
            (task_id, task_type, status, created_at, updated_at, prompt, input_file,
             result_url, result_data, error_message, progress, operator, image_data, google_video_uri)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """, (
            task.task_id, task.task_type, task.status, task.created_at, task.updated_at,
            task.prompt, task.input_file, task.result_url,
            json.dumps(task.result_data) if task.result_data else None,
            task.error_message, task.progress, task.operator,
            json.dumps(task.image_data) if task.image_data else None,
            task.google_video_uri
        ))
        conn.commit()
        conn.close()
    
    def get_task(self, task_id: str) -> Optional[Task]:
        conn = self._connect()
        cursor = conn.cursor()
        cursor.execute("SELECT * FROM tasks WHERE task_id = ?", (task_id,))
        row = cursor.fetchone()
        conn.close()

        if not row:
            return None

        return Task(
            task_id=row[0],
            task_type=TaskType(row[1]),
            status=TaskStatus(row[2]),
            created_at=row[3],
            updated_at=row[4],
            prompt=row[5],
            input_file=row[6],
            result_url=row[7],
            result_data=json.loads(row[8]) if row[8] else None,
            error_message=row[9],
            progress=row[10],
            operator=row[11],
            image_data=json.loads(row[12]) if len(row) > 12 and row[12] else None,
            google_video_uri=row[13] if len(row) > 13 else None
        )
    
    def get_all_tasks(self, operator: Optional[str] = None) -> List[Task]:
        conn = self._connect()
        cursor = conn.cursor()
        if operator:
            cursor.execute("SELECT * FROM tasks WHERE operator = ? ORDER BY created_at DESC", (operator,))
        else:
            cursor.execute("SELECT * FROM tasks ORDER BY created_at DESC")
        rows = cursor.fetchall()
        conn.close()
        
        tasks = []
        for row in rows:
            tasks.append(Task(
                task_id=row[0],
                task_type=TaskType(row[1]),
                status=TaskStatus(row[2]),
                created_at=row[3],
                updated_at=row[4],
                prompt=row[5],
                input_file=row[6],
                result_url=row[7],
                result_data=json.loads(row[8]) if row[8] else None,
                error_message=row[9],
                progress=row[10],
                operator=row[11],
                image_data=json.loads(row[12]) if len(row) > 12 and row[12] else None,
                google_video_uri=row[13] if len(row) > 13 else None
            ))
        return tasks

# Global task management
task_db = TaskDatabase()
task_queue: List[str] = []  # Queue of task IDs
worker_running = False

# Global task queue
task_queue: List[str] = []
