#!/usr/bin/env python3
from __future__ import annotations

"""
monitoring.py - Extracted from Orchestrator/app.py

This module was automatically extracted using byte-offset manifest refactoring.
Original location: Lines 2193-2584

Extraction date: 2025-12-10T21:13:50.353547+00:00
Original SHA-256: 26dd28057885f5acb4f29f669a550fb8a51e2b51eecd8dc5d607f7ee68a75fd7
"""

# Standard library imports
from datetime import datetime, timezone
import math
import sqlite3
import os
import re
import time
from pathlib import Path
from typing import Dict, Any, List, Optional

# External library imports
import shutil
import google.generativeai as genai

# Additional imports (auto-generated by dependency audit)
from Orchestrator.config import ARC_DIR, CFG, CURRENT_OPERATOR, GOOGLE_API_KEY, UPLOADS_DIR, VOL_PATH
from Orchestrator.fossils import load_snapshot_index
from Orchestrator.state import state_by_op


def get_disk_usage() -> Dict[str, Any]:
    """Get disk usage statistics for monitoring."""
    import shutil

    usage = {}

    # Overall disk usage
    stat = shutil.disk_usage("/")
    usage["disk"] = {
        "total_gb": stat.total / (1024 ** 3),
        "used_gb": stat.used / (1024 ** 3),
        "free_gb": stat.free / (1024 ** 3),
        "percent": (stat.used / stat.total) * 100
    }

    # Archive directory size
    archive_size = 0
    archive_count = 0
    if ARC_DIR.exists():
        for f in ARC_DIR.glob("*.txt"):
            archive_size += f.stat().st_size
            archive_count += 1

    usage["archives"] = {
        "count": archive_count,
        "size_mb": archive_size / (1024 ** 2)
    }

    # Uploads directory size
    uploads_size = 0
    uploads_count = 0
    if UPLOADS_DIR.exists():
        for f in UPLOADS_DIR.rglob("*"):
            if f.is_file():
                uploads_size += f.stat().st_size
                uploads_count += 1

    usage["uploads"] = {
        "count": uploads_count,
        "size_mb": uploads_size / (1024 ** 2)
    }

    # Current volume size
    if VOL_PATH.exists():
        usage["volume_mb"] = VOL_PATH.stat().st_size / (1024 ** 2)
    else:
        usage["volume_mb"] = 0

    # Database size
    db_path = Path("Portal/tasks.db")
    if db_path.exists():
        usage["database_mb"] = db_path.stat().st_size / (1024 ** 2)
    else:
        usage["database_mb"] = 0

    # Add warnings
    usage["warnings"] = []
    if usage["disk"]["percent"] > 90:
        usage["warnings"].append("CRITICAL: Disk usage above 90%")
    elif usage["disk"]["percent"] > 80:
        usage["warnings"].append("WARNING: Disk usage above 80%")

    if usage["disk"]["free_gb"] < 5:
        usage["warnings"].append("WARNING: Less than 5GB free space")

    if usage["archives"]["count"] > 300:
        usage["warnings"].append("INFO: Many archive files, cleanup recommended")

    return usage

def cleanup_stuck_tasks(max_hours: int = 24) -> Dict[str, Any]:
    """Clean up tasks that have been stuck in processing/pending for too long."""
    from datetime import datetime, timezone, timedelta

    cleanup_stats = {
        "checked": 0,
        "marked_failed": 0,
        "failed_tasks": []
    }

    try:
        import sqlite3
        db_path = Path("Portal/tasks.db")
        if not db_path.exists():
            return cleanup_stats

        conn = sqlite3.connect(str(db_path))
        cursor = conn.cursor()

        # Find tasks stuck in processing or pending
        cursor.execute("""
            SELECT task_id, task_type, status, created_at, updated_at, prompt
            FROM tasks
            WHERE status IN ('processing', 'pending')
        """)

        stuck_tasks = []
        now = datetime.now(timezone.utc)
        cutoff = now - timedelta(hours=max_hours)

        for row in cursor.fetchall():
            task_id, task_type, status, created_at, updated_at, prompt = row
            cleanup_stats["checked"] += 1

            # Parse the updated_at timestamp
            try:
                updated_time = datetime.fromisoformat(updated_at.replace('Z', '+00:00'))

                # If task hasn't been updated in max_hours, mark as stuck
                if updated_time < cutoff:
                    stuck_tasks.append({
                        "task_id": task_id,
                        "task_type": task_type,
                        "status": status,
                        "hours_stuck": (now - updated_time).total_seconds() / 3600
                    })
            except Exception as e:
                # If we can't parse the time, assume it's old and mark it
                stuck_tasks.append({
                    "task_id": task_id,
                    "task_type": task_type,
                    "status": status,
                    "hours_stuck": "unknown"
                })

        # Mark stuck tasks as failed
        for task in stuck_tasks:
            cursor.execute("""
                UPDATE tasks
                SET status='failed',
                    progress=0,
                    error_message=?,
                    updated_at=?
                WHERE task_id=?
            """, (
                f"Task abandoned - stuck in {task['status']} for >{max_hours} hours",
                now.isoformat().replace('+00:00', 'Z'),
                task['task_id']
            ))
            cleanup_stats["marked_failed"] += 1
            cleanup_stats["failed_tasks"].append({
                "task_id": task["task_id"],
                "task_type": task["task_type"],
                "hours_stuck": task["hours_stuck"]
            })

        conn.commit()
        conn.close()

    except Exception as e:
        cleanup_stats["error"] = str(e)

    return cleanup_stats

def drift_state_for(s: 'OpState') -> str:
    y = 64000
    r = 110000
    total = s.conv_tokens_since + s.ctx_tokens_since
    if total >= r:   return "red"
    if total >= y:   return "yellow"
    return "green"

def drift_state_global() -> str:
    y = 64000
    r = 110000
    if not state_by_op:
        return "green"
    worst = max((s.conv_tokens_since + s.ctx_tokens_since) for s in state_by_op.values())
    if worst >= r:   return "red"
    if worst >= y:   return "yellow"
    return "green"

def cap_chars(text: str, max_chars: int) -> str:
    if len(text) <= max_chars:
        return text
    lines = text.splitlines()
    if not lines:
        return text[:max_chars]
    start_line = lines[0]
    end_line = lines[-1] if lines[-1].startswith("=== END SNAPSHOT") else ""
    body_lines = lines[1:-1] if end_line else lines[1:]
    body = "\n".join(body_lines)
    budget = max_chars - len(start_line) - len(end_line) - 8
    if budget <= 0:
        return start_line[:max_chars]
    trimmed = body[:budget]
    parts = [start_line, trimmed]
    if end_line: parts.append(end_line)
    return "\n".join(parts)

PLAN_LINE_RX = re.compile(r'^\s*(?:\d+[\.\)]|\-|\*|•)\s+', re.M)
def extract_plan(text: str) -> str:
    """Return only the bullet/numbered list portion if present, else ''."""
    lines = text.splitlines()
    plan_lines = [ln for ln in lines if PLAN_LINE_RX.search(ln)]
    if not plan_lines:
        return ""
    start = next(i for i, ln in enumerate(lines) if PLAN_LINE_RX.search(ln))
    return "\n".join(lines[start:]).strip()

def _extract_clean_text(raw):
    """Fallback text extractor for when full JSON parsing fails.

    Strips markdown code fences and tries to present clean content.
    """
    if not isinstance(raw, str):
        return str(raw)

    text = raw.strip()

    # Strip markdown code fences (```json ... ``` or ``` ... ```)
    if text.startswith("```"):
        # Find the end of the opening fence line
        first_newline = text.find('\n')
        if first_newline != -1:
            text = text[first_newline + 1:]

    if text.endswith("```"):
        text = text[:-3]

    # Strip any remaining backticks at edges
    text = text.strip().strip('`').strip()

    # If it looks like truncated JSON, try to extract meaningful content
    if text.startswith('{') and '"ui_reply"' in text:
        # This is likely a truncated JSON response
        # Try to find content after "ui_reply": "
        idx = text.find('"ui_reply"')
        if idx != -1:
            # Find the start of the value
            colon_idx = text.find(':', idx)
            if colon_idx != -1:
                # Skip whitespace and opening quote
                val_start = colon_idx + 1
                while val_start < len(text) and text[val_start] in ' \t\n\r"':
                    val_start += 1
                # Return everything after, even if truncated
                remaining = text[val_start:]
                if remaining:
                    # Clean up any trailing partial JSON
                    # Remove trailing incomplete escape sequences or quotes
                    while remaining and remaining[-1] in '\\"':
                        remaining = remaining[:-1]
                    return remaining.strip()

    return text


# -----------------------------------------------------------------------------
# Snapshot rendering
# -----------------------------------------------------------------------------
def render_snapshot_body_v71(info: dict, snap_id: str, utc: str, reason: str,
                             log_lines: List[str],
                             gauges: dict, provenance: dict) -> str:
    drift = gauges.get("drift", "green")
    p = gauges.get("p", 0); c = gauges.get("c", 0); t = gauges.get("t", p + c)
    model = gauges.get("model", "")
    op_line = gauges.get("operator", CURRENT_OPERATOR)

    gm = "yes" if provenance.get("gm", True) else "no"
    recent = provenance.get("recent", [])
    relevant = provenance.get("relevant", [])

    inc_model   = CFG.getboolean("snapshot","include_model",    fallback=True)
    show_tokens = CFG.getboolean("snapshot","show_tokens",      fallback=True)
    show_drift  = CFG.getboolean("snapshot","show_drift",       fallback=True)
    show_prov   = CFG.getboolean("snapshot","show_provenance",  fallback=True)

    gauges_lines = [f"CONTINUITY: {reason}"]
    if show_drift:  gauges_lines.append(f"DRIFT: {drift}")
    if show_tokens: gauges_lines.append(f"TOKENS (since last mint): prompt={p}, completion={c}, total={t}")
    if inc_model and model: gauges_lines.append(f"MODEL: {model}")
    gauges_lines += [f"OPERATOR: {op_line}", "MODE: Normal"]

    prov_lines = []
    if show_prov:
        prov_lines.append(f"- GM_EXCERPT: {gm}")
        prov_lines.append(f"- Recent fossils: {', '.join(recent) if recent else 'none'}")
        prov_lines.append(f"- Relevant fossils: {', '.join(relevant) if relevant else 'none'}")

    body = (
        f"=== START SNAPSHOT — UTC {utc} — {snap_id} (7.1.0) ===\n"
        "CROSS-FILE BEACON\n"
        "===============================================================================\n"
        f"Tail-first sweep resolved tip = {info['tail_id']}\n"
        f"COUNT=1 | TARGET_ID={snap_id}\n"
        "UFL: OUTSIDE-JUNK IGNORED | BYTES_AFTER_END=0 | BYTES_BEFORE_START=0\n"
        "Result: ✅ Tail lock confirmed\n"
        "===============================================================================\n\n"
        "VOLUME TRACKER\n"
        f"Tail: {info['tail_id']}\n"
        "Next: TBD\n"
        f"Tail Source: {info['tail_id']} — UTC {info['utc']}\n"
        "Mode: NORMAL\n\n"
        "GAUGES\n" + "\n".join(gauges_lines) + "\n\n"
        "SNAPSHOT BODY\n\n"
        "Kernel Index\n"
        f"- Tail: {info['tail_id']}\n"
        f"- Current: {snap_id}\n"
        "- Volume: Appliance/Overseer\n\n"
        "Context Provenance\n" + ("\n".join(prov_lines) + "\n\n" if show_prov else "\n- [disabled]\n\n") +
        "Raw Session Log\n" +
        ( "\n".join(f"- [{i+1}] {ln}" for i, ln in enumerate(log_lines)) if log_lines else "- (no new turns since last mint)\n" ) +
        "\n"
        "Release Notes\n"
        "- Hybrid context window in effect; gauges record drift and token usage.\n\n"
        f"=== END SNAPSHOT — {snap_id} — UTC {utc} ===\n"
    )
    return body

# -----------------------------------------------------------------------------
# Semantic Search & Embeddings
# -----------------------------------------------------------------------------
def generate_embedding(text: str, max_retries: int = 3) -> Optional[List[float]]:
    """Generate embedding for text using Gemini Embedding API.

    Returns None if embedding generation fails after retries.
    """
    if not GOOGLE_API_KEY:
        print("[EMBEDDING] Warning: GOOGLE_API_KEY not configured, skipping embedding generation")
        return None

    # Truncate text if too long (Gemini has token limits)
    max_chars = 10000
    if len(text) > max_chars:
        text = text[:max_chars] + "..."

    for attempt in range(max_retries):
        try:
            result = genai.embed_content(
                model="models/gemini-embedding-001",
                content=text,
                task_type="retrieval_document"
            )
            return result['embedding']
        except Exception as e:
            print(f"[EMBEDDING] Attempt {attempt + 1}/{max_retries} failed: {e}")
            if attempt < max_retries - 1:
                time.sleep(1)  # Brief delay before retry
            else:
                print(f"[EMBEDDING] Failed to generate embedding after {max_retries} attempts")
                return None

def cosine_similarity(vec1: List[float], vec2: List[float]) -> float:
    """Calculate cosine similarity between two vectors."""
    if not vec1 or not vec2 or len(vec1) != len(vec2):
        return 0.0

    dot_product = sum(a * b for a, b in zip(vec1, vec2))
    magnitude1 = math.sqrt(sum(a * a for a in vec1))
    magnitude2 = math.sqrt(sum(b * b for b in vec2))

    if magnitude1 == 0 or magnitude2 == 0:
        return 0.0

    return dot_product / (magnitude1 * magnitude2)

def semantic_search(query: str, operator: str = "", k: int = 10) -> List[Tuple[str, float]]:
    """Perform semantic search using embeddings.

    Returns list of (snapshot_id, similarity_score) tuples, sorted by relevance.

    Special case: "system" operator can see ALL snapshots from all operators.
    This is needed for outbound calls where the AI needs context from prior conversations.
    """
    # Generate query embedding
    query_embedding = generate_embedding(query)
    if not query_embedding:
        print("[SEMANTIC] Query embedding failed, falling back to keyword search")
        return []

    # Load snapshot index
    index = load_snapshot_index()
    if not index:
        return []

    # Calculate similarity with all snapshots
    scores = []
    for snap_id, data in index.items():
        # Filter by operator if specified - "system" sees all operators
        if operator and operator != "system" and data.get("operator") != operator:
            continue

        # Skip if no embedding stored
        if "embedding" not in data or not data["embedding"]:
            continue

        # Calculate similarity
        similarity = cosine_similarity(query_embedding, data["embedding"])
        scores.append((snap_id, similarity))

    # Sort by similarity (highest first) and return top k
    scores.sort(key=lambda x: x[1], reverse=True)
    return scores[:k]

