#!/usr/bin/env python3
from __future__ import annotations

"""
startup.py - Extracted from Orchestrator/app.py

This module was automatically extracted using byte-offset manifest refactoring.
Original location: Lines 3702-3845

Extraction date: 2025-12-10T22:40:50.457843+00:00
Original SHA-256: ef19b35b98d461528de8fae91c27887ef850830798abe8b12e25015e169ea471
"""

# Standard library imports
import logging
import re
import sys
import signal
import threading
from pathlib import Path
from typing import Dict, Any, Optional, List

logger = logging.getLogger("blackbox.startup")

# External library imports
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

# Local imports - Import app from checkpoint to register event handlers
from Orchestrator.checkpoint import app
from Orchestrator.config import SNAPSHOT_INDEX, OPERATOR_STATE_FILE, APPS_REGISTRY_FILE, UPLOADS_DIR, VOL_PATH, START_RX
from Orchestrator.fossils import load_snapshot_index, rebuild_snapshot_index, update_snapshot_index
from Orchestrator.volume import cleanup_old_archives, read_text_safe, read_volume_bytes, cleanup_old_artifacts
from Orchestrator.state import load_operator_state, load_operator_preferences, load_app_registry

# Additional imports (auto-generated by dependency audit)
from Orchestrator.monitoring import cleanup_stuck_tasks, get_disk_usage
from Orchestrator.scheduler import get_scheduler_manager


def shutdown_handler(signum, frame):
    """Handle SIGTERM/SIGINT for graceful shutdown"""
    logger.info("Received signal %s, shutting down gracefully...", signum)
    logger.info("Stopping background worker...")
    # The worker thread is daemon=True, so it will stop when main thread exits
    logger.info("Shutdown complete")
    sys.exit(0)

# Register signal handlers
signal.signal(signal.SIGTERM, shutdown_handler)  # systemd stop
signal.signal(signal.SIGINT, shutdown_handler)   # Ctrl+C

def _incremental_index_update(index, vol_bytes, scan_from_byte):
    """Process only new snapshots from a byte offset instead of full rebuild.

    Scans the volume from `scan_from_byte` forward, indexing any new snapshots
    found in the tail. Instant for typical restarts where only a few snapshots
    were minted since the last clean index.
    """
    import time
    from Orchestrator.fossils import save_snapshot_index
    start_time = time.time()

    tail = vol_bytes[scan_from_byte:]
    START_RX_B = re.compile(rb'=== START SNAPSHOT \xe2\x80\x94 UTC (?P<utc>\d{4}-\d{2}-\d{2}T[\d:]+Z) \xe2\x80\x94 (?P<snap>SNAP-\d{8}-\d+)')
    OP_RX_B = re.compile(rb'OPERATOR:\s*([^\n]+)')

    added = 0
    for m_start in START_RX_B.finditer(tail):
        snap_id = m_start.group("snap").decode('utf-8')
        if snap_id in index:
            continue

        utc = m_start.group("utc").decode('utf-8')

        end_pattern = rb'=== END SNAPSHOT \xe2\x80\x94 ' + re.escape(snap_id.encode()) + rb'.*?==='
        m_end = re.search(end_pattern, tail[m_start.end():m_start.end() + 200000])
        if not m_end:
            continue

        byte_start = scan_from_byte + m_start.start()
        byte_end = scan_from_byte + m_start.end() + m_end.end()

        snap_bytes = vol_bytes[byte_start:byte_end]
        operator = "Unknown"
        op_match = OP_RX_B.search(snap_bytes)
        if op_match:
            operator = op_match.group(1).strip().decode('utf-8', errors='replace')

        snap_type = "checkpoint" if b"[CHECKPOINT]" in snap_bytes else "normal"

        index[snap_id] = {
            "byte_start": byte_start,
            "byte_end": byte_end,
            "operator": operator,
            "timestamp": utc,
            "type": snap_type
        }
        added += 1

    save_snapshot_index(index)
    elapsed = time.time() - start_time
    logger.info("Incremental update: added %d snapshots in %.2fs (total: %d)", added, elapsed, len(index))


# Startup: Initialize or rebuild snapshot index
@app.on_event("startup")
def startup_check_index():
    """Check if snapshot index exists, rebuild if missing or stale. Also run cleanup."""
    logger.info("Checking snapshot index...")

    if not SNAPSHOT_INDEX.exists():
        logger.info("Index not found, rebuilding...")
        rebuild_snapshot_index()
    else:
        try:
            index = load_snapshot_index()
            index_count = len(index)

            if not VOL_PATH.exists():
                logger.info("No volume file found, index is empty")
            else:
                vol_size = VOL_PATH.stat().st_size
                # Check if volume has grown since last indexed snapshot
                max_byte_end = max((v.get("byte_end", 0) for v in index.values()), default=0)

                if vol_size == max_byte_end:
                    logger.info("Index is current with %d snapshots (volume unchanged)", index_count)
                elif vol_size > max_byte_end:
                    new_bytes = vol_size - max_byte_end
                    if new_bytes < 100:
                        # Trailing whitespace/newline — not a real snapshot
                        logger.info("Index is current with %d snapshots (volume has %d trailing bytes)", index_count, new_bytes)
                    else:
                        # Volume has new data — incrementally index only the new tail
                        logger.info("Volume grew by %d bytes since last index, running incremental update...", new_bytes)
                        vol_bytes = read_volume_bytes(VOL_PATH)
                        _incremental_index_update(index, vol_bytes, max_byte_end)
                else:
                    # Volume shrunk or something weird — full rebuild
                    logger.info("Volume size mismatch (indexed up to byte %d, volume is %d bytes), rebuilding...", max_byte_end, vol_size)
                    rebuild_snapshot_index()
        except Exception as e:
            logger.error("Error checking index: %s, rebuilding...", e)
            rebuild_snapshot_index()

    # Load operator state after index is ready
    load_operator_state()

    # Load operator preferences (cross-device sync)
    load_operator_preferences()

    # Load registered apps from disk
    load_app_registry()

    # Run artifact cleanup on startup (4-day retention)
    logger.info("Running artifact cleanup...")
    cleanup_old_artifacts()

    # Run archive cleanup on startup
    logger.info("Running archive cleanup...")
    try:
        cleanup_stats = cleanup_old_archives(days_to_keep=30, max_size_gb=5.0, max_files=200)
        if cleanup_stats["deleted_files"] > 0:
            logger.info("Cleaned up %d archives (%.1f MB freed)",
                        cleanup_stats["deleted_files"], cleanup_stats["deleted_size_mb"])
        logger.info("Archive status: %d files, %.1f MB total",
                    cleanup_stats["remaining_files"], cleanup_stats["remaining_size_mb"])

        # Check disk space
        disk_usage = get_disk_usage()
        if disk_usage["warnings"]:
            for warning in disk_usage["warnings"]:
                logger.warning("%s", warning)
        logger.info("Disk usage: %.1f%%, %.1f GB free",
                    disk_usage["disk"]["percent"], disk_usage["disk"]["free_gb"])

        # Clean up stuck tasks
        logger.info("Checking for stuck tasks...")
        task_cleanup_stats = cleanup_stuck_tasks(max_hours=24)
        if task_cleanup_stats["marked_failed"] > 0:
            logger.info("Marked %d stuck tasks as failed", task_cleanup_stats["marked_failed"])
            for task in task_cleanup_stats["failed_tasks"]:
                hours = task["hours_stuck"]
                hours_str = f"{hours:.1f}" if isinstance(hours, (int, float)) else str(hours)
                logger.info("  - %s task stuck for %s hours", task["task_type"], hours_str)
        else:
            logger.info("No stuck tasks found (%d tasks checked)", task_cleanup_stats["checked"])
    except Exception as e:
        logger.error("Error during cleanup: %s", e)

    # Start Sovereign Browser display
    logger.info("Starting Sovereign Browser display...")
    try:
        from Orchestrator.browser.config import NATIVE_MODE, ACTIVE_DISPLAY, DISPLAY_WIDTH, DISPLAY_HEIGHT
        from Orchestrator.browser.display import ensure_display_running
        if ensure_display_running():
            mode_str = "native desktop" if NATIVE_MODE else "Xvfb virtual"
            logger.info("Sovereign Browser %s display :%s ready (%sx%s)", mode_str, ACTIVE_DISPLAY, DISPLAY_WIDTH, DISPLAY_HEIGHT)
        else:
            logger.warning("Sovereign Browser display failed to start (browser tasks will start it on demand)")
    except Exception as e:
        logger.error("Sovereign Browser display error: %s (will start on demand)", e)

    # Start background worker thread for task processing (lazy import to avoid circular import)
    logger.info("Starting background worker thread...")
    from Orchestrator.tasks import background_worker
    worker_thread = threading.Thread(target=background_worker, daemon=True)
    worker_thread.start()
    logger.info("Background worker thread started")



@app.on_event("startup")
async def startup_scheduler():
    """Start the cron job scheduler."""
    try:
        manager = get_scheduler_manager()
        await manager.start()
        logger.info("Cron scheduler started")
    except Exception as e:
        logger.error("Cron scheduler failed to start: %s", e)


@app.on_event("startup")
async def startup_cellular():
    """Initialize the cellular hotplug monitor (internet failover only).

    AT command telephony (modem, sms, voice) has been removed.
    Telephony now runs on Asterisk/PJSIP via the TG200 gateway.
    The hotplug monitor is retained for USB device detection.
    """
    from Orchestrator.config import CELLULAR_ENABLED
    if not CELLULAR_ENABLED:
        logger.info("Cellular module disabled (CELLULAR_ENABLED=false)")
        return

    try:
        from Orchestrator.cellular.hotplug import start_hotplug_monitor

        # Start hotplug monitor — detects USB modem plug/unplug for internet failover
        await start_hotplug_monitor()
        logger.info("Cellular hotplug monitor active (internet failover only)")
    except Exception as e:
        logger.error("Cellular hotplug monitor error: %s (non-fatal, continuing)", e)


@app.on_event("startup")
async def startup_cellular_internet():
    """Initialize the cellular internet failover manager."""
    from Orchestrator.config import CELLULAR_INTERNET_ENABLED
    if not CELLULAR_INTERNET_ENABLED:
        logger.info("Cellular internet manager disabled (CELLULAR_INTERNET_ENABLED=false)")
        return

    try:
        from Orchestrator.cellular.internet_manager import start_internet_manager
        mgr = await start_internet_manager()
        logger.info("Cellular internet manager active (connection=%s)", mgr._connection_name)
    except Exception as e:
        logger.error("Cellular internet manager error: %s (non-fatal, continuing)", e)


@app.on_event("startup")
async def startup_asterisk():
    """Initialize Asterisk ARI connection and AudioSocket server."""
    from Orchestrator.config import ASTERISK_ENABLED
    if not ASTERISK_ENABLED:
        logger.info("Asterisk integration disabled (ASTERISK_ENABLED=false)")
        return

    try:
        from Orchestrator.asterisk.audio_ipc import init_ipc_client
        from Orchestrator.asterisk.client import init_ari_client

        # Start audio subprocess (runs AudioSocket server in its own process)
        ipc_client = await init_ipc_client()
        if ipc_client:
            logger.info("Audio subprocess started (AudioSocket on port 9092)")
        else:
            logger.warning("Audio subprocess failed to start")

        # Connect to ARI
        ari_client = await init_ari_client()
        if ari_client and ari_client.is_connected:
            # Register inbound call handler
            from Orchestrator.routes.asterisk_routes import handle_inbound_call
            ari_client.on_stasis_start = handle_inbound_call
            logger.info("Asterisk ARI connected, inbound call handler registered")

            # Pre-generate IVR TTS prompts
            try:
                from Orchestrator.asterisk.ivr_audio import ensure_all_prompts
                await ensure_all_prompts()
                logger.info("IVR TTS prompts pre-generated")
            except Exception as e:
                logger.warning("IVR prompt generation failed: %s (non-fatal)", e)
        else:
            logger.warning("Asterisk ARI connection failed (will retry on demand)")

    except Exception as e:
        logger.error("Asterisk initialization error: %s (non-fatal, continuing)", e)


@app.on_event("startup")
async def startup_sms():
    """Initialize the SMS system (AMI client + router)."""
    from Orchestrator.config import ASTERISK_ENABLED
    if not ASTERISK_ENABLED:
        logger.info("SMS system disabled (ASTERISK_ENABLED=false)")
        return

    try:
        from Orchestrator.sms import start_sms_system
        await start_sms_system()
        logger.info("SMS system started (AMI connected, listening for inbound SMS)")
    except Exception as e:
        logger.error("SMS system startup error: %s (non-fatal, continuing)", e)


@app.on_event("shutdown")
async def shutdown_sms():
    """Stop the SMS system."""
    try:
        from Orchestrator.sms import stop_sms_system
        await stop_sms_system()
        logger.info("SMS system stopped")
    except Exception:
        pass


@app.on_event("shutdown")
async def shutdown_asterisk():
    """Disconnect from Asterisk and stop AudioSocket server."""
    try:
        from Orchestrator.asterisk.client import get_ari_client
        client = get_ari_client()
        if client:
            await client.disconnect()
            logger.info("Asterisk ARI disconnected")
    except Exception:
        pass
    try:
        from Orchestrator.asterisk.audio_ipc import get_ipc_client
        client = get_ipc_client()
        if client:
            await client.shutdown()
            logger.info("Audio subprocess stopped")
    except Exception:
        pass


@app.on_event("shutdown")
async def shutdown_cellular_internet():
    """Stop the cellular internet manager."""
    try:
        from Orchestrator.cellular.internet_manager import stop_internet_manager
        await stop_internet_manager()
        logger.info("Cellular internet manager stopped")
    except Exception:
        pass


@app.on_event("shutdown")
async def shutdown_cellular():
    """Stop the cellular hotplug monitor."""
    try:
        from Orchestrator.cellular.hotplug import stop_hotplug_monitor
        await stop_hotplug_monitor()
        logger.info("Cellular hotplug monitor stopped")
    except Exception:
        pass


@app.on_event("shutdown")
async def shutdown_scheduler():
    """Stop the cron job scheduler."""
    try:
        manager = get_scheduler_manager()
        await manager.shutdown()
        logger.info("Cron scheduler stopped")
    except Exception:
        pass

from starlette.middleware.base import BaseHTTPMiddleware

class StaticCacheMiddleware(BaseHTTPMiddleware):
    """Add Cache-Control headers for static assets served from /ui/."""
    async def dispatch(self, request, call_next):
        response = await call_next(request)
        path = request.url.path
        if path.startswith("/ui/"):
            if any(path.endswith(ext) for ext in ('.css', '.js', '.png', '.jpg', '.svg', '.woff2', '.ico')):
                response.headers["Cache-Control"] = "public, max-age=3600, must-revalidate"
            elif path.endswith('.html') or path == "/ui/" or path == "/ui":
                response.headers["Cache-Control"] = "no-cache"
        return response

app.add_middleware(StaticCacheMiddleware)

app.mount("/ui", StaticFiles(directory="Portal", html=True), name="ui")

class ChatIn(BaseModel):
    messages: Optional[list] = None 
    operator: Optional[str] = None
    provider: Optional[str] = None
    model: Optional[str] = None
    
class ImageData(BaseModel):
    data: str  # Base64 encoded image
    mime_type: str

class ReferenceImage(BaseModel):
    """Reference image for Nano Banana Pro style/subject guidance"""
    data: str  # Base64 encoded image data (without data:image/xxx;base64, prefix)
    mimeType: str  # image/jpeg, image/png, image/webp, image/gif

class GenIn(BaseModel):
    prompt: str
    operator: Optional[str] = None
    # Video generation options (Veo 3.1)
    aspectRatio: Optional[str] = "16:9"  # Also used for image generation
    resolution: Optional[str] = "720p"  # For video; images use 1K, 2K, 4K
    duration: Optional[int] = 8  # Duration in seconds (4, 6, or 8)
    durationSeconds: Optional[str] = None  # Legacy - use 'duration' instead
    negativePrompt: Optional[str] = None  # Things to exclude from video
    image: Optional[ImageData] = None  # For image-to-video (base64 data)
    image_url: Optional[str] = None  # For image-to-video (URL like /ui/uploads/image.png)
    # Image generation options (Nano Banana Pro / Gemini Imagen)
    numberOfImages: Optional[int] = 1  # 1-4 images at a time
    referenceImages: Optional[List[ReferenceImage]] = None  # Up to 14 reference images for style guidance

class AudioAnalysisIn(BaseModel):
    file_path: str
    operator: Optional[str] = None
    prompt: Optional[str] = "Generate a transcript with timestamps, identify speakers, and analyze emotions in this audio."

class VideoExtensionIn(BaseModel):
    video_url: str
    prompt: Optional[str] = ""
    operator: Optional[str] = None


# --- NEW: Google SSML Generation ---
class GoogleSSMLIn(BaseModel):
    text: Optional[str] = None
    ssml: Optional[str] = None
    voice_name: str
    speaking_rate: float = 1.0
    pitch: float = 0.0
    operator: Optional[str] = None # Added operator

# --- NEW: Gemini Pro TTS Generation ---
class GeminiProTTSIn(BaseModel):
    text: str
    voice_name: Optional[str] = "Charon"  # Default for single-speaker mode
    operator: Optional[str] = None
    multi_speaker: Optional[bool] = False  # Enable multi-speaker mode
    speakers: Optional[List[Dict[str, str]]] = None  # List of {name, voice} dicts for multi-speaker
    model: Optional[str] = "gemini-2.5-pro-tts"  # Model: gemini-2.5-pro-tts or gemini-2.5-flash-tts

# --- NEW: Lyria-002 Music Generation ---
class LyriaMusicIn(BaseModel):
    prompt: str  # e.g. "Epic orchestral movie trailer music with thundering drums"
    negative_prompt: Optional[str] = None  # e.g. "vocals, singing, speech"
    seed: Optional[int] = None  # For reproducible generation (mutually exclusive with sample_count > 1)
    sample_count: Optional[int] = 1  # Number of variations to generate (1-4, cannot use with seed)
    operator: Optional[str] = None

