#!/usr/bin/env python3
from __future__ import annotations

"""
state.py - Extracted from Orchestrator/app.py

This module was automatically extracted using byte-offset manifest refactoring.
Original location: Lines 287-503

Extraction date: 2025-12-10T21:05:22.680306+00:00
Original SHA-256: 75d666debf7f8622d1965e225ca5739467ce987b89465a4f730f6ff67a28739b
"""

# Standard library imports
import json
import threading
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, Any, List, Optional
from collections import defaultdict

# External library imports
import traceback

# Local imports
from Orchestrator.config import OPERATOR_STATE_FILE, OPERATOR_PREFS_FILE, APPS_REGISTRY_FILE
from Orchestrator.models import RegisteredApp

# Additional imports (auto-generated by dependency audit)
from Orchestrator.config import USERS_DEFAULT
from Orchestrator.models import AgentSession, RegisteredApp


# Global state dictionaries
PERSISTED_AGENT_SESSIONS: Dict[str, Any] = {}
APP_REGISTRY: Dict[str, RegisteredApp] = {}
AGENT_SESSIONS: Dict[str, Any] = {}  # Active agent sessions

# Global locks
task_lock = threading.Lock()  # For task queue operations
mint_lock = threading.Lock()  # For snapshot minting

# -----------------------------------------------------------------------------
# Per-operator state
# -----------------------------------------------------------------------------
@dataclass
class OpState:
    conversation_log: list = field(default_factory=list)
    last_mint_index: int = 0
    conv_turns_since: int = 0
    conv_tokens_since: int = 0
    ctx_tokens_since: int = 0
    context_used: int = 0
    last_mint_ms: int = 0
    last_context_meta: dict = field(default_factory=lambda: {
        "recent_ids": [], "relevant_ids": [],
        "gm_excerpt": True, "model": "", "operator": "",
        "usage_last": {"prompt_tokens": 0, "completion_tokens": 0, "total_tokens": 0},
    })
    # Checkpoint tracking (per-operator)
    total_turns: int = 0  # Total conversation turns for this operator
    last_checkpoint_turn: int = 0  # Turn number of last checkpoint
    last_checkpoint_id: str = ""  # SNAP-ID of most recent checkpoint
    total_tokens: int = 0  # Cumulative token usage for this operator

    def add_conversation_turn(self, turn: dict, max_turns: int = 100):
        """Add a conversation turn with automatic pruning to prevent memory leaks"""
        self.conversation_log.append(turn)
        if len(self.conversation_log) > max_turns:
            items_removed = len(self.conversation_log) - max_turns
            old_index = self.last_mint_index
            self.conversation_log = self.conversation_log[-max_turns:]
            # Adjust last_mint_index to account for pruned items
            self.last_mint_index = max(0, self.last_mint_index - items_removed)

state_by_op: Dict[str, OpState] = defaultdict(OpState)

def get_state(op: str) -> OpState:
    return state_by_op[op or USERS_DEFAULT]

def save_operator_state():
    """Save persistent operator state to JSON file, including agent sessions."""
    try:
        state_data = {}
        for operator, state in state_by_op.items():
            state_data[operator] = {
                "total_turns": state.total_turns,
                "last_checkpoint_turn": state.last_checkpoint_turn,
                "last_checkpoint_id": state.last_checkpoint_id,
                # Note: last_mint_index is not persisted since conversation_log is in-memory only
                "last_mint_ms": state.last_mint_ms,
                "total_tokens": state.total_tokens
            }

        # Also save agent session data for each operator
        # Look through AGENT_SESSIONS to find sessions by operator
        for session_id, session in AGENT_SESSIONS.items():
            if session.operator and session.claude_session_id:
                if session.operator not in state_data:
                    state_data[session.operator] = {}
                state_data[session.operator]["agent_session"] = {
                    "claude_session_id": session.claude_session_id,
                    "message_count": session.message_count,
                    "model": session.model,
                    "working_directory": session.working_directory,
                    "last_activity": session.last_activity
                }

        # Also preserve any persisted agent sessions that aren't currently active
        for operator, persisted in PERSISTED_AGENT_SESSIONS.items():
            if operator in state_data and "agent_session" not in state_data[operator]:
                state_data[operator]["agent_session"] = persisted

        OPERATOR_STATE_FILE.parent.mkdir(parents=True, exist_ok=True)
        with open(OPERATOR_STATE_FILE, 'w') as f:
            json.dump(state_data, f, indent=2)
        print(f"[STATE] Saved operator state for {len(state_data)} operators")
    except Exception as e:
        print(f"[ERROR] Failed to save operator state: {e}")

def load_operator_state():
    """Load persistent operator state from JSON file, including agent sessions."""
    global PERSISTED_AGENT_SESSIONS
    try:
        if not OPERATOR_STATE_FILE.exists():
            print("[STATE] No existing operator state file found, starting fresh")
            return

        with open(OPERATOR_STATE_FILE, 'r') as f:
            state_data = json.load(f)

        for operator, data in state_data.items():
            s = get_state(operator)
            s.total_turns = data.get("total_turns", 0)
            s.last_checkpoint_turn = data.get("last_checkpoint_turn", 0)
            s.last_checkpoint_id = data.get("last_checkpoint_id", "")
            # Reset last_mint_index to 0 since conversation_log is empty after restart
            s.last_mint_index = 0
            s.last_mint_ms = data.get("last_mint_ms", 0)
            s.total_tokens = data.get("total_tokens", 0)

            # Load agent session data if present
            if "agent_session" in data:
                PERSISTED_AGENT_SESSIONS[operator] = data["agent_session"]
                print(f"[STATE]   {operator}: found persisted agent session (claude_id={data['agent_session'].get('claude_session_id', 'N/A')[:8]}..., msgs={data['agent_session'].get('message_count', 0)})")

        print(f"[STATE] Loaded operator state for {len(state_data)} operators")
        print(f"[STATE] Loaded {len(PERSISTED_AGENT_SESSIONS)} persisted agent sessions")
        for op, data in state_data.items():
            print(f"[STATE]   {op}: {data['total_turns']} turns, last checkpoint at turn {data['last_checkpoint_turn']}")
    except Exception as e:
        print(f"[ERROR] Failed to load operator state: {e}")
        import traceback
        traceback.print_exc()

# -----------------------------------------------------------------------------
# Operator Preferences (cross-device sync for voice, etc.)
# -----------------------------------------------------------------------------
OPERATOR_PREFERENCES: Dict[str, dict] = {}

def load_operator_preferences():
    """Load operator preferences from JSON file."""
    global OPERATOR_PREFERENCES
    try:
        if not OPERATOR_PREFS_FILE.exists():
            print("[PREFS] No existing preferences file found, starting fresh")
            return
        with open(OPERATOR_PREFS_FILE, 'r') as f:
            OPERATOR_PREFERENCES = json.load(f)
        print(f"[PREFS] Loaded preferences for {len(OPERATOR_PREFERENCES)} operators")
    except Exception as e:
        print(f"[ERROR] Failed to load operator preferences: {e}")

def save_operator_preferences():
    """Save operator preferences to JSON file."""
    try:
        OPERATOR_PREFS_FILE.parent.mkdir(parents=True, exist_ok=True)
        with open(OPERATOR_PREFS_FILE, 'w') as f:
            json.dump(OPERATOR_PREFERENCES, f, indent=2)
        print(f"[PREFS] Saved preferences for {len(OPERATOR_PREFERENCES)} operators")
    except Exception as e:
        print(f"[ERROR] Failed to save operator preferences: {e}")

def get_operator_preference(operator: str, key: str, default=None):
    """Get a specific preference for an operator."""
    if operator not in OPERATOR_PREFERENCES:
        return default
    return OPERATOR_PREFERENCES[operator].get(key, default)

def set_operator_preference(operator: str, key: str, value):
    """Set a specific preference for an operator and persist."""
    if operator not in OPERATOR_PREFERENCES:
        OPERATOR_PREFERENCES[operator] = {}
    OPERATOR_PREFERENCES[operator][key] = value
    save_operator_preferences()

def save_app_registry():
    """Save registered apps to JSON file for persistence across restarts."""
    try:
        apps_data = []
        # Need to use agent_lock but it's not defined yet at module load time
        # So we iterate directly - this is called from contexts where lock is held
        for app_id, app in APP_REGISTRY.items():
            apps_data.append({
                "app_id": app.app_id,
                "name": app.name,
                "port": app.port,
                "directory": app.directory,
                "session_id": app.session_id,
                "operator": app.operator,
                "created_at": app.created_at,
                "status": app.status
            })

        APPS_REGISTRY_FILE.parent.mkdir(parents=True, exist_ok=True)
        with open(APPS_REGISTRY_FILE, 'w') as f:
            json.dump(apps_data, f, indent=2)
        print(f"[APPS] Saved {len(apps_data)} apps to registry")
    except Exception as e:
        print(f"[ERROR] Failed to save app registry: {e}")

def load_app_registry():
    """Load registered apps from JSON file on startup."""
    try:
        if not APPS_REGISTRY_FILE.exists():
            print("[APPS] No existing apps registry file found, starting fresh")
            return

        with open(APPS_REGISTRY_FILE, 'r') as f:
            apps_data = json.load(f)

        for app_data in apps_data:
            app = RegisteredApp(
                app_id=app_data["app_id"],
                name=app_data["name"],
                port=app_data["port"],
                directory=app_data.get("directory", ""),
                session_id=app_data.get("session_id", ""),
                operator=app_data.get("operator", ""),
                created_at=app_data.get("created_at", ""),
                status=app_data.get("status", "registered")
            )
            APP_REGISTRY[app.app_id] = app

        print(f"[APPS] Loaded {len(apps_data)} apps from registry")
        for app in APP_REGISTRY.values():
            print(f"[APPS]   {app.name} on port {app.port} ({app.operator})")
    except Exception as e:
        print(f"[ERROR] Failed to load app registry: {e}")
        import traceback
        traceback.print_exc()

# Global locks
state_lock = threading.Lock()
mint_lock  = threading.Lock()
task_lock  = threading.Lock()
agent_lock = threading.Lock()  # For agent session management

