#!/usr/bin/env python3
from __future__ import annotations

"""
tasks - Extracted from Orchestrator/app.py

This module was automatically extracted using byte-offset manifest refactoring.
Original location: Lines 731-1758

Extraction date: 2025-12-10T22:43:57.540563+00:00
Original SHA-256: 902790a0b252457803f6617120cd974c32e4a5fb3b1e470a4fcae81ef56ef59a
"""

# Standard library imports
import asyncio
import base64
import json
import uuid
import queue
import time
import re
from typing import Dict, Any, Optional, List
from pathlib import Path

# External library imports
import traceback
import urllib
import requests
from fastapi import HTTPException

# Additional imports (auto-generated by dependency audit)
from Orchestrator.artifacts import parse_and_process_artifacts
from Orchestrator.checkpoint import create_checkpoint_async, perform_mint, should_create_checkpoint
from Orchestrator.config import ANTHROPIC_MODEL_DEFAULT, AUTO_ENABLE, CFG, CURRENT_OPERATOR, DEBOUNCE_MS, DEFAULT_PROVIDER, GEMINI_MODEL_DEFAULT, GOOGLE_API_KEY, GOOGLE_IMAGEN_MODEL, GOOGLE_VEO_MODEL, ON_RED, ON_YELLOW, OPENAI_MODEL_DEFAULT, OUTPUT_SPEC, TOOLVAULT_ENABLED, TOKENS_THRESHOLD, TURNS_THRESHOLD, UPLOADS_DIR, USERS_DEFAULT, VOL_PATH, XAI_MODEL_DEFAULT
from Orchestrator.config import build_output_spec
from Orchestrator.behavioral_core import BEHAVIORAL_CORE_CHAT
from Orchestrator.fossils import extract_snap_ids, get_recent_checkpoints_for_operator, get_recent_fossils_for_operator, hybrid_retrieve, keyword_retrieve_for_operator, semantic_retrieve, _extract_terms, _generate_ngrams
from Orchestrator.monitoring import drift_state_for, extract_plan, _extract_clean_text
from Orchestrator.startup import ChatIn, GeminiProTTSIn, GoogleSSMLIn, LyriaMusicIn
from Orchestrator.state import get_state, save_operator_state, task_lock, state_lock
from Orchestrator.volume import now_utc_iso, read_text_safe
from Orchestrator.models import Task, TaskStatus, TaskType, task_db, task_queue, worker_running
import Orchestrator.models as models_module  # For modifying worker_running global
from Orchestrator.media_index import add_media_entry
# NOTE: call_imagen, call_google_tts_synthesize, call_gemini_tts, call_lyria_music
# are imported lazily inside process_* functions to avoid circular imports
# NOTE: call_openai, call_anthropic, call_gemini are imported lazily inside process_chat_task


def generate_prompt_slug(prompt: str, max_length: int = 30) -> str:
    """Generate URL-safe slug from prompt for human/model readable filenames.

    Args:
        prompt: The generation prompt
        max_length: Maximum length of slug (default 30)

    Returns:
        URL-safe slug string (e.g., "sunset-over-mountains")
    """
    import unicodedata

    # Remove common prefixes that don't add value to the filename
    prompt_lower = prompt.lower()
    prefixes = [
        'generate ', 'create ', 'make ', 'draw ', 'paint ',
        'an image of ', 'a photo of ', 'a picture of ',
        'an image showing ', 'a video of ', 'a video showing ',
        'music for ', 'a song about ', 'audio of '
    ]
    for prefix in prefixes:
        if prompt_lower.startswith(prefix):
            prompt = prompt[len(prefix):]
            break

    # Normalize unicode and convert to ASCII
    slug = unicodedata.normalize('NFKD', prompt).encode('ascii', 'ignore').decode('ascii')

    # Convert to lowercase and replace non-alphanumeric with spaces
    slug = re.sub(r'[^a-z0-9\s]', '', slug.lower())

    # Replace multiple spaces with single hyphen
    slug = re.sub(r'\s+', '-', slug.strip())

    # Truncate at word boundary if too long
    if len(slug) > max_length:
        # Find last hyphen before max_length
        truncated = slug[:max_length]
        last_hyphen = truncated.rfind('-')
        if last_hyphen > 10:  # Only truncate at word boundary if we have enough chars
            slug = truncated[:last_hyphen]
        else:
            slug = truncated

    # Remove trailing hyphens and ensure we have something
    slug = slug.rstrip('-')

    return slug if slug else 'media'


def create_task(task_type: TaskType, operator: Optional[str] = None, **kwargs) -> Task:
    task_id = str(uuid.uuid4())
    now = now_utc_iso()
    task = Task(
        task_id=task_id,
        task_type=task_type,
        status=TaskStatus.PENDING,
        created_at=now,
        updated_at=now,
        operator=operator,
        **kwargs
    )
    task_db.save_task(task)

    with task_lock:
        task_queue.append(task_id)

    return task


def get_recent_media_artifacts(operator: str, limit: int = 10) -> List[Dict]:
    """Get recent media artifacts (images, videos, music) for an operator.

    Returns list of artifacts with URLs that the model can reference for
    subsequent operations like image-to-video conversion.
    """
    artifacts = []
    media_task_types = {TaskType.IMAGE_GENERATION, TaskType.VIDEO_GENERATION, TaskType.LYRIA_MUSIC}

    # Get all tasks for this operator (or system operator for tool-generated media)
    all_tasks = task_db.get_all_tasks(operator=operator)
    system_tasks = task_db.get_all_tasks(operator="system")

    for task in (all_tasks + system_tasks)[:50]:  # Check last 50 tasks
        if task.task_type not in media_task_types:
            continue
        if task.status != TaskStatus.COMPLETED:
            continue
        if not task.result_url:
            continue

        # Build artifact info
        artifact = {
            "type": task.task_type.value.replace("_generation", "").replace("lyria_", ""),
            "url": task.result_url,
            "prompt": task.prompt[:100] if task.prompt else "",
            "task_id": task.task_id,
            "created_at": task.created_at
        }

        # Include artifact metadata if available
        if task.result_data and "artifact" in task.result_data:
            artifact.update(task.result_data["artifact"])

        artifacts.append(artifact)

        if len(artifacts) >= limit:
            break

    # Sort by created_at descending (most recent first)
    artifacts.sort(key=lambda x: x.get("created_at", ""), reverse=True)
    return artifacts[:limit]


def collect_pending_media_artifacts(operator: str, since_timestamp: Optional[str] = None) -> List[Dict]:
    """Collect media artifacts from completed tasks for an operator.

    This function retrieves all completed media generation tasks (image, video, music)
    for the given operator and extracts their artifact metadata for storage in the
    snapshot index.

    Args:
        operator: Operator/user name to filter tasks
        since_timestamp: Optional ISO timestamp to filter tasks created after this time

    Returns:
        List of artifact metadata dicts ready for snapshot index
    """
    artifacts = []
    media_task_types = {TaskType.IMAGE_GENERATION, TaskType.VIDEO_GENERATION, TaskType.LYRIA_MUSIC}

    # Get all tasks for this operator
    all_tasks = task_db.get_all_tasks(operator=operator)

    for task in all_tasks:
        # Only include completed media generation tasks
        if task.task_type not in media_task_types:
            continue
        if task.status != TaskStatus.COMPLETED:
            continue

        # Filter by timestamp if provided
        if since_timestamp and task.created_at < since_timestamp:
            continue

        # Extract artifact from result_data
        if task.result_data and "artifact" in task.result_data:
            artifact = task.result_data["artifact"]
            # Ensure task_id is present
            if "task_id" not in artifact:
                artifact["task_id"] = task.task_id
            artifacts.append(artifact)

    return artifacts

def update_task(task_id: str, **kwargs):
    task = task_db.get_task(task_id)
    if task:
        task.updated_at = now_utc_iso()
        for key, value in kwargs.items():
            if hasattr(task, key):
                setattr(task, key, value)
        task_db.save_task(task)


def background_worker():
    """Process tasks from the queue using a thread pool for concurrency.

    Uses ThreadPoolExecutor so slow tasks (checkpoints, video gen) don't block
    fast tasks (images, TTS). Max 4 concurrent tasks to avoid API rate limits.
    """
    from concurrent.futures import ThreadPoolExecutor, Future
    MAX_CONCURRENT = 4

    models_module.worker_running = True
    print(f"[WORKER] Background worker started (max_concurrent={MAX_CONCURRENT})")

    active_futures: dict[str, Future] = {}  # task_id -> Future

    def _on_task_done(task_id: str, future: Future):
        """Callback when a task completes — clean up tracking."""
        active_futures.pop(task_id, None)
        exc = future.exception()
        if exc:
            print(f"[WORKER] Task {task_id} raised uncaught exception: {exc}")

    with ThreadPoolExecutor(max_workers=MAX_CONCURRENT, thread_name_prefix="task-worker") as pool:
        while models_module.worker_running:
            # Clean up finished futures
            done_ids = [tid for tid, f in active_futures.items() if f.done()]
            for tid in done_ids:
                active_futures.pop(tid, None)

            # Only pop from queue if we have capacity
            if len(active_futures) >= MAX_CONCURRENT:
                time.sleep(0.5)
                continue

            task_id = None
            with task_lock:
                if task_queue:
                    task_id = task_queue.pop(0)

            if task_id:
                task = task_db.get_task(task_id)
                if task and task.status == TaskStatus.PENDING:
                    print(f"[WORKER] Submitting task {task_id} ({task.task_type}) [active={len(active_futures)}]")
                    future = pool.submit(process_task, task)
                    active_futures[task_id] = future
                    future.add_done_callback(lambda f, tid=task_id: _on_task_done(tid, f))
            else:
                time.sleep(2)  # Wait before checking again

def process_task(task: Task):
    """Process a single task based on its type"""
    try:
        update_task(task.task_id, status=TaskStatus.PROCESSING, progress=10)

        if task.task_type == TaskType.IMAGE_GENERATION:
            process_image_generation(task)
        elif task.task_type == TaskType.VIDEO_GENERATION:
            process_video_generation(task)
        elif task.task_type == TaskType.AUDIO_ANALYSIS:
            process_audio_analysis(task)
        elif task.task_type == TaskType.GOOGLE_TTS:
            process_google_tts(task)
        elif task.task_type == TaskType.GEMINI_TTS:
            process_gemini_tts(task)
        elif task.task_type == TaskType.LYRIA_MUSIC:
            process_lyria_music(task)
        elif task.task_type == TaskType.CHAT:
            process_chat_task(task)
        elif task.task_type == TaskType.CHECKPOINT:
            process_checkpoint_task(task)
        elif task.task_type in (TaskType.BROWSER_USE, TaskType.USE_COMPUTER):
            process_browser_use(task)
        elif task.task_type == TaskType.GEMINI_CU:
            # Handled by asyncio.create_task in gemini_cu_routes — skip worker processing
            print(f"[WORKER] Skipping GEMINI_CU task {task.task_id} (handled by async route)")
            return

    except Exception as e:
        print(f"[WORKER] Task {task.task_id} failed: {e}")
        import traceback
        traceback.print_exc()
        update_task(task.task_id,
                   status=TaskStatus.FAILED,
                   error_message=str(e),
                   progress=0)

def process_image_generation(task: Task):
    """Generate image(s) using Google Imagen (Nano Banana Pro)

    Supports multiple images, aspect ratios, resolutions, and reference images.
    Options are stored in task.result_data["options"] by the endpoint.
    """
    from Orchestrator.routes.tts_routes import call_imagen
    update_task(task.task_id, progress=30)

    # Extract options from task.result_data
    options = {}
    if task.result_data and "options" in task.result_data:
        options = task.result_data["options"]
        print(f"[WORKER] Image generation options: {options.get('aspectRatio', '16:9')} @ {options.get('resolution', '1K')}, count={options.get('numberOfImages', 1)}")

    # Generate image(s) with options
    images = call_imagen(task.prompt, GOOGLE_IMAGEN_MODEL, options)

    update_task(task.task_id, progress=70)

    # Save all generated images with prompt-based slug filename
    slug = generate_prompt_slug(task.prompt)
    urls = []
    for i, image_bytes in enumerate(images):
        if len(images) == 1:
            filename = f"{slug}_{task.task_id}.png"
        else:
            filename = f"{slug}_{task.task_id}_{i+1}.png"
        save_path = UPLOADS_DIR / filename
        save_path.write_bytes(image_bytes)
        url = f"/ui/uploads/{filename}"
        urls.append(url)
        print(f"[WORKER] Image {i+1} saved: {filename}")

        # Index the media file for search/list tools
        add_media_entry(
            url=url,
            media_type="image",
            prompt=task.prompt,
            task_id=task.task_id,
            filename=filename,
            file_size=len(image_bytes),
            extra_metadata={
                "aspect_ratio": options.get("aspectRatio", "16:9"),
                "resolution": options.get("resolution", "1K"),
                "model": GOOGLE_IMAGEN_MODEL
            }
        )

    # Use first URL as primary result, store all URLs in result_data
    primary_url = urls[0] if urls else None
    result_data = task.result_data or {}
    result_data["all_urls"] = urls

    # Create artifact metadata for snapshot index
    artifact = {
        "type": "image",
        "url": primary_url,
        "all_urls": urls,
        "task_id": task.task_id,
        "prompt": task.prompt,
        "model": GOOGLE_IMAGEN_MODEL,
        "aspect_ratio": options.get("aspectRatio", "16:9"),
        "resolution": options.get("resolution", "1K"),
        "created_at": now_utc_iso()
    }
    result_data["artifact"] = artifact

    update_task(task.task_id,
               status=TaskStatus.COMPLETED,
               result_url=primary_url,
               result_data=result_data,
               progress=100)
    print(f"[WORKER] Generated {len(urls)} image(s): {urls}")

def process_video_generation(task: Task):
    """Generate video using Veo 3.1 (text-to-video, image-to-video, or video extension)"""
    update_task(task.task_id, progress=20)

    if not GOOGLE_API_KEY:
        raise HTTPException(status_code=400, detail="GOOGLE_API_KEY not configured")

    # Step 1: Initiate video generation
    base_url = "https://generativelanguage.googleapis.com/v1beta"
    predict_url = f"{base_url}/models/{GOOGLE_VEO_MODEL}:predictLongRunning"

    # Build instances payload
    instance = {"prompt": task.prompt}

    # Check if this is a video extension (video URL in result_data)
    # WebSocket handlers wrap in {"options": {...}}, REST handlers use flat structure
    # Need to check both formats: direct keys AND nested in "options"
    video_url_for_extension = None
    if task.result_data:
        # Check direct keys first (REST handlers, /extend/video endpoint)
        if "url" in task.result_data:
            video_url_for_extension = task.result_data["url"]
        elif "video_url" in task.result_data:
            video_url_for_extension = task.result_data["video_url"]
        # Check wrapped format (WebSocket handlers use {"options": {...}})
        elif "options" in task.result_data and isinstance(task.result_data["options"], dict):
            opts = task.result_data["options"]
            if "url" in opts:
                video_url_for_extension = opts["url"]
            elif "video_url" in opts:
                video_url_for_extension = opts["video_url"]

    if video_url_for_extension:
        video_url = video_url_for_extension
        print(f"[WORKER] Video extension mode: extending {video_url}")

        # Extract path from full URL if it's a Tailscale URL
        if video_url.startswith("http://") or video_url.startswith("https://"):
            from urllib.parse import urlparse
            parsed = urlparse(video_url)
            video_url = parsed.path
            print(f"[WORKER] Extracted path from URL: {video_url}")

        # Look up the original Google video URI for extensions
        if video_url.startswith("/ui/uploads/"):
            # Extract task_id from filename
            # Handles both old format ({task_id}.mp4) and new slug format ({slug}_{task_id}.mp4)
            filename = video_url.split("/")[-1]
            base_name = filename.replace(".mp4", "")

            # Check if it's the new slug format (contains underscore with UUID after it)
            # UUID format: 8-4-4-4-12 hex chars (36 chars with dashes)
            if "_" in base_name:
                # Try to extract UUID from the end (after last underscore that precedes a UUID)
                parts = base_name.rsplit("_", 1)
                potential_uuid = parts[-1] if len(parts) > 1 else base_name
                # Check if it looks like a UUID (36 chars with dashes in right places)
                if len(potential_uuid) == 36 and potential_uuid[8] == "-" and potential_uuid[13] == "-":
                    original_task_id = potential_uuid
                else:
                    original_task_id = base_name  # Fallback to full name
            else:
                original_task_id = base_name

            # Look up the original task to get the Google video URI
            original_task = task_db.get_task(original_task_id)

            if original_task and original_task.google_video_uri:
                # Use the stored Google video URI for extension
                instance["video"] = {
                    "uri": original_task.google_video_uri
                }
                print(f"[WORKER] Using stored Google video URI for extension: {original_task.google_video_uri}")
            else:
                # Fallback: No stored URI found (shouldn't happen for Veo-generated videos)
                raise Exception(
                    f"Cannot extend video: No Google video URI found for task {original_task_id}. "
                    f"Video extensions only work with videos generated by Veo."
                )
        else:
            # External URL - use as-is (likely won't work, but try anyway)
            instance["video"] = {
                "uri": video_url
            }
            print(f"[WORKER] Using external video URI: {video_url}")
    # Add image if provided (for image-to-video)
    elif task.image_data:
        instance["image"] = {
            "bytesBase64Encoded": task.image_data["data"],
            "mimeType": task.image_data["mime_type"]
        }
        print(f"[WORKER] Image-to-video mode: animating uploaded image")
    # Check for image_url in result_data (for model-initiated image-to-video)
    # Note: We check both wrapped {"options": {...}} and direct format
    else:
        image_url = None
        if task.result_data:
            raw_data = task.result_data
            if isinstance(raw_data, dict):
                wrapped_opts = raw_data.get("options", {})
                if isinstance(wrapped_opts, dict):
                    image_url = wrapped_opts.get("image_url")
                if not image_url:
                    image_url = raw_data.get("image_url")

        if image_url:
            print(f"[WORKER] Image-to-video mode via URL: {image_url}")

            # Clean URL - remove host prefix if present
            clean_url = image_url
            if clean_url.startswith("http://") or clean_url.startswith("https://"):
                from urllib.parse import urlparse
                parsed = urlparse(clean_url)
                clean_url = parsed.path

            # Resolve to file path
            if clean_url.startswith("/ui/"):
                relative_path = clean_url.replace("/ui/", "")
                file_path = Path("Portal") / relative_path
            else:
                raise Exception(f"Invalid image URL format: {image_url}")

            if not file_path.exists():
                raise Exception(f"Image file not found: {file_path}")

            # Read and encode image
            import base64
            with open(file_path, "rb") as f:
                image_bytes = f.read()

            # Detect MIME type
            suffix = file_path.suffix.lower()
            mime_map = {".png": "image/png", ".jpg": "image/jpeg", ".jpeg": "image/jpeg", ".webp": "image/webp", ".gif": "image/gif"}
            mime_type = mime_map.get(suffix, "image/jpeg")

            instance["image"] = {
                "bytesBase64Encoded": base64.b64encode(image_bytes).decode("utf-8"),
                "mimeType": mime_type
            }
            print(f"[WORKER] Loaded image from {file_path} ({mime_type}, {len(image_bytes)} bytes)")
        else:
            print(f"[WORKER] Text-to-video mode")

    # Extract video options from result_data (if not a video extension)
    # Handle both formats: direct options OR wrapped in {"options": ...}
    raw_result_data = task.result_data or {}
    if "options" in raw_result_data and isinstance(raw_result_data["options"], dict):
        video_options = raw_result_data["options"]
    else:
        video_options = raw_result_data
    is_extension = "url" in raw_result_data or "video_url" in raw_result_data or "url" in video_options or "video_url" in video_options

    # Get aspect ratio and resolution from options
    aspect_ratio = video_options.get("aspectRatio", "16:9")
    resolution = video_options.get("resolution", "720p")
    duration = video_options.get("duration", 8)
    negative_prompt = video_options.get("negativePrompt")

    # Validate 1080p + 8s constraint
    if resolution == "1080p" and duration != 8:
        print(f"[WORKER] Warning: 1080p requires 8s duration. Falling back to 720p.")
        resolution = "720p"

    print(f"[WORKER] Video options: {aspect_ratio}, {duration}s, {resolution}")

    # Build parameters
    parameters = {
        "sampleCount": 1,
        "aspectRatio": aspect_ratio,
        "resolution": resolution
    }

    # Only add durationSeconds for new video generation (not for extensions)
    if not is_extension:
        parameters["durationSeconds"] = duration
        print(f"[WORKER] Duration: {duration} seconds")

    # Add negative prompt if provided (appended to prompt for filtering)
    actual_prompt = task.prompt
    if negative_prompt and not is_extension:
        # Note: Veo doesn't have native negative prompt, but we can append "without: ..."
        actual_prompt = f"{task.prompt}. Avoid: {negative_prompt}."
        instance["prompt"] = actual_prompt
        print(f"[WORKER] Negative prompt appended: {negative_prompt}")

    payload = {
        "instances": [instance],
        "parameters": parameters
    }
    
    print(f"[WORKER] Initiating Veo 3.1 video generation...")
    response = requests.post(
        predict_url,
        headers={
            "x-goog-api-key": GOOGLE_API_KEY,
            "Content-Type": "application/json"
        },
        json=payload,
        timeout=30
    )

    # Log error details if request failed
    if response.status_code != 200:
        try:
            error_data = response.json()
            print(f"[WORKER] API Error Response: {error_data}")
        except:
            print(f"[WORKER] API Error (no JSON): {response.text[:500]}")

    response.raise_for_status()
    data = response.json()
    
    operation_name = data.get("name")
    if not operation_name:
        raise Exception("No operation name returned from Veo API")
    
    print(f"[WORKER] Operation started: {operation_name}")
    update_task(task.task_id, progress=30)
    
    # Step 2: Poll for completion
    poll_url = f"{base_url}/{operation_name}"
    max_attempts = 120  # 20 minutes max (10 second intervals)
    attempt = 0
    
    while attempt < max_attempts:
        time.sleep(10)  # Poll every 10 seconds
        attempt += 1
        
        # Update progress gradually
        progress = min(30 + (attempt * 0.5), 80)
        update_task(task.task_id, progress=int(progress))
        
        poll_response = requests.get(
            poll_url,
            headers={"x-goog-api-key": GOOGLE_API_KEY},
            timeout=30
        )
        poll_response.raise_for_status()
        poll_data = poll_response.json()
        
        if poll_data.get("done"):
            print(f"[WORKER] Video generation complete!")
            update_task(task.task_id, progress=85)

            # Step 3: Check for RAI filtering (content policy rejection)
            generate_response = poll_data.get("response", {}).get("generateVideoResponse", {})
            if "raiMediaFilteredCount" in generate_response:
                filtered_count = generate_response.get("raiMediaFilteredCount", 0)
                filtered_reasons = generate_response.get("raiMediaFilteredReasons", [])
                reason_str = "; ".join(filtered_reasons) if filtered_reasons else "Content policy violation"
                raise Exception(f"Video blocked by Google content policy ({filtered_count} filtered): {reason_str}")

            # Step 4: Extract video URI and download
            try:
                video_uri = generate_response["generatedSamples"][0]["video"]["uri"]
            except (KeyError, IndexError) as e:
                raise Exception(f"Could not extract video URI from response: {poll_data}")
            
            # Download the video
            print(f"[WORKER] Downloading video from: {video_uri}")
            video_response = requests.get(
                video_uri,
                headers={"x-goog-api-key": GOOGLE_API_KEY},
                timeout=300,
                stream=True
            )
            video_response.raise_for_status()
            
            # Save video with prompt-based slug filename
            slug = generate_prompt_slug(task.prompt)
            filename = f"{slug}_{task.task_id}.mp4"
            save_path = UPLOADS_DIR / filename
            with open(save_path, 'wb') as f:
                for chunk in video_response.iter_content(chunk_size=8192):
                    f.write(chunk)

            url = f"/ui/uploads/{filename}"

            # Index the media file for search/list tools
            file_size = save_path.stat().st_size if save_path.exists() else None
            add_media_entry(
                url=url,
                media_type="video",
                prompt=task.prompt,
                task_id=task.task_id,
                filename=filename,
                file_size=file_size,
                extra_metadata={
                    "aspect_ratio": aspect_ratio,
                    "resolution": resolution,
                    "duration": duration,
                    "model": GOOGLE_VEO_MODEL,
                    "google_video_uri": video_uri
                }
            )

            # Create artifact metadata for snapshot index
            result_data = task.result_data or {}
            artifact = {
                "type": "video",
                "url": url,
                "task_id": task.task_id,
                "prompt": task.prompt,
                "model": GOOGLE_VEO_MODEL,
                "aspect_ratio": aspect_ratio,
                "resolution": resolution,
                "duration": duration,
                "google_video_uri": video_uri,
                "created_at": now_utc_iso()
            }
            result_data["artifact"] = artifact

            update_task(task.task_id,
                       status=TaskStatus.COMPLETED,
                       result_url=url,
                       result_data=result_data,
                       progress=100,
                       google_video_uri=video_uri)  # Store original Google URI for extensions
            print(f"[WORKER] Video saved: {url}")
            print(f"[WORKER] Stored Google video URI for extensions: {video_uri}")
            return
        
        if poll_data.get("error"):
            error_msg = poll_data["error"].get("message", "Unknown error")
            raise Exception(f"Veo API error: {error_msg}")
    
    raise Exception("Video generation timed out after 20 minutes")

def process_audio_analysis(task: Task):
    """Analyze audio using Gemini"""
    update_task(task.task_id, progress=20)
    
    if not GOOGLE_API_KEY:
        raise HTTPException(status_code=400, detail="GOOGLE_API_KEY not configured")
    
    # Step 1: Upload audio file to Gemini Files API
    file_path = Path(task.input_file)
    if not file_path.exists():
        raise Exception(f"Audio file not found: {task.input_file}")
    
    print(f"[WORKER] Uploading audio file to Gemini Files API...")
    
    # Determine MIME type using standard MIME types
    # Based on Gemini API examples at https://ai.google.dev/api/files
    mime_type_map = {
        ".mp3": "audio/mpeg",   # Standard MIME type for MP3
        ".wav": "audio/wav",
        ".m4a": "audio/mp4",    # M4A is MPEG-4 audio container
        ".mp4": "audio/mp4",
        ".aac": "audio/aac",
        ".ogg": "audio/ogg",
        ".flac": "audio/flac",
        ".aiff": "audio/aiff"
    }
    mime_type = mime_type_map.get(file_path.suffix.lower(), "audio/mpeg")

    print(f"[WORKER] File: {file_path.name}, Extension: {file_path.suffix.lower()}, MIME type: {mime_type}")

    # Read file
    audio_bytes = file_path.read_bytes()
    num_bytes = len(audio_bytes)

    print(f"[WORKER] File size: {num_bytes} bytes")

    # Initial resumable upload request
    print(f"[WORKER] Starting resumable upload to Gemini Files API...")
    upload_url_response = requests.post(
        "https://generativelanguage.googleapis.com/upload/v1beta/files",
        headers={
            "x-goog-api-key": GOOGLE_API_KEY,
            "X-Goog-Upload-Protocol": "resumable",
            "X-Goog-Upload-Command": "start",
            "X-Goog-Upload-Header-Content-Length": str(num_bytes),
            "X-Goog-Upload-Header-Content-Type": mime_type,
            "Content-Type": "application/json"
        },
        json={"file": {"display_name": file_path.name}},
        timeout=30
    )

    # Check for errors with detailed logging
    if upload_url_response.status_code != 200:
        error_body = upload_url_response.text
        print(f"[WORKER] ERROR: Upload initiation failed with status {upload_url_response.status_code}")
        print(f"[WORKER] ERROR: Response body: {error_body}")
        raise Exception(f"Gemini Files API returned {upload_url_response.status_code}: {error_body}")

    upload_url_response.raise_for_status()
    upload_url = upload_url_response.headers.get("x-goog-upload-url")
    
    if not upload_url:
        raise Exception("No upload URL received from Gemini Files API")
    
    update_task(task.task_id, progress=40)
    
    # Upload the actual file bytes
    print(f"[WORKER] Uploading {num_bytes} bytes...")
    upload_response = requests.post(
        upload_url,
        headers={
            "Content-Length": str(num_bytes),
            "X-Goog-Upload-Offset": "0",
            "X-Goog-Upload-Command": "upload, finalize"
        },
        data=audio_bytes,
        timeout=300
    )
    upload_response.raise_for_status()
    file_info = upload_response.json()
    file_uri = file_info["file"]["uri"]
    
    print(f"[WORKER] File uploaded: {file_uri}")
    update_task(task.task_id, progress=60)
    
    # Step 2: Generate content with Gemini
    prompt = task.result_data.get("prompt") if task.result_data else None
    if not prompt:
        prompt = "Generate a detailed transcript with timestamps, identify speakers if multiple people are present, and analyze the emotional tone and key topics discussed in this audio."
    
    generate_url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent"
    generate_payload = {
        "contents": [{
            "parts": [
                {"text": prompt},
                {"file_data": {"mime_type": mime_type, "file_uri": file_uri}}
            ]
        }]
    }
    
    print(f"[WORKER] Analyzing audio with Gemini...")
    generate_response = requests.post(
        generate_url,
        headers={
            "x-goog-api-key": GOOGLE_API_KEY,
            "Content-Type": "application/json"
        },
        json=generate_payload,
        timeout=120
    )
    generate_response.raise_for_status()
    analysis = generate_response.json()
    
    update_task(task.task_id, progress=90)
    
    # Extract text response
    try:
        text_result = analysis["candidates"][0]["content"]["parts"][0]["text"]
    except (KeyError, IndexError):
        text_result = json.dumps(analysis, indent=2)
    
    # Save result
    result_data = {
        "transcript": text_result,
        "file_uri": file_uri,
        "analysis": analysis
    }
    
    update_task(task.task_id,
               status=TaskStatus.COMPLETED,
               result_data=result_data,
               progress=100)
    print(f"[WORKER] Audio analysis complete")

def process_google_tts(task: Task):
    """Generate Google TTS audio"""
    from Orchestrator.routes.tts_routes import call_google_tts_synthesize
    update_task(task.task_id, progress=30)

    inp_data = task.result_data or {}
    inp = GoogleSSMLIn(**inp_data)
    audio_bytes = call_google_tts_synthesize(inp)
    
    update_task(task.task_id, progress=70)
    filename = f"{task.task_id}.mp3"
    save_path = UPLOADS_DIR / filename
    save_path.write_bytes(audio_bytes)
    
    url = f"/ui/uploads/{filename}"
    update_task(task.task_id,
               status=TaskStatus.COMPLETED,
               result_url=url,
               progress=100)
    print(f"[WORKER] Google TTS generated: {url}")

def process_gemini_tts(task: Task):
    """Generate Gemini Pro TTS audio"""
    from Orchestrator.routes.tts_routes import call_gemini_tts
    update_task(task.task_id, progress=30)

    inp_data = task.result_data or {}
    inp = GeminiProTTSIn(**inp_data)
    wav_bytes = call_gemini_tts(inp)  # call_gemini_tts already returns WAV bytes

    update_task(task.task_id, progress=70)
    filename = f"{task.task_id}.wav"
    save_path = UPLOADS_DIR / filename
    save_path.write_bytes(wav_bytes)

    url = f"/ui/uploads/{filename}"
    update_task(task.task_id,
               status=TaskStatus.COMPLETED,
               result_url=url,
               progress=100)
    print(f"[WORKER] Gemini Pro TTS generated: {url}")

def process_lyria_music(task: Task):
    """Generate music using Google Lyria-002
    Supports generating multiple variations via sample_count parameter.
    """
    from Orchestrator.routes.tts_routes import call_lyria_music
    update_task(task.task_id, progress=20)

    inp_data = task.result_data or {}
    inp = LyriaMusicIn(**inp_data)

    sample_count = inp.sample_count if inp.sample_count else 1
    print(f"[WORKER] Generating {sample_count} music variation(s): {inp.prompt[:80]}...")
    update_task(task.task_id, progress=40)

    # call_lyria_music now returns a list of audio samples
    audio_samples = call_lyria_music(inp)

    update_task(task.task_id, progress=80)

    # Save all audio samples with prompt-based slug filename
    slug = generate_prompt_slug(inp.prompt)
    urls = []
    total_bytes = 0
    for i, wav_bytes in enumerate(audio_samples):
        if len(audio_samples) == 1:
            filename = f"{slug}_{task.task_id}_music.wav"
        else:
            filename = f"{slug}_{task.task_id}_music_{i+1}.wav"
        save_path = UPLOADS_DIR / filename
        save_path.write_bytes(wav_bytes)
        url = f"/ui/uploads/{filename}"
        urls.append(url)
        total_bytes += len(wav_bytes)
        print(f"[WORKER] Saved variation {i+1}: {filename} ({len(wav_bytes)} bytes)")

        # Index the media file for search/list tools
        add_media_entry(
            url=url,
            media_type="audio",
            prompt=inp.prompt,
            task_id=task.task_id,
            filename=filename,
            file_size=len(wav_bytes),
            extra_metadata={
                "model": "lyria-002",
                "variation": i + 1 if len(audio_samples) > 1 else None,
                "sample_count": sample_count
            }
        )

    # Use first URL as primary result, store all URLs in result_data
    primary_url = urls[0] if urls else None
    result_data = task.result_data or {}
    result_data["all_urls"] = urls
    result_data["variation_count"] = len(urls)

    # Create artifact metadata for snapshot index
    artifact = {
        "type": "music",
        "url": primary_url,
        "all_urls": urls,
        "task_id": task.task_id,
        "prompt": inp.prompt,
        "model": "lyria-002",
        "sample_count": sample_count,
        "total_bytes": total_bytes,
        "created_at": now_utc_iso()
    }
    result_data["artifact"] = artifact

    update_task(task.task_id,
               status=TaskStatus.COMPLETED,
               result_url=primary_url,
               result_data=result_data,
               progress=100)
    print(f"[WORKER] Lyria music generated: {len(urls)} variation(s), {total_bytes} bytes total")

def process_checkpoint_task(task: Task):
    """Process a checkpoint creation task"""
    try:
        update_task(task.task_id, progress=20)

        operator = task.operator or USERS_DEFAULT
        manual = task.result_data.get("manual", False) if task.result_data else False

        print(f"[WORKER] Creating checkpoint for {operator} (manual={manual})")

        update_task(task.task_id, progress=40)

        # Run checkpoint function (synchronous — uses requests.post internally)
        create_checkpoint_async(operator, manual=manual)

        update_task(task.task_id,
                   status=TaskStatus.COMPLETED,
                   result_data={"operator": operator, "manual": manual},
                   progress=100)

        print(f"[WORKER] Checkpoint created successfully for {operator}")

    except Exception as e:
        import traceback
        error_msg = str(e)
        trace = traceback.format_exc()
        print(f"[WORKER] Checkpoint task failed: {error_msg}\n{trace}")

        update_task(task.task_id,
                   status=TaskStatus.FAILED,
                   error_message=error_msg,
                   progress=0)

def process_browser_use(task: Task):
    """Process a Sovereign Browser task using Anthropic Computer Use."""
    import asyncio

    update_task(task.task_id, progress=20)
    print(f"[WORKER] Starting Sovereign Browser task {task.task_id}")

    try:
        from Orchestrator.browser.agent_loop import BrowserSession
        from Orchestrator.browser.config import SESSION_TIMEOUT

        prompt = task.prompt or ""
        url = (task.result_data or {}).get("url")
        operator = task.operator or "system"

        session = BrowserSession(task_id=task.task_id, operator=operator)
        update_task(task.task_id, progress=30)

        # Run the async agent loop in a new event loop
        result = asyncio.run(
            asyncio.wait_for(
                session.run(prompt=prompt, url=url),
                timeout=SESSION_TIMEOUT + 30
            )
        )

        update_task(task.task_id, progress=90)

        if result.get("success"):
            update_task(
                task.task_id,
                status=TaskStatus.COMPLETED,
                result_url=result.get("final_screenshot"),
                result_data={
                    **(task.result_data or {}),
                    "result_text": result.get("result_text", ""),
                    "screenshots": result.get("screenshots", []),
                    "final_screenshot": result.get("final_screenshot"),
                    "steps": result.get("steps", 0),
                    "tokens": result.get("tokens", {}),
                },
                progress=100,
            )
            print(f"[WORKER] Browser task {task.task_id} completed: {result.get('steps', 0)} steps, {len(result.get('screenshots', []))} screenshots")

            # Auto-snapshot: send summary to /chat for auto-mint
            try:
                import requests as req
                screenshots = result.get("screenshots", [])
                summary = (
                    f"COMPUTER USE AGENT — TASK RESULT\n\n"
                    f"Task ID: {task.task_id}\n"
                    f"Prompt: {task.prompt[:300] if task.prompt else 'N/A'}\n"
                    f"Steps: {result.get('steps', 0)}\n"
                    f"Screenshots: {len(screenshots)}\n\n"
                    f"Result:\n{result.get('result_text', '')[:1000]}\n\n"
                    f"Screenshots captured: {', '.join(screenshots[-5:])}"
                )
                req.post(
                    "http://localhost:9091/chat",
                    json={
                        "operator": operator,
                        "messages": [{"role": "user", "content": summary}],
                        "provider": "google",
                        "model": "gemini-2.5-flash",
                        "streaming": False,
                    },
                    timeout=30
                )
                print(f"[WORKER] Auto-snapshot sent for CU task {task.task_id}")
            except Exception as snap_err:
                print(f"[WORKER] Auto-snapshot failed (non-fatal): {snap_err}")
        else:
            update_task(
                task.task_id,
                status=TaskStatus.FAILED,
                error_message=result.get("result_text", "Browser task failed"),
                result_data={
                    **(task.result_data or {}),
                    "screenshots": result.get("screenshots", []),
                    "steps": result.get("steps", 0),
                },
                progress=0,
            )
            print(f"[WORKER] Browser task {task.task_id} failed: {result.get('result_text')}")

    except asyncio.TimeoutError:
        update_task(
            task.task_id,
            status=TaskStatus.FAILED,
            error_message="Browser session timed out",
            progress=0,
        )
        print(f"[WORKER] Browser task {task.task_id} timed out")
    except Exception as e:
        import traceback
        traceback.print_exc()
        update_task(
            task.task_id,
            status=TaskStatus.FAILED,
            error_message=str(e),
            progress=0,
        )
        print(f"[WORKER] Browser task {task.task_id} error: {e}")


def process_chat_task(task: Task):
    """Process a chat request asynchronously"""
    global CURRENT_OPERATOR

    # --- Nested Helper Functions for robust JSON parsing ---
    def _extract_first_json_object(s: str) -> Optional[str]:
        """Extract the first complete JSON object from a string."""
        if not isinstance(s, str): return None
        i = 0; n = len(s); depth = 0; start = -1
        in_str = False; esc = False
        while i < n:
            ch = s[i]
            if in_str:
                if esc: esc = False
                elif ch == '\\': esc = True
                elif ch == '"': in_str = False
            else:
                if ch == '"': in_str = True
                elif ch == '{':
                    if depth == 0: start = i
                    depth += 1
                elif ch == '}':
                    if depth > 0:
                        depth -= 1
                        if depth == 0 and start != -1:
                            return s[start:i+1]
            i += 1
        return None

    def _extract_ui_reply_from_truncated(s: str) -> Optional[str]:
        """Extract ui_reply from potentially truncated JSON response.

        This handles the case where max_tokens cuts off the response mid-JSON.
        We try to find and extract the ui_reply value even if the JSON is incomplete.
        """
        if not isinstance(s, str): return None

        # Strip markdown fences if present
        s = s.strip()
        if s.startswith("```"):
            # Remove opening fence (```json or ```)
            first_newline = s.find('\n')
            if first_newline != -1:
                s = s[first_newline + 1:]
        if s.endswith("```"):
            s = s[:-3]
        s = s.strip()

        # Look for "ui_reply": pattern
        patterns = ['"ui_reply":', "'ui_reply':"]
        for pattern in patterns:
            idx = s.find(pattern)
            if idx == -1:
                continue

            # Find the start of the value (skip whitespace after colon)
            val_start = idx + len(pattern)
            while val_start < len(s) and s[val_start] in ' \t\n\r':
                val_start += 1

            if val_start >= len(s):
                continue

            # Check if it starts with a quote
            if s[val_start] != '"':
                continue

            # Parse the JSON string value, handling escapes
            val_start += 1  # skip opening quote
            result = []
            i = val_start
            while i < len(s):
                ch = s[i]
                if ch == '\\' and i + 1 < len(s):
                    # Handle escape sequence
                    next_ch = s[i + 1]
                    if next_ch == 'n':
                        result.append('\n')
                    elif next_ch == 't':
                        result.append('\t')
                    elif next_ch == 'r':
                        result.append('\r')
                    elif next_ch == '"':
                        result.append('"')
                    elif next_ch == '\\':
                        result.append('\\')
                    elif next_ch == '/':
                        result.append('/')
                    elif next_ch == 'b':
                        result.append('\b')
                    elif next_ch == 'f':
                        result.append('\f')
                    elif next_ch == 'u' and i + 5 < len(s):
                        # Unicode escape \uXXXX
                        try:
                            code_point = int(s[i+2:i+6], 16)
                            result.append(chr(code_point))
                            i += 4  # extra skip for unicode
                        except ValueError:
                            result.append(next_ch)
                    else:
                        result.append(next_ch)
                    i += 2
                elif ch == '"':
                    # End of string found - this is a complete extraction
                    return ''.join(result)
                else:
                    result.append(ch)
                    i += 1

            # If we get here, the string was truncated (no closing quote found)
            # Return what we have - it's better than nothing
            if result:
                extracted = ''.join(result)
                # Add a note that it was truncated
                if len(extracted) > 100:  # Only add note for substantial content
                    return extracted + "\n\n[Response truncated due to length limit]"
                return extracted

        return None

    try:
        update_task(task.task_id, progress=5)

        # Get chat input from task.result_data
        inp_dict = task.result_data or {}
        inp = ChatIn(**inp_dict)

        if not inp.messages:
            raise Exception("The 'messages' field is required and cannot be empty.")

        active_operator = (inp.operator or USERS_DEFAULT).strip()
        CURRENT_OPERATOR = active_operator
        s = get_state(active_operator)

        update_task(task.task_id, progress=10)

        user_text = ""
        for m in reversed(inp.messages):
            if m.get("role") == "user":
                content = m.get("content", "")
                if isinstance(content, list):
                    user_text = next((p.get("text","") for p in content if p.get("type")=="text"), "")
                else:
                    user_text = str(content)
                break

        RF  = CFG.getint("context", "recent_fossils_per_user", fallback=8)
        KF  = CFG.getint("context", "keyword_fossils_per_user", fallback=6)
        SF  = CFG.getint("context", "semantic_fossils_per_user", fallback=15)
        ST  = CFG.getfloat("context", "semantic_threshold", fallback=0.7)
        CP  = CFG.getint("context", "checkpoint_snapshots", fallback=1)
        CAP = CFG.getint("context", "max_fossil_chars", fallback=4000)

        print(f"[CONTEXT] Config - Recent: {RF}, Keyword: {KF}, Semantic: {SF} (threshold={ST}), Checkpoints: {CP}, Cap: {CAP}")

        actual_file_size = VOL_PATH.stat().st_size if VOL_PATH.exists() else 0

        vol_txt = read_text_safe(VOL_PATH)

        vol_txt_len = len(vol_txt.encode('utf-8'))
        if vol_txt_len != actual_file_size:
            print(f"[WARNING] File size mismatch: read {vol_txt_len} bytes but file is {actual_file_size} bytes")

        update_task(task.task_id, progress=20)

        recent_snaps  = get_recent_fossils_for_operator(vol_txt, active_operator, RF, CAP)
        # Separate keyword and semantic searches for better control
        keyword_snaps_before = keyword_retrieve_for_operator(vol_txt, user_text, KF, active_operator) if user_text else []
        semantic_snaps_before = semantic_retrieve(user_text, operator=active_operator, k=SF, threshold=ST) if user_text else []

        checkpoint_snaps = get_recent_checkpoints_for_operator(vol_txt, active_operator, count=CP)
        if checkpoint_snaps:
            checkpoint_ids = extract_snap_ids(checkpoint_snaps)
            print(f"[CHECKPOINT] Retrieved {len(checkpoint_snaps)} checkpoint(s) for {active_operator}: {checkpoint_ids}")
        else:
            print(f"[CHECKPOINT] No checkpoints found for {active_operator}")

        extracted_terms = _extract_terms(user_text)
        extracted_bigrams = _generate_ngrams(user_text, 2)
        extracted_trigrams = _generate_ngrams(user_text, 3)
        print(f"[KEYWORD] Extracted terms: {extracted_terms[:10]}")
        print(f"[KEYWORD] Extracted bigrams: {extracted_bigrams[:5]}")
        print(f"[KEYWORD] Extracted trigrams: {extracted_trigrams[:3]}")

        keyword_ids_before = extract_snap_ids(keyword_snaps_before)
        semantic_ids_before = extract_snap_ids(semantic_snaps_before)
        print(f"[KEYWORD] Found {len(keyword_snaps_before)} keyword snapshots: {keyword_ids_before}")
        print(f"[SEMANTIC] Found {len(semantic_snaps_before)} semantic snapshots (threshold={ST}): {semantic_ids_before}")

        # Deduplicate keyword snaps against recent
        recent_ids = set(extract_snap_ids(recent_snaps))
        deduplicated = []
        duplicates_removed = []
        for snap in keyword_snaps_before:
            snap_ids = extract_snap_ids([snap])
            if snap_ids:
                if snap_ids[0] not in recent_ids:
                    deduplicated.append(snap)
                else:
                    duplicates_removed.append(snap_ids[0])
        keyword_snaps = deduplicated

        if duplicates_removed:
            print(f"[KEYWORD] Removed {len(duplicates_removed)} duplicates already in recent: {duplicates_removed}")

        # Deduplicate semantic snaps against recent AND keyword
        keyword_ids_set = set(extract_snap_ids(keyword_snaps))
        seen_ids = recent_ids | keyword_ids_set
        semantic_deduplicated = []
        semantic_duplicates_removed = []
        for snap in semantic_snaps_before:
            snap_ids = extract_snap_ids([snap])
            if snap_ids:
                if snap_ids[0] not in seen_ids:
                    semantic_deduplicated.append(snap)
                else:
                    semantic_duplicates_removed.append(snap_ids[0])
        semantic_snaps = semantic_deduplicated

        if semantic_duplicates_removed:
            print(f"[SEMANTIC] Removed {len(semantic_duplicates_removed)} duplicates already in recent/keyword: {semantic_duplicates_removed}")

        keyword_ids = extract_snap_ids(keyword_snaps)
        semantic_ids = extract_snap_ids(semantic_snaps)
        print(f"[CONTEXT] Operator: {active_operator}")
        print(f"[CONTEXT] Recent snapshots ({len(recent_snaps)}): {list(recent_ids)}")
        print(f"[CONTEXT] Keyword snapshots ({len(keyword_snaps)}): {keyword_ids}")
        print(f"[CONTEXT] Semantic snapshots ({len(semantic_snaps)}): {semantic_ids}")
        print(f"[CONTEXT] Query: {user_text[:100]}...")

        update_task(task.task_id, progress=30)

        context_parts = []

        # Get recent media artifacts (images, videos, music) - inject first so model sees them
        media_artifacts = get_recent_media_artifacts(active_operator, limit=10)
        if media_artifacts:
            media_lines = ["=== RECENT MEDIA (Available for Reference) ===",
                           "These are recently generated media files you can reference by URL:"]
            for artifact in media_artifacts:
                media_type = artifact.get("type", "media")
                url = artifact.get("url", "")
                prompt = artifact.get("prompt", "")[:80]
                created = artifact.get("created_at", "")[:19]  # Trim to datetime
                media_lines.append(f"- [{media_type.upper()}] {url}")
                media_lines.append(f"  Prompt: \"{prompt}...\"")
                media_lines.append(f"  Created: {created}")
            media_lines.append("")
            media_lines.append("To use an image for video generation, pass its URL to generate_video with image_url parameter.")
            context_parts.append("\n".join(media_lines))
            print(f"[CONTEXT] Media artifacts ({len(media_artifacts)}): {[a.get('url') for a in media_artifacts[:3]]}")

        if checkpoint_snaps:
            if len(checkpoint_snaps) == 1:
                context_parts.append("=== CHECKPOINT SUMMARY (Compressed Memory) ===\n" + checkpoint_snaps[0])
            else:
                checkpoint_blocks = []
                for i, checkpoint in enumerate(checkpoint_snaps, 1):
                    checkpoint_blocks.append(f"=== CHECKPOINT #{i} (Older) ===" if i == 1 else f"=== CHECKPOINT #{i} ===" if i < len(checkpoint_snaps) else f"=== CHECKPOINT #{i} (Most Recent) ===")
                    checkpoint_blocks.append(checkpoint)
                context_parts.append("\n\n".join(checkpoint_blocks))
        if recent_snaps: context_parts.append("Recent snapshots:\n" + "\n\n".join(recent_snaps))
        if keyword_snaps: context_parts.append("Keyword-matched snapshots:\n" + "\n\n".join(keyword_snaps))
        if semantic_snaps: context_parts.append("Semantically relevant snapshots:\n" + "\n\n".join(semantic_snaps))
        hybrid_context_block = "\n\n".join(context_parts)

        # SMS mode: inject SMS-specific system prompt
        sms_mode = inp_dict.get("sms_mode", False)
        sms_sender = inp_dict.get("sms_sender", "")
        sms_contact_name = inp_dict.get("sms_contact_name", "unknown")
        sms_prompt_prefix = ""

        if sms_mode:
            sms_prompt_prefix = (
                f"IMPORTANT: You are responding to an SMS text message from {sms_contact_name} ({sms_sender}).\n"
                "SMS RULES:\n"
                "- Keep responses under 160 characters when possible (1 SMS segment)\n"
                "- Maximum 1500 characters total (will be split into multiple messages automatically)\n"
                "- Plain text ONLY — NO markdown, NO formatting, NO bullet points, NO headers\n"
                "- Be concise and conversational, like a real text message\n"
                "- Do NOT use asterisks, backticks, or any special formatting\n"
                "- You can send longer responses if needed — the system splits them into multiple texts\n"
                "- To send SMS to someone else, use the send_sms tool\n"
                "- Respond naturally as a helpful AI assistant via text message\n\n"
            )
            print(f"[SMS-MODE] Processing SMS from {sms_contact_name} ({sms_sender}) for operator {active_operator}")

        # Build system prompt — dynamic (ToolVault) or static (legacy)
        if TOOLVAULT_ENABLED:
            _user_msg = ""
            for _m in reversed(inp.messages):
                if _m.get("role") == "user":
                    _c = _m.get("content", "")
                    _user_msg = _c[:500] if isinstance(_c, str) else ""
                    break
            if _user_msg:
                from Orchestrator.toolvault.injector import inject_for_prompt
                _, tool_instructions = inject_for_prompt(_user_msg, inp.provider or DEFAULT_PROVIDER)
                dynamic_core = build_core_system_prompt(tool_instructions) + GM_FORMAT_RULES
                dynamic_spec = build_output_spec(tool_instructions)
            else:
                dynamic_core = GM_EXCERPT
                dynamic_spec = OUTPUT_SPEC
        else:
            dynamic_core = GM_EXCERPT
            dynamic_spec = OUTPUT_SPEC

        sys_msg = {"role": "system", "content": sms_prompt_prefix + dynamic_core}
        msg_list = [sys_msg]
        if hybrid_context_block: msg_list.append({"role":"system","content": hybrid_context_block})
        msg_list.append({"role":"system","content": dynamic_spec})
        msg_list.extend(inp.messages)

        has_video = False
        has_audio = False
        has_pdf = False

        for msg in inp.messages:
            content = msg.get("content")
            if isinstance(content, list):
                for part in content:
                    part_type = part.get("type", "")
                    if part_type == "video_url":
                        has_video = True
                    elif part_type == "audio_url":
                        has_audio = True
                    elif part_type == "document_url":
                        url = part.get("document_url", {}).get("url", "")
                        if url.lower().endswith(".pdf"):
                            has_pdf = True

        provider = (inp.provider or DEFAULT_PROVIDER).lower()
        # Normalize provider aliases
        if provider == "gemini":
            provider = "google"
        original_provider = provider
        provider_switched = False

        if has_video or has_audio:
            if provider != "google":
                provider = "google"
                provider_switched = True
                print(f"[AUTO-ROUTE] Switched from {original_provider} to google (video/audio detected)")
        elif has_pdf and provider == "openai":
            provider = "google"
            provider_switched = True
            print(f"[AUTO-ROUTE] Switched from openai to google (PDF document detected)")

        # Computer Use is streaming-only; fall back to Anthropic for non-streaming path
        if provider == "computer-use":
            provider = "anthropic"
            print("[AUTO-ROUTE] Switched from computer-use to anthropic (non-streaming fallback)")

        if provider == "anthropic": selected_model = inp.model or ANTHROPIC_MODEL_DEFAULT
        elif provider == "google": selected_model = inp.model or GEMINI_MODEL_DEFAULT
        elif provider == "openai": selected_model = inp.model or OPENAI_MODEL_DEFAULT
        elif provider == "xai": selected_model = inp.model or XAI_MODEL_DEFAULT
        else: raise Exception(f"unknown provider: {provider}")

        with state_lock:
            s.last_context_meta.update({
                "recent_ids": list(recent_ids),
                "relevant_ids": extract_snap_ids(keyword_snaps), "gm_excerpt": True,
                "provider": provider, "model": selected_model, "operator": active_operator,
                "usage_last": {"prompt_tokens": 0, "completion_tokens": 0, "total_tokens": 0},
            })

        update_task(task.task_id, progress=40)

        # Call provider API (lazy imports to avoid circular dependency)
        from Orchestrator.routes.chat_routes import call_anthropic, call_gemini, call_openai, call_xai
        media_parts = []
        if provider == "anthropic":
            raw, usage = call_anthropic(msg_list, selected_model, operator=active_operator)
        elif provider == "google":
            raw, usage, media_parts = call_gemini(msg_list, selected_model, operator=active_operator)
        elif provider == "xai":
            raw, usage = call_xai(msg_list, selected_model, operator=active_operator)
        else:
            raw, usage = call_openai(msg_list, selected_model, operator=active_operator)

        update_task(task.task_id, progress=70)

        # Process inline media from Gemini 3
        media_urls = []
        if media_parts:
            for i, media in enumerate(media_parts):
                try:
                    mime_type = media.get("mime_type", "")
                    data_b64 = media.get("data", "")

                    if not data_b64:
                        continue

                    media_bytes = base64.b64decode(data_b64)

                    ext = ".bin"
                    if "image/png" in mime_type: ext = ".png"
                    elif "image/jpeg" in mime_type or "image/jpg" in mime_type: ext = ".jpg"
                    elif "image/webp" in mime_type: ext = ".webp"
                    elif "image/gif" in mime_type: ext = ".gif"
                    elif "audio/mpeg" in mime_type or "audio/mp3" in mime_type: ext = ".mp3"
                    elif "audio/wav" in mime_type: ext = ".wav"
                    elif "audio/ogg" in mime_type: ext = ".ogg"
                    elif "video/mp4" in mime_type: ext = ".mp4"
                    elif "video/webm" in mime_type: ext = ".webm"

                    timestamp = int(time.time() * 1000)
                    filename = f"gemini3_inline_{timestamp}_{i}{ext}"
                    save_path = UPLOADS_DIR / filename

                    save_path.write_bytes(media_bytes)

                    media_url = f"/ui/uploads/{filename}"
                    media_urls.append({
                        "url": media_url,
                        "mime_type": mime_type,
                        "type": "image" if "image" in mime_type else ("audio" if "audio" in mime_type else ("video" if "video" in mime_type else "file"))
                    })

                    print(f"[GEMINI3] Saved inline media: {filename} ({len(media_bytes)} bytes, {mime_type})")

                except Exception as e:
                    print(f"[GEMINI3] Error saving inline media: {e}")

        ui_reply, snap_persp = raw, ""
        try:
            json_str = _extract_first_json_object(raw)
            if not json_str: raise json.JSONDecodeError("No JSON object found", raw, 0)
            data = json.loads(json_str)
            ui_reply = data.get("ui_reply", "").strip() or raw
            snap_persp = data.get("snapshot_perspective", "").strip()
        except (json.JSONDecodeError, AttributeError) as parse_err:
            # Standard JSON parsing failed - try truncation-aware extraction
            print(f"[PARSE] Standard JSON parsing failed: {str(parse_err)[:100]}")
            truncated_reply = _extract_ui_reply_from_truncated(raw)
            if truncated_reply:
                print(f"[PARSE] Recovered ui_reply from truncated response ({len(truncated_reply)} chars)")
                ui_reply = truncated_reply
                snap_persp = "(Response was truncated - snapshot_perspective unavailable)"
            else:
                print(f"[PARSE] Could not recover ui_reply, using raw text")
                ui_reply = _extract_clean_text(raw)
                snap_persp = "(Could not parse snapshot_perspective)"

        # SMS mode: cap response length and strip formatting
        if sms_mode:
            # Strip HTML tags
            ui_reply = re.sub(r'<[^>]+>', '', ui_reply)
            # Strip markdown
            ui_reply = re.sub(r'\*\*(.+?)\*\*', r'\1', ui_reply)
            ui_reply = re.sub(r'\*(.+?)\*', r'\1', ui_reply)
            ui_reply = re.sub(r'`(.+?)`', r'\1', ui_reply)
            ui_reply = re.sub(r'^#+\s*', '', ui_reply, flags=re.MULTILINE)
            ui_reply = re.sub(r'\n{3,}', '\n\n', ui_reply)
            # Cap at 1500 chars
            if len(ui_reply) > 1500:
                ui_reply = ui_reply[:1497] + "..."
            ui_reply = ui_reply.strip()
            print(f"[SMS-MODE] Response: {len(ui_reply)} chars")

        # Multi-Provider Native Output Rendering - supports MULTIPLE generations of each type
        if "generate_image:" in ui_reply or "generate_video:" in ui_reply or "generate_music:" in ui_reply:
            print(f"[{provider.upper()}] Detected multimodal generation command(s)")

            # Process ALL image generation commands (not just the first one)
            image_pattern = r'generate_image:\s*(.+?)(?=\n\n|generate_video:|generate_music:|generate_image:|$)'
            for image_match in re.finditer(image_pattern, ui_reply, re.DOTALL):
                image_prompt = image_match.group(1).strip()
                if not image_prompt:
                    continue
                print(f"[MULTIMODAL] Auto-executing image generation: {image_prompt[:100]}...")

                img_task = create_task(
                    TaskType.IMAGE_GENERATION,
                    operator=active_operator,
                    prompt=image_prompt
                )

                # Use loading placeholder instead of blocking (to avoid deadlock with single worker thread)
                loading_msg = f'<div class="image-loading-placeholder" data-task-id="{img_task.task_id}" style="padding: 12px; background: #000000; border-radius: 8px; margin: 8px 0;">🖼️ Image generation in progress<span class="thinking-dots" style="display:inline-flex; gap:4px; margin-left:8px;"><span></span><span></span><span></span></span></div>'
                ui_reply = ui_reply.replace(image_match.group(0), loading_msg, 1)
                print(f"[MULTIMODAL] Image generation queued: {img_task.task_id}")

            # Process ALL video generation commands
            video_pattern = r'generate_video:\s*(.+?)(?=\n\n|generate_image:|generate_music:|generate_video:|$)'
            for video_match in re.finditer(video_pattern, ui_reply, re.DOTALL):
                video_prompt = video_match.group(1).strip()
                if not video_prompt:
                    continue
                print(f"[MULTIMODAL] Auto-executing video generation: {video_prompt[:100]}...")

                vid_task = create_task(
                    TaskType.VIDEO_GENERATION,
                    operator=active_operator,
                    prompt=video_prompt
                )

                loading_msg = f'<div class="video-loading-placeholder" data-task-id="{vid_task.task_id}" style="padding: 12px; background: #000000; border-radius: 8px; margin: 8px 0;">🎬 Video generation in progress<span class="thinking-dots" style="display:inline-flex; gap:4px; margin-left:8px;"><span></span><span></span><span></span></span></div>'
                ui_reply = ui_reply.replace(video_match.group(0), loading_msg, 1)
                print(f"[MULTIMODAL] Video generation queued: {vid_task.task_id}")

            # Process ALL music generation commands
            music_pattern = r'generate_music:\s*(.+?)(?=\n\n|generate_image:|generate_video:|generate_music:|$)'
            for music_match in re.finditer(music_pattern, ui_reply, re.DOTALL):
                music_prompt = music_match.group(1).strip()
                if not music_prompt:
                    continue
                print(f"[MULTIMODAL] Auto-executing music generation: {music_prompt[:100]}...")

                music_task = create_task(
                    TaskType.LYRIA_MUSIC,
                    operator=active_operator,
                    prompt=music_prompt,
                    result_data={"prompt": music_prompt, "operator": active_operator}
                )

                loading_msg = f'<div class="music-loading-placeholder" data-task-id="{music_task.task_id}" style="padding: 12px; background: #000000; border-radius: 8px; margin: 8px 0;">🎵 Music generation in progress<span class="thinking-dots" style="display:inline-flex; gap:4px; margin-left:8px;"><span></span><span></span><span></span></span></div>'
                ui_reply = ui_reply.replace(music_match.group(0), loading_msg, 1)
                print(f"[MULTIMODAL] Music generation queued: {music_task.task_id}")

        # Process artifact generation commands
        if '[ARTIFACT:' in ui_reply:
            print(f"[ARTIFACT] Detected artifact generation command")
            ui_reply = parse_and_process_artifacts(ui_reply, active_operator)

        update_task(task.task_id, progress=80)

        reply_alias = ui_reply
        plan_from_ui = extract_plan(ui_reply)
        plan_from_snap = extract_plan(snap_persp)
        if not plan_from_ui and plan_from_snap:
            ui_reply = (ui_reply + "\n\n" + plan_from_snap).strip()
            reply_alias = ui_reply

        total_tok = usage.get("total_tokens", usage.get("prompt_tokens", 0) + usage.get("completion_tokens", 0))
        with state_lock:
            s.last_context_meta["usage_last"] = {"prompt_tokens": usage.get("prompt_tokens", 0),
                                               "completion_tokens": usage.get("completion_tokens", 0),
                                               "total_tokens": total_tok}
        utc_now = now_utc_iso()

        user_message_content = next((m.get("content") for m in inp.messages if m.get("role") == "user"), None)
        if user_message_content:
            log_text = user_text if user_text else "[media content]"
            s.add_conversation_turn({"role": "user", "utc": utc_now, "text": log_text})

        s.add_conversation_turn({"role": "assistant", "utc": utc_now, "text": ui_reply, "snap_text": snap_persp})
        s.conv_turns_since  += 1
        s.conv_tokens_since += total_tok
        s.context_used      += total_tok

        s.total_turns += 1
        s.total_tokens += total_tok

        update_task(task.task_id, progress=90)

        if AUTO_ENABLE:
            now_ms = int(time.time() * 1000)
            d = drift_state_for(s)
            should, reason = False, None
            if d == "red" and ON_RED == "auto": should, reason = True, "DRIFT_RED"
            elif d == "yellow" and ON_YELLOW == "auto": should, reason = True, "DRIFT_YELLOW"
            elif s.conv_tokens_since >= TOKENS_THRESHOLD: should, reason = True, "TOKENS"
            elif s.conv_turns_since  >= TURNS_THRESHOLD:  should, reason = True, "TURNS"
            if should and (now_ms - s.last_mint_ms >= DEBOUNCE_MS):
                _ = perform_mint(active_operator, reason or "AUTO")
                s.last_mint_ms = int(time.time() * 1000)

        checkpoint_triggered = False
        if should_create_checkpoint(active_operator):
            print(f"[CHECKPOINT] Creating checkpoint task for {active_operator} at turn {s.total_turns}")
            checkpoint_triggered = True
            # Create checkpoint task (runs in background)
            checkpoint_task = create_task(
                TaskType.CHECKPOINT,
                operator=active_operator,
                result_data={"manual": False}
            )
            print(f"[CHECKPOINT] Checkpoint task created: {checkpoint_task.task_id}")

        save_operator_state()

        result_data = {
            "ui_reply": ui_reply, "reply": reply_alias, "text": reply_alias,
            "snapshot_perspective": snap_persp, "usage": usage,
            "conv_turns_since": s.conv_turns_since, "conv_tokens_since": s.conv_tokens_since,
            "ctx_tokens_since": s.ctx_tokens_since, "drift": drift_state_for(s),
            "retrieved": len(keyword_snaps) + len(recent_snaps),
            "inline_media": media_urls,
            "checkpoint_triggered": checkpoint_triggered,
        }

        update_task(task.task_id,
                   status=TaskStatus.COMPLETED,
                   result_data=result_data,
                   progress=100)

        print(f"[WORKER] Chat task {task.task_id} completed for operator {active_operator}")

    except Exception as e:
        import traceback
        error_msg = str(e)
        trace = traceback.format_exc()
        print(f"[WORKER] Chat task {task.task_id} failed: {error_msg}\n{trace}")

        update_task(task.task_id,
                   status=TaskStatus.FAILED,
                   error_message=error_msg,
                   result_data={"error": error_msg, "trace": trace},
                   progress=0)

# -----------------------------------------------------------------------------
# Helpers
# -----------------------------------------------------------------------------
SNAP_ID_RX = re.compile(r"(SNAP-\d{8}-\d+)")
OP_RX      = re.compile(r"^OPERATOR:\s*(.+)$", re.M)

# Core system prompt — identity, behavior, knowledge hierarchy (NO tool descriptions)
# Tool descriptions are injected dynamically from the ToolVault when TOOLVAULT_ENABLED.
CORE_SYSTEM_PROMPT = (
    BEHAVIORAL_CORE_CHAT + "\n\n"

    "IDENTITY:\n"
    "You are the AI Black Box Flight Recorder, connected to an immutable "
    "conversation ledger and a multimodal toolchain. The operator's memory, "
    "decisions, and past work live in the snapshot volume — treat it as your "
    "external long-term memory, not as reference material.\n\n"

    "TEMPORAL AWARENESS — FIRST ACTION:\n"
    "Your VERY FIRST action must be to call get_current_time to anchor yourself in the present. "
    "Do this before any other tool calls or responses. Knowing the exact date and time is critical "
    "for interpreting snapshots, scheduling tasks, and understanding temporal context.\n\n"

    "KNOWLEDGE HIERARCHY (in order of priority):\n"
    "1. SNAPSHOTS (Primary Truth — SEARCH FIRST, SEARCH OFTEN): The BlackBox contains 1,600+ snapshots — your complete memory. "
    "This is an unlimited bucket holding every past conversation, development session, bug fix, decision, user preference, and interaction. "
    "Search snapshots INSTINCTIVELY using search_snapshots — before answering questions about past work, before starting tasks, before guessing at context. "
    "If a snapshot references other snapshot IDs in its chain, trace those IDs to gather complete context. "
    "The web has general knowledge — snapshots have THIS user's knowledge. When in doubt, search. For anything about the past, search.\n"
    "2. WEB SEARCH (Live Data): Use the web freely for current information, real-time data, documentation, and facts. "
    "The web provides live, up-to-date information - use it proactively, not as a last resort.\n"
    "3. TRAINING DATA (Fallback): Only rely on training knowledge when snapshots and web don't have the answer.\n\n"

    "MULTIMODAL MEDIA - AUTO-DISPLAY RULE:\n"
    "When referencing ANY media artifact (image, video, audio), ALWAYS display the URL in chat so the user can see it. "
    "Don't wait for the user to ask - show them what you're talking about. Output the URL on its own line:\n"
    "  /ui/uploads/sunset-mountains_abc123.png  (renders as image)\n"
    "  /ui/uploads/racing-car_def456.mp4  (renders as video player)\n"
    "  /ui/uploads/epic-music_ghi789.wav  (renders as audio player)\n"
    "Use list_media or search_media tools to find available media.\n\n"

    "TOOL USAGE:\n"
    "You already have the most relevant tools loaded for this conversation — use them DIRECTLY by calling them. "
    "Do NOT use toolvault to search for tools you already have. Only use toolvault(action='search') if you need a capability "
    "that is NOT in your current tool list. When you receive tool results, acknowledge naturally without wrapping in artifact blocks.\n\n"

    "{TOOL_INSTRUCTIONS}\n\n"

    "ARTIFACT/FILE GENERATION:\n"
    "Create downloadable files with artifact blocks:\n"
    "  Format: [ARTIFACT:filename.ext:type]\\ncontent\\n[/ARTIFACT]\n"
    "  Types: text, pdf, csv, docx (NOT for images/videos/music - those use tools)\n\n"

    "CRITICAL: Do NOT generate snapshot format markers like '=== START SNAPSHOT ===', "
    "'VOLUME TRACKER', 'GAUGES', 'Raw Session Log', etc. Just respond directly."
)

# Legacy static tool descriptions for CORE_SYSTEM_PROMPT (used when TOOLVAULT_ENABLED=false)
CORE_TOOLS_STATIC = (
    "MEDIA GENERATION RULES:\n"
    "- IMAGES: Generate instinctively when helpful to illustrate concepts, visualize ideas, or enhance communication.\n"
    "- MUSIC & VIDEOS: Only generate when the user EXPLICITLY requests them.\n"
    "- Image-to-image: Use reference_images parameter (max 10 images for best quality).\n"
    "- Video extension: Use video_url parameter with 720p resolution.\n"
    "- Image-to-video: Use image_url parameter with a previously generated image.\n\n"
    "SCHEDULED TASKS (CRON JOBS):\n"
    "You can create, edit, and search scheduled tasks for the user. Use these proactively when the user wants:\n"
    "- Recurring reminders or checks\n- One-time future reminders\n- Automated monitoring\n"
    "Tools: create_cron_job, edit_cron_job, search_cron_jobs.\n"
    "Delivery options: snapshot, sms, voice_call, notification.\n\n"
    "COMPUTER USE & DEVICE CONTROL:\n"
    "- use_computer — Launch an AI agent to control the Linux desktop (browser, terminal, apps). Returns task_id.\n"
    "- list_devices — List devices on the Tailscale mesh network.\n"
    "- control_android_device — Control an Android device via Gemini CU. Returns task_id.\n\n"
    "GMAIL EMAIL ACCESS:\n"
    "- gmail_search — Search or list emails. Gmail syntax (from:, subject:, is:unread).\n"
    "- gmail_read — Read full email by message ID.\n"
    "- gmail_send — Compose and send email.\n"
    "- gmail_reply — Reply to email thread.\n"
    "- gmail_labels — List labels or modify messages.\n"
    "Always pass operator name for correct Gmail account.\n"
)


def build_core_system_prompt(tool_instructions: str = "") -> str:
    """Build the core system prompt with dynamic or static tool instructions."""
    if tool_instructions:
        return CORE_SYSTEM_PROMPT.replace("{TOOL_INSTRUCTIONS}", tool_instructions)
    return CORE_SYSTEM_PROMPT.replace("{TOOL_INSTRUCTIONS}", CORE_TOOLS_STATIC)


# Streaming mode system prompt (static fallback — dynamicized at request time)
STREAM_EXCERPT = build_core_system_prompt()

# Non-streaming format rules (appended to CORE_SYSTEM_PROMPT for non-streaming JSON mode)
GM_FORMAT_RULES = (
    "\n\nOUTPUT FORMAT RULES (MANDATORY):\n"
    "You MUST strictly follow the response format specified in OUTPUT_SPEC. Any deviation is a system failure.\n"
    "1. Your entire output MUST be a single, raw JSON object starting with `{` and ending with `}`.\n"
    "2. NO markdown code fences (```), no headers, no commentary, no text outside the JSON object.\n"
    "3. The JSON object MUST contain the exact keys: `ui_reply` and `snapshot_perspective`.\n"
    "4. Values must be plain strings. DO NOT nest JSON-encoded strings inside values (no double-serialization).\n\n"
    "Use the recent/relevant Context Fossils below to inform your reasoning."
)

# Non-streaming mode with JSON format requirements (static fallback)
GM_EXCERPT = build_core_system_prompt() + GM_FORMAT_RULES
