#!/usr/bin/env python3
"""
volume.py - Extracted from Orchestrator/app.py

This module was automatically extracted using byte-offset manifest refactoring.
Original location: Lines 1759-2011

Extraction date: 2025-12-10T21:10:15.848302+00:00
Original SHA-256: 109fee54ec35d06268326ca9994ef9e1d9d40d1076da22fb8f6fee565a37be38
"""

# Standard library imports
from datetime import datetime, timezone
import hashlib
import json
import os
import time
from pathlib import Path
from typing import Dict, Any, Optional, List

# External library imports
import shutil
import traceback

# Local imports
from Orchestrator.config import ARTIFACTS_DIR, ARTIFACT_RETENTION_DAYS

# Additional imports (auto-generated by dependency audit)
from Orchestrator.config import ARC_DIR, ARTIFACT_RETENTION_DAYS, GM_HASH, GM_PATH, MANIFEST, END_RX, START_RX, VOL_PATH, SNAP_RE


def now_utc_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

def sha256_bytes(b: bytes) -> str:
    return hashlib.sha256(b).hexdigest()

def atomic_write(path: Path, data: bytes):
    tmp = path.with_suffix(path.suffix + ".part")
    tmp.write_bytes(data)
    os.replace(tmp, path)

def verify_gm_or_halt():
    if not GM_PATH.exists() or not GM_HASH.exists():
        raise HTTPException(500, "GM-NOT-FOUND")
    gm = GM_PATH.read_bytes()
    expect = GM_HASH.read_text().strip()
    digest = sha256_bytes(gm)
    if digest != expect:
        raise HTTPException(500, f"GM-HASH-MISMATCH: {digest} != {expect}")
    return digest, len(gm)

def read_text_safe(p: Path) -> str:
    """Read file with fresh handle to avoid caching issues.

    On Windows, file system caching can cause stale reads when files are
    rapidly appended. Read in binary mode first, then decode to ensure
    we get ALL bytes from disk, not a buffered/cached subset.
    """
    if not p.exists():
        return ""

    # Read in binary mode to ensure complete file read, then decode
    # Text mode reads can be incomplete due to buffering on Windows
    try:
        with open(p, 'rb') as f:
            raw_bytes = f.read()

        # Decode with error replacement
        text = raw_bytes.decode('utf-8', errors='replace')

        # Debug: verify we read the complete file
        expected_size = p.stat().st_size
        actual_size = len(raw_bytes)
        if actual_size != expected_size:
            print(f"[ERROR] Incomplete read! Expected {expected_size} bytes, got {actual_size} bytes")

        return text
    except Exception as e:
        print(f"[ERROR] Failed to read {p}: {e}")
        import traceback
        traceback.print_exc()
        return ""

def read_volume_bytes(p: Path) -> bytes:
    """Read volume file as bytes for byte-offset indexing.

    Returns raw bytes to allow proper byte-offset slicing.
    Byte offsets in the index must be used with bytes, not strings.
    """
    if not p.exists():
        return b""

    try:
        with open(p, 'rb') as f:
            raw_bytes = f.read()

        # Debug: verify we read the complete file
        expected_size = p.stat().st_size
        actual_size = len(raw_bytes)
        if actual_size != expected_size:
            print(f"[ERROR] Incomplete read! Expected {expected_size} bytes, got {actual_size} bytes")

        return raw_bytes
    except Exception as e:
        print(f"[ERROR] Failed to read {p}: {e}")
        import traceback
        traceback.print_exc()
        return b""

def parse_tail(vol_txt: str) -> Dict[str, Any]:
    ends = list(END_RX.finditer(vol_txt))
    if not ends:
        return {"unanimous": True, "tail_id": "SNAP-000", "utc": "N/A"}
    end_m = ends[-1]
    snap_id = end_m.group("snap")
    utc_part = end_m.group("utc")
    end_pos = end_m.start()
    starts_before = list(START_RX.finditer(vol_txt, 0, end_pos))
    start_m = next((m for m in reversed(starts_before) if m.group("snap") == snap_id), None)
    if not start_m:
        raise HTTPException(500, "PARTIAL-SNAPSHOT")
    return {"unanimous": True, "tail_id": snap_id, "utc": utc_part}

def next_snap_id_from_tail(tail_snap: str) -> str:
    today = datetime.now(timezone.utc).strftime("%Y%m%d")
    m = SNAP_RE.fullmatch(tail_snap.strip())
    n = int(m.group(2)) if m else 0
    n += 1
    width = max(3, len(str(n)))
    return f"SNAP-{today}-{str(n).zfill(width)}"

def append_snapshot_text(text: str):
    VOL_PATH.parent.mkdir(parents=True, exist_ok=True)
    try:
        with open(VOL_PATH, "rb+") as f:
            f.seek(0, os.SEEK_END)
            size = f.tell()
            if size > 0:
                f.seek(-1, os.SEEK_END)
                last = f.read(1)
                if last != b"\n":
                    f.seek(0, os.SEEK_END)
                    f.write(b"\n")
            f.write(text.encode("utf-8"))
            f.flush()
            os.fsync(f.fileno())
    except FileNotFoundError:
        with open(VOL_PATH, "wb") as f:
            f.write(text.encode("utf-8"))
            f.flush()
            os.fsync(f.fileno())

def archive_volume():
    utc = now_utc_iso().replace(":", "-")
    arc = ARC_DIR / f"Volume_{utc}.txt"
    atomic_write(arc, VOL_PATH.read_bytes())
    man = json.loads(MANIFEST.read_text())
    digest = sha256_bytes(VOL_PATH.read_bytes())
    man["latest_path"] = str(VOL_PATH.as_posix())
    man["latest_sha256"] = digest
    man["latest_utc"] = utc.replace("-", ":", 2)
    man["archive"].append({"utc": utc.replace("-", ":", 2),
                           "path": str(arc.as_posix()),
                           "sha256": digest})
    atomic_write(MANIFEST, json.dumps(man, indent=2).encode("utf-8"))
    return arc, digest, utc

def cleanup_old_archives(days_to_keep: int = 30, max_size_gb: float = 5.0, max_files: int = 200) -> Dict[str, Any]:
    """Clean up old archive files to prevent disk space issues.

    Args:
        days_to_keep: Keep archives newer than this many days
        max_size_gb: Maximum total size of archive directory in GB
        max_files: Maximum number of archive files to keep

    Returns:
        Dict with cleanup statistics
    """
    import shutil
    from datetime import datetime, timedelta, timezone

    cleanup_stats = {
        "deleted_files": 0,
        "deleted_size_mb": 0,
        "remaining_files": 0,
        "remaining_size_mb": 0,
        "reason": []
    }

    if not ARC_DIR.exists():
        return cleanup_stats

    # Get all archive files sorted by modification time (oldest first)
    archive_files = []
    total_size = 0

    for file_path in ARC_DIR.glob("Volume_*.txt"):
        stat = file_path.stat()
        archive_files.append({
            "path": file_path,
            "mtime": stat.st_mtime,
            "size": stat.st_size
        })
        total_size += stat.st_size

    if not archive_files:
        return cleanup_stats

    # Sort by modification time (oldest first)
    archive_files.sort(key=lambda x: x["mtime"])

    # Determine what to delete
    files_to_delete = []
    cutoff_time = time.time() - (days_to_keep * 86400)  # Convert days to seconds

    # Check age-based cleanup
    for file_info in archive_files:
        if file_info["mtime"] < cutoff_time:
            files_to_delete.append(file_info)
            cleanup_stats["reason"].append("age")

    # Check size-based cleanup (delete oldest until under size limit)
    total_size_gb = total_size / (1024 ** 3)
    if total_size_gb > max_size_gb:
        cleanup_stats["reason"].append("size")
        for file_info in archive_files:
            if total_size_gb <= max_size_gb:
                break
            if file_info not in files_to_delete:
                files_to_delete.append(file_info)
            total_size_gb -= (file_info["size"] / (1024 ** 3))

    # Check count-based cleanup (keep only the most recent max_files)
    if len(archive_files) > max_files:
        cleanup_stats["reason"].append("count")
        files_to_keep = archive_files[-max_files:]  # Keep the most recent
        for file_info in archive_files:
            if file_info not in files_to_keep and file_info not in files_to_delete:
                files_to_delete.append(file_info)

    # Perform deletion
    for file_info in files_to_delete:
        try:
            file_info["path"].unlink()
            cleanup_stats["deleted_files"] += 1
            cleanup_stats["deleted_size_mb"] += file_info["size"] / (1024 ** 2)
        except Exception as e:
            print(f"Error deleting archive {file_info['path']}: {e}")

    # Calculate remaining statistics
    remaining_size = 0
    remaining_count = 0
    for file_info in archive_files:
        if file_info not in files_to_delete:
            remaining_count += 1
            remaining_size += file_info["size"]

    cleanup_stats["remaining_files"] = remaining_count
    cleanup_stats["remaining_size_mb"] = remaining_size / (1024 ** 2)

    return cleanup_stats

# -----------------------------------------------------------------------------
# Artifact Generation & Management
# -----------------------------------------------------------------------------

def cleanup_old_artifacts():
    """Remove artifacts older than ARTIFACT_RETENTION_DAYS."""
    if not ARTIFACTS_DIR.exists():
        return
    cutoff = time.time() - (ARTIFACT_RETENTION_DAYS * 86400)
    cleaned = 0
    for artifact in ARTIFACTS_DIR.iterdir():
        if artifact.is_file() and artifact.stat().st_mtime < cutoff:
            try:
                artifact.unlink()
                cleaned += 1
                print(f"[ARTIFACT] Cleaned up expired: {artifact.name}")
            except Exception as e:
                print(f"[ARTIFACT] Cleanup error: {e}")
    if cleaned:
        print(f"[ARTIFACT] Cleaned up {cleaned} expired artifacts")

