#!/usr/bin/env python3
from __future__ import annotations

"""
admin_routes.py - Health, upload, dashboard, admin endpoints
"""

# Standard library imports
import json
import uuid
from pathlib import Path
from typing import Dict, Any, Optional, List

# External library imports
from fastapi import HTTPException, WebSocket, UploadFile, File, Form, Body
from fastapi.responses import StreamingResponse, HTMLResponse, FileResponse, JSONResponse

# Local imports
from Orchestrator.checkpoint import app
from Orchestrator.volume import verify_gm_or_halt

# Additional imports (auto-generated by dependency audit)
from Orchestrator.checkpoint import create_checkpoint_async, perform_mint
from Orchestrator.config import (
    ANTHROPIC_API_KEY, ANTHROPIC_MODEL_DEFAULT,
    ARC_DIR, ARTIFACTS_DIR, AUDIO_ENGINE, CFG,
    CHECKPOINT_AUTO_CREATE_INTERVAL, CHECKPOINT_MIN_SNAPSHOTS, CHECKPOINT_TURNS_TO_COMPRESS,
    CTX_MAX, CURRENT_OPERATOR, END_RX,
    GEMINI_MODEL_DEFAULT, GOOGLE_API_KEY, GOOGLE_APPLICATION_CREDENTIALS, GOOGLE_AUTH_AVAILABLE,
    MANIFEST, OPENAI_API_KEY, OPENAI_MODEL_DEFAULT,
    SNAPSHOT_INDEX, START_RX, STT_MODEL, TTS_MODEL,
    UPLOADS_DIR, USERS_DEFAULT, USERS_LIST, USE_CLOUD_TTS, VOL_PATH,
    XAI_API_KEY, XAI_MODEL_DEFAULT,
)
from Orchestrator.utils.models_cache import get_cached_or_fetch as _models_cache_get
from Orchestrator.fossils import extract_snap_ids, get_recent_fossils_for_operator, hybrid_retrieve, rebuild_snapshot_index
import Orchestrator.models as models_module  # Import module for dynamic access to models_module.worker_running
from Orchestrator.models import task_queue
from Orchestrator.monitoring import cleanup_stuck_tasks, drift_state_global, get_disk_usage
from Orchestrator.state import get_state, state_by_op
from Orchestrator.volume import cleanup_old_archives, parse_tail, read_text_safe, sha256_bytes, verify_gm_or_halt



@app.get("/", response_class=HTMLResponse)
def root():
    p = Path("Portal/index.html")
    return p.read_text(encoding="utf-8") if p.exists() else "<h3>BlackBox Portal running. Open /ui/index.html</h3>"

MAX_UPLOAD_SIZE = 500 * 1024 * 1024  # 500MB max upload
UPLOAD_CHUNK_SIZE = 1024 * 1024       # 1MB chunks for streaming write

@app.post("/upload")
async def upload_file(file: UploadFile = File(...)):
    try:
        ext = Path(file.filename).suffix or ".tmp"
        filename = f"{uuid.uuid4()}{ext}"
        save_path = UPLOADS_DIR / filename

        # Stream file to disk in chunks to avoid loading entire file into memory
        total_written = 0
        with open(save_path, "wb") as f:
            while True:
                chunk = await file.read(UPLOAD_CHUNK_SIZE)
                if not chunk:
                    break
                total_written += len(chunk)
                if total_written > MAX_UPLOAD_SIZE:
                    # Clean up partial file
                    f.close()
                    save_path.unlink(missing_ok=True)
                    raise HTTPException(
                        status_code=413,
                        detail=f"File too large. Maximum upload size is {MAX_UPLOAD_SIZE // (1024*1024)}MB"
                    )
                f.write(chunk)

        size_mb = total_written / (1024 * 1024)
        print(f"File '{file.filename}' uploaded ({size_mb:.1f}MB) to '{save_path}'")
        url = f"/ui/uploads/{filename}"
        return {"url": url}
    except HTTPException:
        raise
    except Exception as e:
        print(f"ERROR: File upload failed: {e}")
        raise HTTPException(status_code=500, detail=f"File upload failed: {e}")


# -----------------------------------------------------------------------------
# Session-based upload for Agent Mode
# Files are stored in session-specific folders that Claude Code can access
# -----------------------------------------------------------------------------
SESSION_UPLOADS_DIR = UPLOADS_DIR / "sessions"

@app.post("/upload/session")
async def upload_session_file(
    file: UploadFile = File(...),
    session_id: str = Form(...)
):
    """Upload file to session-specific folder for Claude Code agent.

    Files are stored at: Portal/uploads/sessions/{session_id}/{original_filename}
    This allows Claude Code to access files directly using its file reading tools.
    """
    try:
        # Create session folder if it doesn't exist
        session_folder = SESSION_UPLOADS_DIR / session_id
        session_folder.mkdir(parents=True, exist_ok=True)

        # Use original filename (or add UUID prefix if collision)
        original_name = Path(file.filename).name
        save_path = session_folder / original_name

        # Handle filename collisions by adding timestamp prefix
        if save_path.exists():
            import time
            timestamp = int(time.time())
            stem = Path(original_name).stem
            ext = Path(original_name).suffix
            save_path = session_folder / f"{stem}_{timestamp}{ext}"

        # Stream file to disk in chunks to avoid loading entire file into memory
        total_written = 0
        with open(save_path, "wb") as f:
            while True:
                chunk = await file.read(UPLOAD_CHUNK_SIZE)
                if not chunk:
                    break
                total_written += len(chunk)
                if total_written > MAX_UPLOAD_SIZE:
                    f.close()
                    save_path.unlink(missing_ok=True)
                    raise HTTPException(
                        status_code=413,
                        detail=f"File too large. Maximum upload size is {MAX_UPLOAD_SIZE // (1024*1024)}MB"
                    )
                f.write(chunk)

        # Get absolute path for Claude Code
        abs_path = str(save_path.resolve())
        # Also provide relative URL for web access
        relative_url = f"/ui/uploads/sessions/{session_id}/{save_path.name}"

        size_mb = total_written / (1024 * 1024)
        print(f"[Session Upload] File '{file.filename}' ({size_mb:.1f}MB) saved to '{abs_path}'")

        return {
            "url": relative_url,
            "path": abs_path,
            "filename": save_path.name,
            "session_id": session_id,
            "session_folder": str(session_folder.resolve())
        }
    except HTTPException:
        raise
    except Exception as e:
        print(f"ERROR: Session file upload failed: {e}")
        raise HTTPException(status_code=500, detail=f"Session file upload failed: {e}")


@app.get("/upload/session/{session_id}")
async def list_session_files(session_id: str):
    """List all files in a session's upload folder."""
    try:
        session_folder = SESSION_UPLOADS_DIR / session_id
        if not session_folder.exists():
            return {"files": [], "session_folder": None}

        files = []
        for f in session_folder.iterdir():
            if f.is_file():
                files.append({
                    "filename": f.name,
                    "path": str(f.resolve()),
                    "url": f"/ui/uploads/sessions/{session_id}/{f.name}",
                    "size": f.stat().st_size,
                    "modified": f.stat().st_mtime
                })

        return {
            "files": files,
            "session_folder": str(session_folder.resolve()),
            "count": len(files)
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.delete("/upload/session/{session_id}")
async def cleanup_session_files(session_id: str):
    """Delete all files in a session's upload folder."""
    try:
        import shutil
        session_folder = SESSION_UPLOADS_DIR / session_id
        if session_folder.exists():
            shutil.rmtree(session_folder)
            print(f"[Session Cleanup] Deleted session folder: {session_folder}")
            return {"deleted": True, "session_id": session_id}
        return {"deleted": False, "message": "Session folder not found"}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


def cleanup_old_session_files(max_age_days: int = 3):
    """Clean up session folders older than max_age_days.

    Called periodically to prevent unbounded file growth.
    """
    import time
    import shutil

    if not SESSION_UPLOADS_DIR.exists():
        return 0

    cutoff_time = time.time() - (max_age_days * 24 * 60 * 60)
    cleaned = 0

    for session_folder in SESSION_UPLOADS_DIR.iterdir():
        if session_folder.is_dir():
            # Check folder modification time
            try:
                mtime = session_folder.stat().st_mtime
                if mtime < cutoff_time:
                    shutil.rmtree(session_folder)
                    print(f"[Session Cleanup] Removed old session folder: {session_folder.name}")
                    cleaned += 1
            except Exception as e:
                print(f"[Session Cleanup] Error cleaning {session_folder}: {e}")

    return cleaned


@app.post("/upload/cleanup")
async def trigger_session_cleanup(max_age_days: int = 3):
    """Manually trigger cleanup of old session files."""
    cleaned = cleanup_old_session_files(max_age_days)
    return {"cleaned_sessions": cleaned, "max_age_days": max_age_days}

@app.get("/health")
def health():
    try:
        gm_digest, gm_bytes = verify_gm_or_halt()
        status = "ok"
        detail = ""
    except HTTPException as e:
        gm_digest, gm_bytes = "", 0
        status = "GM FAIL"
        detail = str(e)
    vol_bytes = VOL_PATH.stat().st_size if VOL_PATH.exists() else 0
    # Count snapshots from index
    try:
        snapshot_count = len(json.loads(SNAPSHOT_INDEX.read_text())) if SNAPSHOT_INDEX.exists() else 0
    except Exception:
        snapshot_count = 0
    try:
        pairing = {
            "default_origin": CFG.get("pairing", "default_origin", fallback=""),
            "default_operator": CFG.get("pairing", "default_operator", fallback=""),
        }
    except Exception:
        pairing = {"default_origin": "", "default_operator": ""}
    # Build per-operator turn data for checkpoint tracking
    operator_turns = {}
    for op, s in state_by_op.items():
        # Calculate turns until next checkpoint using countdown-based logic
        # This matches the logic in should_create_checkpoint()
        turns_since_last_checkpoint = s.total_turns - s.last_checkpoint_turn

        # Calculate how many turns until the next checkpoint
        # The checkpoint triggers when turns_since >= interval, so we need (interval - turns_since)
        turns_until_checkpoint = CHECKPOINT_AUTO_CREATE_INTERVAL - turns_since_last_checkpoint

        # If we're at or past the checkpoint threshold, show 0 (checkpoint needed now)
        if turns_until_checkpoint <= 0:
            turns_until_checkpoint = 0

        operator_turns[op] = {
            "total_turns": s.total_turns,
            "turns_until_checkpoint": turns_until_checkpoint,
            "total_tokens": s.total_tokens
        }

    return {
        "status": status, "detail": detail, "gm_sha256": gm_digest,"worker_running": models_module.worker_running,"queue_size": len(task_queue),
        "gm_bytes": gm_bytes, "volume_bytes": vol_bytes, "snapshot_count": snapshot_count, "drift": drift_state_global(),
        "ctx_used": max((s.context_used for s in state_by_op.values()), default=0),
        "ctx_max": CTX_MAX, "latest_manifest": json.loads(MANIFEST.read_text()),
        "audio_engine": AUDIO_ENGINE, "tts_model": TTS_MODEL, "stt_model": STT_MODEL,
        "users": {"list": USERS_LIST, "default": USERS_DEFAULT}, "pairing": pairing,
        "operator_turns": operator_turns,  # Per-operator turn counts, checkpoint countdown, and cumulative tokens
        "checkpoint_config": {
            "turns_to_compress": CHECKPOINT_TURNS_TO_COMPRESS,
            "auto_create_interval": CHECKPOINT_AUTO_CREATE_INTERVAL,
            "min_snapshots_required": CHECKPOINT_MIN_SNAPSHOTS
        }
    }

@app.get("/operators")
def list_operators():
    """List available operators for mobile/overlay dropdown."""
    return {
        "operators": USERS_LIST,
        "default": USERS_DEFAULT
    }

@app.get("/tts/status")
def tts_status():
    """Check TTS configuration and which API is active."""
    return {
        "cloud_tts_enabled": USE_CLOUD_TTS,
        "google_auth_available": GOOGLE_AUTH_AVAILABLE,
        "active_api": "Cloud TTS (GA)" if (USE_CLOUD_TTS and GOOGLE_AUTH_AVAILABLE) else "AI Studio (Preview)",
        "active_model": "gemini-2.5-pro-tts" if (USE_CLOUD_TTS and GOOGLE_AUTH_AVAILABLE) else "gemini-2.5-pro-preview-tts",
        "credentials_file": GOOGLE_APPLICATION_CREDENTIALS if GOOGLE_APPLICATION_CREDENTIALS else None,
        "credentials_exist": bool(GOOGLE_APPLICATION_CREDENTIALS and os.path.exists(GOOGLE_APPLICATION_CREDENTIALS)),
        "api_key_configured": bool(GOOGLE_API_KEY),
        "setup_instructions": {
            "for_ga_models": "Set GOOGLE_APPLICATION_CREDENTIALS=/path/to/service-account.json in .env",
            "for_preview_models": "Set GOOGLE_API_KEY=your-api-key in .env"
        }
    }


@app.get("/dashboard")
def dashboard():
    """User-friendly system dashboard for monitoring appliance health."""
    usage = get_disk_usage()

    # Check API keys configuration
    api_keys_configured = {
        "openai": bool(OPENAI_API_KEY.strip()),
        "anthropic": bool(ANTHROPIC_API_KEY.strip()),
        "google": bool(GOOGLE_API_KEY.strip())
    }

    # Get last activity timestamps
    last_activities = {}
    for op, s in state_by_op.items():
        if s.last_mint_ms and s.last_mint_ms > 0:
            # Convert milliseconds to ISO timestamp
            from datetime import datetime
            last_activities[op] = datetime.fromtimestamp(s.last_mint_ms / 1000).isoformat()

    # Overall system health
    health_status = "healthy"
    health_issues = []

    if usage["disk"]["percent"] > 90:
        health_status = "critical"
        health_issues.append("Disk space critical")
    elif usage["disk"]["percent"] > 80:
        health_status = "warning"
        health_issues.append("Disk space low")

    if not any(api_keys_configured.values()):
        health_status = "warning"
        health_issues.append("No API keys configured")

    if usage["archives"]["count"] > 300:
        if health_status == "healthy":
            health_status = "info"
        health_issues.append(f"Archive cleanup recommended ({usage['archives']['count']} files)")

    # Get task statistics
    try:
        import sqlite3
        from datetime import datetime, timezone, timedelta
        db_path = Path("Portal/tasks.db")
        task_stats = {
            "active": 0,
            "completed_last_24h": 0,
            "failed": 0,
            "total": 0
        }

        if db_path.exists():
            conn = sqlite3.connect(str(db_path))
            cursor = conn.cursor()

            # Count active tasks
            cursor.execute("SELECT COUNT(*) FROM tasks WHERE status IN ('processing', 'pending')")
            task_stats["active"] = cursor.fetchone()[0]

            # Count completed in last 24h
            cutoff = (datetime.now(timezone.utc) - timedelta(hours=24)).isoformat().replace('+00:00', 'Z')
            cursor.execute("SELECT COUNT(*) FROM tasks WHERE status='completed' AND updated_at > ?", (cutoff,))
            task_stats["completed_last_24h"] = cursor.fetchone()[0]

            # Count failed tasks
            cursor.execute("SELECT COUNT(*) FROM tasks WHERE status='failed'")
            task_stats["failed"] = cursor.fetchone()[0]

            # Total tasks
            cursor.execute("SELECT COUNT(*) FROM tasks")
            task_stats["total"] = cursor.fetchone()[0]

            conn.close()
    except Exception as e:
        task_stats = {"error": str(e)}

    return {
        "health_status": health_status,
        "health_issues": health_issues,
        "disk_usage": usage,
        "api_keys_configured": api_keys_configured,
        "last_activities": last_activities,
        "archive_status": {
            "count": usage["archives"]["count"],
            "size_mb": usage["archives"]["size_mb"],
            "auto_cleanup_enabled": True,
            "cleanup_settings": {
                "days_to_keep": 30,
                "max_size_gb": 5.0,
                "max_files": 200
            }
        },
        "system_uptime": get_system_uptime(),
        "service_status": "running",  # If we're responding, we're running
        "worker_status": "running" if models_module.worker_running else "stopped",
        "queue_size": len(task_queue),
        "task_status": task_stats,
        "task_cleanup": {
            "auto_cleanup_enabled": True,
            "max_stuck_hours": 24,
            "cleanup_runs_with": "watchdog (every 2 minutes)"
        }
    }

@app.post("/cleanup/archives")
def cleanup_archives_manual(
    days_to_keep: int = 30,
    max_size_gb: float = 5.0,
    max_files: int = 200,
    dry_run: bool = False
):
    """Manually trigger archive cleanup with custom parameters."""
    if dry_run:
        # Just check what would be deleted
        stats = cleanup_old_archives(days_to_keep, max_size_gb, max_files)
        # Restore files since this was a dry run (hacky but works)
        return {"dry_run": True, "would_delete": stats}

    stats = cleanup_old_archives(days_to_keep, max_size_gb, max_files)
    return {
        "dry_run": False,
        "cleanup_stats": stats,
        "disk_usage_after": get_disk_usage()
    }

@app.get("/watchdog")
def watchdog():
    """Systemd watchdog endpoint - returns 200 if service is healthy."""
    # Check critical components
    checks = {
        "volume_accessible": VOL_PATH.exists(),
        "manifest_accessible": MANIFEST.exists(),
        "worker_running": models_module.worker_running,
        "database_accessible": Path("Portal/tasks.db").exists()
    }

    # Check disk space
    usage = get_disk_usage()
    checks["disk_space_ok"] = usage["disk"]["percent"] < 95

    # Clean up stuck tasks periodically (runs every watchdog check)
    try:
        task_cleanup = cleanup_stuck_tasks(max_hours=24)
        checks["stuck_tasks_cleaned"] = task_cleanup["marked_failed"]
    except Exception as e:
        checks["stuck_tasks_error"] = str(e)

    # If any critical check fails, return error
    if not all([checks["volume_accessible"], checks["manifest_accessible"],
                checks["disk_space_ok"]]):
        raise HTTPException(status_code=503, detail=f"Service unhealthy: {checks}")

    return {"status": "healthy", "checks": checks}

def get_system_uptime() -> str:
    """Get system uptime in human-readable format."""
    try:
        with open('/proc/uptime', 'r') as f:
            uptime_seconds = float(f.readline().split()[0])

        days = int(uptime_seconds // 86400)
        hours = int((uptime_seconds % 86400) // 3600)
        minutes = int((uptime_seconds % 3600) // 60)

        if days > 0:
            return f"{days}d {hours}h {minutes}m"
        elif hours > 0:
            return f"{hours}h {minutes}m"
        else:
            return f"{minutes}m"
    except Exception:
        return "unknown"

# ── Fallback model catalogs ──────────────────────────────────────────
# These are the lists returned when the upstream API is unreachable or
# missing credentials. Refreshed 2026-05-18 per audit M9 + N16. xAI list
# drops the deprecated grok-4-1-fast / grok-4-fast / grok-4-0709 /
# grok-code-fast-1 families that xAI is retiring May 15, 2026 (auto-
# redirected to grok-4.3 server-side). Kept grok-3-beta + grok-3-mini-beta
# in the transition period since they're customer favorites for cheap
# chat (audit N21).
_FALLBACK_MODELS = {
    "google": [
        {"id": "gemini-3.1-pro-preview-customtools", "name": "Gemini 3.1 Pro Custom Tools"},
        {"id": "gemini-3.1-pro-preview", "name": "Gemini 3.1 Pro"},
        {"id": "gemini-2.5-pro", "name": "Gemini 2.5 Pro"},
        {"id": "gemini-2.5-flash", "name": "Gemini 2.5 Flash"},
        {"id": "gemini-2.5-flash-lite", "name": "Gemini 2.5 Flash-Lite"},
        {"id": "gemini-2.0-flash-exp", "name": "Gemini 2.0 Flash (Experimental)"},
        {"id": "gemini-1.5-pro", "name": "Gemini 1.5 Pro (Legacy)"},
        {"id": "gemini-1.5-flash", "name": "Gemini 1.5 Flash (Legacy)"},
    ],
    "anthropic": [
        {"id": "claude-opus-4-7", "name": "Claude Opus 4.7 (Apr 2026, 1M ctx, adaptive thinking)"},
        {"id": "claude-opus-4-6", "name": "Claude Opus 4.6 (Feb 2026)"},
        {"id": "claude-sonnet-4-6", "name": "Claude Sonnet 4.6 (Mar 2026)"},
        {"id": "claude-opus-4-5-20251101", "name": "Claude Opus 4.5 (Nov 2025)"},
        {"id": "claude-sonnet-4-5-20250929", "name": "Claude Sonnet 4.5 (Sep 2025)"},
        {"id": "claude-haiku-4-5-20251001", "name": "Claude Haiku 4.5 (Oct 2025)"},
        {"id": "claude-opus-4-1-20250805", "name": "Claude Opus 4.1 (Aug 2025)"},
        {"id": "claude-sonnet-4-20250514", "name": "Claude Sonnet 4 (May 2025)"},
        {"id": "claude-3-7-sonnet-20250219", "name": "Claude 3.7 Sonnet (Feb 2025)"},
        {"id": "claude-3-5-haiku-20241022", "name": "Claude 3.5 Haiku (Oct 2024)"},
    ],
    "openai": [
        {"id": "gpt-5.1", "name": "GPT-5.1"},
        {"id": "gpt-5-2025-08-07", "name": "GPT-5 (Aug 2025)"},
        {"id": "gpt-5-mini-2025-08-07", "name": "GPT-5 Mini"},
        {"id": "gpt-5-nano-2025-08-07", "name": "GPT-5 Nano"},
        {"id": "o3-2025-04-16", "name": "o3 (Reasoning)"},
        {"id": "o4-mini-2025-04-16", "name": "o4-mini (Reasoning)"},
        {"id": "gpt-4o", "name": "GPT-4o"},
        {"id": "gpt-4o-mini", "name": "GPT-4o Mini"},
    ],
    "xai": [
        {"id": "grok-4.3", "name": "Grok 4.3 (1M ctx, current default)"},
        {"id": "grok-4.20-multi-agent-0309", "name": "Grok 4.20 Multi-Agent (2M ctx, powerhouse)"},
        {"id": "grok-4.20-0309-reasoning", "name": "Grok 4.20 (Reasoning)"},
        {"id": "grok-4.20-0309-non-reasoning", "name": "Grok 4.20 (Instant)"},
        # Transition-period legacy IDs (xAI redirects retired text slugs to
        # grok-4.3 server-side until May 15, 2026 then errors). Keep so old
        # conversations don't crash when reloaded.
        {"id": "grok-3-beta", "name": "Grok 3 Beta (legacy)"},
        {"id": "grok-3-mini-beta", "name": "Grok 3 Mini (legacy, visible thinking)"},
    ],
}

# Per-provider default model id — feeds the dropdown's pre-selected option.
_DEFAULT_MODEL = {
    "google": GEMINI_MODEL_DEFAULT,
    "anthropic": ANTHROPIC_MODEL_DEFAULT,
    "openai": OPENAI_MODEL_DEFAULT,
    "xai": XAI_MODEL_DEFAULT,
}


def _fetch_google_models() -> dict | None:
    """Live-fetch chat-capable Gemini models via the google-generativeai SDK."""
    import google.generativeai as genai
    genai.configure(api_key=GOOGLE_API_KEY)
    models = []
    skip_keywords = ("embedding", "aqa", "bisheng", "learnlm")
    for m in genai.list_models():
        model_id = m.name.replace("models/", "")
        if "generateContent" not in m.supported_generation_methods:
            continue
        if not model_id.startswith("gemini"):
            continue
        if any(kw in model_id.lower() for kw in skip_keywords):
            continue
        display_name = model_id.replace("gemini-", "Gemini ").replace("-", " ").title()
        models.append({"id": model_id, "name": display_name})
    return _wrap("google", models, "live") if models else None


def _fetch_anthropic_models() -> dict | None:
    """Live-fetch Claude models via the official Anthropic SDK (added 2024+)."""
    import anthropic
    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY, timeout=5.0)
    models = []
    # Paginate (default limit=20, max 1000). The Claude catalog is small;
    # one page is plenty.
    page = client.models.list(limit=100)
    for m in page.data:
        model_id = getattr(m, "id", None)
        if not model_id or not model_id.startswith("claude-"):
            continue
        display = getattr(m, "display_name", None) or model_id
        models.append({"id": model_id, "name": display})
    return _wrap("anthropic", models, "live") if models else None


def _fetch_openai_models() -> dict | None:
    """Live-fetch GPT models via the OpenAI SDK."""
    import openai
    client = openai.OpenAI(api_key=OPENAI_API_KEY, timeout=5.0)
    models = []
    for m in client.models.list().data:
        if not m.id.startswith("gpt-") and not m.id.startswith("o"):
            continue
        # 'o3', 'o4-mini' etc. are reasoning models — include them too
        display_name = m.id.upper().replace("-", " ")
        models.append({"id": m.id, "name": display_name})
    return _wrap("openai", models, "live") if models else None


def _fetch_xai_models() -> dict | None:
    """Live-fetch Grok models via xAI's OpenAI-compatible /v1/models endpoint.

    xAI exposes an OpenAI-compatible API surface (per their docs). The
    openai SDK works against it with base_url override. Filter to chat
    Grok models only — exclude grok-imagine-* (image/video gen) per
    audit M9.
    """
    if not XAI_API_KEY:
        return None  # No API key → fall through to fallback
    import openai
    client = openai.OpenAI(
        api_key=XAI_API_KEY,
        base_url="https://api.x.ai/v1",
        timeout=5.0,
    )
    models = []
    for m in client.models.list().data:
        if not m.id.startswith("grok-"):
            continue
        if m.id.startswith("grok-imagine-"):
            continue  # image/video generation — not for chat dropdown
        # xAI's IDs are already brand-formatted (grok-4.3) so just clean for display
        display_name = m.id.replace("grok-", "Grok ").replace("-", " ").title()
        models.append({"id": m.id, "name": display_name})
    return _wrap("xai", models, "live") if models else None


_FETCHERS = {
    "google": _fetch_google_models,
    "anthropic": _fetch_anthropic_models,
    "openai": _fetch_openai_models,
    "xai": _fetch_xai_models,
}


def _wrap(provider: str, models: list, source: str) -> dict:
    """Build the canonical response envelope. Locked contract — both
    frontends parse this shape (see plan T1 verification)."""
    import datetime as _dt
    return {
        "provider": provider,
        "models": models,
        "source": source,
        "default_id": _DEFAULT_MODEL.get(provider, ""),
        "fetched_iso": _dt.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ"),
    }


@app.get("/models/{provider}")
def get_available_models(provider: str):
    """Return the list of chat-capable models for the given provider.

    Tries the live upstream API first (cached 10 minutes on success).
    On failure (missing key, network error, upstream 500) falls back to
    a hardcoded static list (cached 30 seconds — short, so we recover
    quickly when upstream comes back). See Orchestrator/utils/models_cache.py
    for the cache semantics.

    Response shape (audit I12 locked contract):
        {
            "provider": "xai",
            "models": [{"id": "grok-4.3", "name": "Grok 4.3"}, ...],
            "source": "live" | "fallback",
            "default_id": "grok-4.3",
            "fetched_iso": "2026-05-18T20:30:00Z",
            "cached": true | false
        }

    Frontends use `default_id` to pre-select the dropdown option; the
    `(Auto - Latest)` placeholder is preserved by the frontend code, not
    inserted server-side.
    """
    provider = provider.lower()
    if provider not in _FALLBACK_MODELS:
        raise HTTPException(404, f"Unknown provider: {provider}")

    fetcher = _FETCHERS.get(provider)
    return _models_cache_get(
        provider,
        fetcher=(lambda f=fetcher: f()) if fetcher else (lambda: None),
        fallback=lambda p=provider: _wrap(p, _FALLBACK_MODELS[p], "fallback"),
    )

@app.get("/tail")
def tail():
    return parse_tail(read_text_safe(VOL_PATH))

@app.get("/recall")
def recall():
    vol = read_text_safe(VOL_PATH)
    ends = list(END_RX.finditer(vol))
    if not ends: return {"prior": ""}
    end_m = ends[-1]
    snap_id = end_m.group("snap")
    starts_before = list(START_RX.finditer(vol, 0, end_m.start()))
    start_m = next((m for m in reversed(starts_before) if m.group("snap") == snap_id), None)
    if not start_m: raise HTTPException(500, "PARTIAL-SNAPSHOT")
    return {"prior": vol[start_m.start(): end_m.end()]}

@app.get("/assert")
def assert_volume():
    if not VOL_PATH.exists(): return {"bytes": 0, "sha256": "", "volume": ""}
    b = VOL_PATH.read_bytes()
    vol_text = b.decode('utf-8', errors='replace')
    return {"bytes": len(b), "sha256": sha256_bytes(b), "volume": vol_text}

@app.get("/debug/context")
def debug_context_retrieval(operator: str = "Brandon", query: str = "test query"):
    """Debug endpoint to see what context would be retrieved for a query"""
    try:
        RF  = CFG.getint("context", "recent_fossils_per_user", fallback=3)
        KF  = CFG.getint("context", "keyword_fossils_per_user", fallback=33)
        CAP = CFG.getint("context", "max_fossil_chars", fallback=4000)

        vol_txt = read_text_safe(VOL_PATH)
        recent_snaps  = get_recent_fossils_for_operator(vol_txt, operator, RF, CAP)
        # Use hybrid search (keyword + semantic embeddings) for better retrieval
        keyword_snaps = hybrid_retrieve(vol_txt, query, KF, operator=operator)

        recent_ids = list(set(extract_snap_ids(recent_snaps)))
        relevant_ids = extract_snap_ids(keyword_snaps)

        return {
            "operator": operator,
            "query": query,
            "config": {
                "recent_fossils_per_user": RF,
                "keyword_fossils_per_user": KF,
                "max_fossil_chars": CAP
            },
            "retrieved": {
                "recent_count": len(recent_snaps),
                "recent_ids": recent_ids,
                "relevant_count": len(keyword_snaps),
                "relevant_ids": relevant_ids,
                "recent_previews": [snap[:200] + "..." if len(snap) > 200 else snap for snap in recent_snaps],
                "relevant_previews": [snap[:200] + "..." if len(snap) > 200 else snap for snap in keyword_snaps]
            }
        }
    except Exception as e:
        raise HTTPException(500, str(e))

@app.post("/debug/rebuild_index")
def force_rebuild_index():
    """Force rebuild the snapshot index (useful after fixing operator extraction bug)"""
    try:
        index = rebuild_snapshot_index()

        # Show operator distribution
        operator_counts = {}
        for snap_id, meta in index.items():
            op = meta.get("operator", "Unknown")
            operator_counts[op] = operator_counts.get(op, 0) + 1

        return {
            "success": True,
            "total_snapshots": len(index),
            "operator_distribution": operator_counts,
            "message": "Index rebuilt successfully"
        }
    except Exception as e:
        raise HTTPException(500, str(e))

@app.get("/artifact")
def artifact(which: str = "latest", utc: Optional[str] = None):
    if which == "latest":
        man = json.loads(MANIFEST.read_text())
        if not man["archive"]: raise HTTPException(404, "No archive yet")
        return FileResponse(Path(man["archive"][-1]["path"]))
    elif utc:
        p = ARC_DIR / f"Volume_{utc}.txt"
        if not p.exists(): raise HTTPException(404, "Not found")
        return FileResponse(p)
    raise HTTPException(400, "Specify which=latest or utc=...")

@app.get("/artifacts/{artifact_id}")
def download_artifact(artifact_id: str):
    """Serve generated artifact file for download."""
    # Sanitize path to prevent directory traversal
    safe_id = Path(artifact_id).name
    artifact_path = ARTIFACTS_DIR / safe_id

    if not artifact_path.exists():
        raise HTTPException(404, "Artifact not found or expired")

    # Determine content type based on file extension
    suffix = artifact_path.suffix.lower()
    content_types = {
        '.txt': 'text/plain',
        '.md': 'text/markdown',
        '.json': 'application/json',
        '.py': 'text/x-python',
        '.js': 'text/javascript',
        '.pdf': 'application/pdf',
        '.csv': 'text/csv',
        '.docx': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    }
    media_type = content_types.get(suffix, 'application/octet-stream')

    # Extract original filename from artifact_id (format: operator_uuid_filename)
    parts = safe_id.split('_', 2)
    original_filename = parts[2] if len(parts) >= 3 else safe_id

    return FileResponse(artifact_path, media_type=media_type, filename=original_filename)

@app.post("/artifacts/reprocess")
def reprocess_artifacts(body: dict = Body(...)):
    """Re-process raw artifact tags in content and return HTML with download buttons.

    This is used to fix bubbles that show raw [ARTIFACT:...] tags instead of download buttons,
    typically for content generated before the frontend fix was applied.
    """
    from Orchestrator.artifacts import parse_and_process_artifacts

    content = body.get("content", "")
    operator = body.get("operator", "unknown")

    if not content or '[ARTIFACT:' not in content:
        return {"processed_html": None, "message": "No artifact tags found"}

    # Process the content through the artifact generator
    processed = parse_and_process_artifacts(content, operator)

    return {"processed_html": processed}

@app.post("/mint")
def mint_manual(body: dict = Body(None)):
    """Create a snapshot, optionally with provided content.

    If 'content' is provided, creates a snapshot with that content directly.
    Otherwise, creates a snapshot from the conversation log.
    """
    from Orchestrator.checkpoint import mint_with_content

    body = body or {}
    operator = body.get("operator")
    op = (operator or CURRENT_OPERATOR or USERS_DEFAULT).strip()
    content = body.get("content")
    snap_type = body.get("type", "normal")

    try:
        if content:
            # Content provided - use direct minting
            print(f"[MINT] Direct content mint for operator {op}, content length: {len(content)}")
            return mint_with_content(op, content, reason="MCP", snap_type=snap_type)
        else:
            # No content - use conversation log
            return perform_mint(op, "MANUAL")
    except Exception as e:
        import traceback
        print(f"[ERROR] /mint failed:\n{traceback.format_exc()}")
        return {"status": "error", "error": str(e)}


@app.post("/agent/dev-snapshot")
def create_dev_snapshot(body: dict = Body(...)):
    """Create a development snapshot with provided content.

    This endpoint is used by CLI agents (Gemini CLI, Claude Code) to create
    snapshots with detailed session logs.

    Required body fields:
        - content: The snapshot content (detailed session log)
        - operator: The operator name (e.g., "Brandon-DEV")
    """
    from Orchestrator.checkpoint import mint_with_content

    content = body.get("content", "")
    operator = body.get("operator", "Brandon-DEV")

    if not content:
        return {"success": False, "error": "Content is required"}

    if len(content) < 50:
        return {"success": False, "error": "Content too short - provide detailed session log"}

    try:
        result = mint_with_content(operator, content, reason="DEV-SNAPSHOT", snap_type="normal")
        return {
            "success": True,
            "snap_id": result.get("snap_id"),
            "message": f"Development snapshot created: {result.get('snap_id')}",
            "operator": operator
        }
    except Exception as e:
        import traceback
        print(f"[ERROR] /agent/dev-snapshot failed:\n{traceback.format_exc()}")
        return {"success": False, "error": str(e)}

@app.post("/checkpoint")
async def create_checkpoint_manual(body: dict = Body(None)):
    """Create a manual checkpoint for the specified operator"""
    operator = (body or {}).get("operator") # Read operator from JSON body
    op = (operator or CURRENT_OPERATOR or USERS_DEFAULT).strip()
    try:
        s = get_state(op)
        # Trigger checkpoint creation in background thread (fire-and-forget)
        import threading
        threading.Thread(target=create_checkpoint_async, args=(op, True), daemon=True).start()

        return {
            "status": "success",
            "message": f"Checkpoint creation initiated for {op}",
            "operator": op,
            "turn": s.total_turns
        }
    except Exception as e:
        import traceback
        print(f"[ERROR] /checkpoint failed:\n{traceback.format_exc()}")
        return {"status": "error", "error": str(e)}

@app.post("/operator/add")
def add_operator(body: dict = Body(...)):
    """Add a new operator to config.ini and reload the operator list"""
    operator_name = (body or {}).get("name", "").strip()

    if not operator_name:
        raise HTTPException(status_code=400, detail="Operator name is required")

    try:
        global USERS_LIST, CFG

        # Read current operators from config
        current_list = USERS_LIST.copy()

        # Check if operator already exists
        if operator_name in current_list:
            return {
                "status": "exists",
                "message": f"Operator '{operator_name}' already exists",
                "operators": current_list
            }

        # Add new operator
        current_list.append(operator_name)

        # Update config.ini file
        config_path = Path("config.ini")
        CFG.set("users", "list", ", ".join(current_list))

        with open(config_path, "w") as f:
            CFG.write(f)

        # Reload the config to update the global variable
        CFG.read(config_path)
        USERS_LIST = [u.strip() for u in CFG.get("users","list",fallback="Brandon").split(",") if u.strip()]

        return {
            "status": "success",
            "message": f"Operator '{operator_name}' added successfully",
            "operators": USERS_LIST
        }
    except Exception as e:
        import traceback
        print(f"[ERROR] /operator/add failed:\n{traceback.format_exc()}")
        return {"status": "error", "error": str(e)}


@app.delete("/operator/{name}")
def remove_operator(name: str):
    """Remove an operator from config.ini and reload USERS_LIST.

    Idempotent: returns 200 with status='removed' if found, status='not_present' if absent.
    Refuses 400 if attempting to remove the LAST operator (must always have at least one).
    """
    if not name or not name.strip():
        raise HTTPException(status_code=400, detail="Operator name required")
    name = name.strip()

    global USERS_LIST, CFG
    current_list = USERS_LIST.copy()

    if name not in current_list:
        return {
            "status": "not_present",
            "message": f"Operator '{name}' not in list",
            "operators": current_list,
        }

    if len(current_list) == 1:
        raise HTTPException(
            status_code=400,
            detail="Cannot remove the last operator — at least one must remain",
        )

    current_list.remove(name)

    config_path = Path("config.ini")
    CFG.set("users", "list", ", ".join(current_list))
    with open(config_path, "w") as f:
        CFG.write(f)
    CFG.read(config_path)
    USERS_LIST = [u.strip() for u in CFG.get("users", "list", fallback="Brandon").split(",") if u.strip()]

    return {
        "status": "removed",
        "message": f"Operator '{name}' removed",
        "operators": USERS_LIST,
    }


