#!/usr/bin/env python3
from __future__ import annotations
from dataclasses import asdict

"""
agent_routes.py - Claude Code agent, WebSocket, session management
"""

# Standard library imports
import asyncio
import fcntl
import json
import os
import platform
import re
import socket
import subprocess
import time
import uuid
from datetime import datetime
from pathlib import Path
from typing import Dict, Any, Optional, List

# External library imports
import httpx
import psutil
from fastapi import HTTPException, WebSocket, Body, UploadFile, File, Form, Request, WebSocketDisconnect
from fastapi.responses import StreamingResponse, Response

# Local imports
from Orchestrator.checkpoint import app
from Orchestrator.startup import GenIn, ImageData, VideoExtensionIn

# Additional imports (auto-generated by dependency audit)
from Orchestrator.agent_context import (
    compose_with_fossils,
    resolve_operator,
    retrieve_for_agent,
)
from Orchestrator.config import USERS_DEFAULT
from Orchestrator.models import AGENT_AUTO_APPROVE_PATTERNS, AGENT_PERMISSION_PATTERNS, AgentSession, RegisteredApp
from Orchestrator.state import save_app_registry, save_operator_state, agent_lock, APP_REGISTRY, PERSISTED_AGENT_SESSIONS, AGENT_SESSIONS
from Orchestrator.volume import now_utc_iso
from starlette.websockets import WebSocketState


async def _inject_fossil_context(
    websocket: WebSocket,
    operator_raw: str,
    user_text: str,
    log_prefix: str,
) -> tuple[str, dict]:
    """Run shared retrieval and emit provenance to the client.

    Returns (fossil_context_str, provenance_dict). On any failure (or empty
    operator) returns an empty fossil string + empty provenance so the caller
    can proceed without context. Always emits a `provenance` WS frame so the
    client UI has a deterministic signal — even if every list is empty.
    """
    operator = resolve_operator(operator_raw, log_prefix)
    fossil_text, provenance = retrieve_for_agent(
        user_text=user_text,
        operator=operator,
        log_prefix=log_prefix,
    )
    # Ordering invariant: provenance MUST emit BEFORE we spawn Claude. Android's
    # ClaudeAgentClient writes provenance onto the *current* streaming UiMessage;
    # if we emit after stream completion, the event lands on the next bubble.
    await _safe_ws_send(websocket, {"type": "provenance", "data": provenance})
    return fossil_text, provenance


async def _safe_ws_send(websocket, data: dict) -> bool:
    """Send JSON to WebSocket, return False if connection is dead."""
    try:
        if websocket.application_state == WebSocketState.CONNECTED:
            await websocket.send_json(data)
            return True
    except Exception:
        pass
    return False


def create_claude_streaming(working_dir: str, prompt: str, claude_session_id: str = None, continue_session: bool = False, resume_session: bool = False, model: str = None, skip_permissions: bool = True) -> subprocess.Popen:
    """Create Claude Code process in streaming print mode.
    Uses -p (print) mode with stream-json output for programmatic use.
    This completely skips trust dialogs and interactive prompts.
    Args:
        working_dir: Working directory for Claude Code
        prompt: The prompt to send
        claude_session_id: UUID for Claude's session tracking (for --session-id or --resume)
        continue_session: If True, use --continue to continue the conversation
        resume_session: If True, use --resume to restore a session from disk (requires claude_session_id)
        model: Model to use (opus, sonnet, haiku). If None, uses default.
        skip_permissions: If True (default), bypass permission checks. If False, require permission approval.
    Returns:
        subprocess.Popen with stdout pipe for reading JSON stream
    """
    claude_path = os.path.expanduser("~/.local/bin/claude")
    if not os.path.exists(claude_path):
        claude_path = "claude"

    # Build command arguments
    cmd = [
        claude_path,
        "-p",  # Print mode - skips trust dialog
        "--output-format", "stream-json",  # Streaming JSON output
        "--verbose",  # Required for stream-json
    ]

    # Conditionally skip permissions based on user preference
    if skip_permissions:
        cmd.append("--dangerously-skip-permissions")

    # Add model selection if specified
    if model:
        cmd.extend(["--model", model])

    # Add session continuity flags (priority: resume > continue > session-id)
    if resume_session and claude_session_id:
        cmd.extend(["--resume", claude_session_id])  # Resume a specific session from disk
        print(f"[AGENT] Resuming session from disk: {claude_session_id[:8]}...")
    elif continue_session:
        cmd.append("--continue")  # Continue the most recent conversation in this directory
    elif claude_session_id:
        cmd.extend(["--session-id", claude_session_id])

    # Add the prompt
    cmd.append(prompt)

    print(f"[AGENT] Claude command: {' '.join(cmd[:8])}... (continue={continue_session}, resume={resume_session}, session_id={claude_session_id[:8] if claude_session_id else 'None'})")
    print(f"[AGENT] Model specified: {model}")

    # Only use stdin pipe when we need to send permission responses
    # Having stdin=PIPE when not needed can cause Claude Code to hang
    stdin_config = subprocess.PIPE if not skip_permissions else subprocess.DEVNULL

    process = subprocess.Popen(
        cmd,
        stdin=stdin_config,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        cwd=working_dir,
        env={
            **os.environ,
            "PATH": os.environ.get("PATH", "") + ":" + os.path.expanduser("~/.local/bin")
        },
        start_new_session=True
    )

    # Set stdout to non-blocking
    flags = fcntl.fcntl(process.stdout.fileno(), fcntl.F_GETFL)
    fcntl.fcntl(process.stdout.fileno(), fcntl.F_SETFL, flags | os.O_NONBLOCK)

    print(f"[AGENT] Created Claude Code streaming process PID={process.pid} in {working_dir}")
    return process


def create_claude_pty(working_dir: str) -> Tuple[Any, int]:
    """Create PTY-controlled Claude Code process (legacy - for interactive mode).
    Returns:
        Tuple of (subprocess.Popen, master_fd)
    """
    import subprocess

    master_fd, slave_fd = pty.openpty()

    # Set terminal size (120 cols x 40 rows)
    cols, rows = 120, 40
    winsize = struct.pack('HHHH', rows, cols, 0, 0)
    fcntl.ioctl(slave_fd, termios.TIOCSWINSZ, winsize)

    # Set non-blocking mode on master
    flags = fcntl.fcntl(master_fd, fcntl.F_GETFL)
    fcntl.fcntl(master_fd, fcntl.F_SETFL, flags | os.O_NONBLOCK)

    # Launch Claude Code CLI - use full path since service might not have ~/.local/bin in PATH
    claude_path = os.path.expanduser("~/.local/bin/claude")
    if not os.path.exists(claude_path):
        # Fallback to PATH lookup
        claude_path = "claude"

    # Use --dangerously-skip-permissions to bypass trust dialog and permission prompts
    # This allows for smooth streaming without interactive prompts
    process = subprocess.Popen(
        [claude_path, "--dangerously-skip-permissions"],
        stdin=slave_fd,
        stdout=slave_fd,
        stderr=slave_fd,
        cwd=working_dir,
        env={
            **os.environ,
            "TERM": "xterm-256color",
            "COLUMNS": str(cols),
            "LINES": str(rows),
            "PATH": os.environ.get("PATH", "") + ":" + os.path.expanduser("~/.local/bin")
        },
        start_new_session=True
    )

    # Close slave fd in parent process
    os.close(slave_fd)

    print(f"[AGENT] Created Claude Code process PID={process.pid} in {working_dir}")
    return process, master_fd


def detect_agent_permission(text: str) -> Optional[Dict]:
    """Parse text for permission prompts from Claude Code.

    Returns:
        Dict with permission info if detected, None otherwise.
        If auto-approved, returns {"auto_approved": True, ...}
    """
    for pattern in AGENT_PERMISSION_PATTERNS:
        match = pattern.search(text)
        if match:
            prompt_text = match.group()

            # Check if this should be auto-approved (file reads)
            for auto_pattern in AGENT_AUTO_APPROVE_PATTERNS:
                if auto_pattern.search(text):
                    return {
                        "prompt_text": prompt_text,
                        "auto_approved": True
                    }

            # Determine action type
            action_type = "bash"
            lower_text = text.lower()
            if "edit" in lower_text or "write" in lower_text:
                action_type = "edit"
            elif "read" in lower_text:
                action_type = "read"

            return {
                "prompt_text": prompt_text,
                "action_type": action_type,
                "options": ["Allow", "Deny"],
                "auto_approved": False
            }
    return None


def detect_app_startup(text: str) -> Optional[Dict]:
    """Detect when Claude Code starts a local server.
    Returns:
        Dict with port and name if detected, None otherwise.
    """
    # Ports to exclude (system services)
    EXCLUDED_PORTS = {
        9091,  # AI BlackBox Orchestrator
        8080,  # Tailscale
        80,    # Standard HTTP
        443,   # Standard HTTPS
        22,    # SSH
        3000,  # Common dev server (often system-wide)
        5000,  # Common dev server (often system-wide)
    }

    patterns = [
        re.compile(r"listening on (?:http://)?localhost:(\d+)", re.I),
        re.compile(r"server.+(?:at|on).+localhost:(\d+)", re.I),
        re.compile(r"running (?:at|on).+localhost:(\d+)", re.I),
        re.compile(r"http://localhost:(\d+)"),
        re.compile(r"127\.0\.0\.1:(\d+)"),
    ]

    for pattern in patterns:
        match = pattern.search(text)
        if match:
            port = int(match.group(1))
            # Skip excluded ports
            if port in EXCLUDED_PORTS:
                continue
            return {
                "port": port,
                "name": f"App:{port}",
                "detected_at": now_utc_iso()
            }
    return None


def register_agent_app(session_id: str, operator: str, app_info: Dict):
    """Register a newly detected app in the registry."""
    app_id = str(uuid.uuid4())
    app = RegisteredApp(
        app_id=app_id,
        name=app_info.get("name", f"App:{app_info['port']}"),
        port=app_info["port"],
        directory=app_info.get("directory", ""),
        session_id=session_id,
        operator=operator,
        created_at=now_utc_iso()
    )

    with agent_lock:
        APP_REGISTRY[app_id] = app

        # Also add to session's app list
        if session_id in AGENT_SESSIONS:
            AGENT_SESSIONS[session_id].apps.append(asdict(app))

    # Persist to disk
    save_app_registry()

    print(f"[AGENT] Registered app {app_id} on port {app_info['port']}")
    return app


def ansi_to_html(text: str) -> str:
    """Convert ANSI escape codes to HTML spans with CSS classes."""
    # Color mappings
    colors = {
        '30': 'black', '31': 'red', '32': 'green', '33': 'yellow',
        '34': 'blue', '35': 'magenta', '36': 'cyan', '37': 'white',
        '90': 'bright-black', '91': 'bright-red', '92': 'bright-green',
        '93': 'bright-yellow', '94': 'bright-blue', '95': 'bright-magenta',
        '96': 'bright-cyan', '97': 'bright-white'
    }

    result = text
    # Convert color codes to spans
    for code, color in colors.items():
        result = re.sub(rf'\x1b\[{code}m', f'<span class="ansi-{color}">', result)

    # Bold
    result = re.sub(r'\x1b\[1m', '<span class="ansi-bold">', result)
    # Dim
    result = re.sub(r'\x1b\[2m', '<span class="ansi-dim">', result)
    # Italic
    result = re.sub(r'\x1b\[3m', '<span class="ansi-italic">', result)
    # Underline
    result = re.sub(r'\x1b\[4m', '<span class="ansi-underline">', result)
    # Reset
    result = re.sub(r'\x1b\[0m', '</span>', result)
    result = re.sub(r'\x1b\[m', '</span>', result)

    # Remove any remaining escape codes we don't handle
    result = re.sub(r'\x1b\[[0-9;]*[a-zA-Z]', '', result)
    # Remove other control sequences
    result = re.sub(r'\x1b\][^\x07]*\x07', '', result)  # OSC sequences
    result = re.sub(r'\x1b[PX^_][^\x1b]*\x1b\\', '', result)  # Other sequences

    return result


async def stream_agent_output(session: AgentSession):
    """Stream raw terminal output from Claude Code CLI.
    Simple approach: just pass through everything so user sees exactly what CLI shows.
    Yields 'waiting' periodically but keeps running to catch delayed output.
    """
    print(f"[AGENT] Starting RAW output stream for session {session.session_id}")

    idle_count = 0
    total_idle = 0
    max_idle_before_yield = 20  # 2 seconds (20 * 0.1s) before yielding "waiting"
    max_total_idle = 300  # 30 seconds total idle before giving up

    while session.process and session.process.poll() is None:
        readable, _, _ = select.select([session.pty_master], [], [], 0.05)

        if readable:
            idle_count = 0  # Reset idle counter when we get output
            total_idle = 0
            try:
                raw_chunk = os.read(session.pty_master, 4096)
                if not raw_chunk:
                    continue

                chunk = raw_chunk.decode('utf-8', errors='replace')
                print(f"[AGENT] Got output ({len(chunk)} bytes): {repr(chunk[:80])}...")

                # Convert ANSI to HTML for display
                html_chunk = ansi_to_html(chunk)
                # Clean up carriage returns (terminal cursor movement)
                html_chunk = html_chunk.replace('\r\n', '\n').replace('\r', '\n')

                # Send raw output immediately
                if html_chunk:
                    yield {"type": "raw", "data": html_chunk}
                    session.last_activity = now_utc_iso()

            except OSError as e:
                print(f"[AGENT] OSError: {e}")
                break
            except Exception as e:
                print(f"[AGENT] Error: {e}")
                break
        else:
            idle_count += 1
            total_idle += 1

            # Periodically yield "waiting" to let frontend know we're still alive
            if idle_count >= max_idle_before_yield:
                print(f"[AGENT] Idle for {idle_count * 0.1:.1f}s, yielding 'waiting', total idle: {total_idle * 0.1:.1f}s")
                yield {"type": "waiting", "data": None}
                idle_count = 0  # Reset for next yield cycle

            # Give up after extended idle
            if total_idle >= max_total_idle:
                print(f"[AGENT] Extended idle timeout ({total_idle * 0.1:.1f}s), returning")
                return

        await asyncio.sleep(0.1)

    print(f"[AGENT] Stream ended - process exited for session {session.session_id}")
    session.status = "completed"
    yield {"type": "completed", "data": None}


@app.get("/agent/test")
async def test_agent_endpoint():
    """Test endpoint to verify agent functionality is available."""
    claude_path = os.path.expanduser("~/.local/bin/claude")
    claude_exists = os.path.exists(claude_path)

    return {
        "status": "ok",
        "claude_path": claude_path,
        "claude_exists": claude_exists,
        "agent_sessions": len(AGENT_SESSIONS),
        "app_registry": len(APP_REGISTRY),
        "message": "Agent endpoint is available"
    }


async def pty_reader_task(session: AgentSession, websocket: WebSocket):
    """Background task that reads PTY output and sends to WebSocket."""
    print(f"[AGENT] PTY reader task started for session {session.session_id}")

    try:
        while session.process and session.process.poll() is None:
            readable, _, _ = select.select([session.pty_master], [], [], 0.1)

            if readable:
                try:
                    raw_chunk = os.read(session.pty_master, 4096)
                    if not raw_chunk:
                        continue

                    chunk = raw_chunk.decode('utf-8', errors='replace')
                    print(f"[AGENT] Got output ({len(chunk)} bytes): {repr(chunk[:80])}...")

                    # Convert ANSI to HTML for display
                    html_chunk = ansi_to_html(chunk)
                    html_chunk = html_chunk.replace('\r\n', '\n').replace('\r', '\n')

                    if html_chunk:
                        if not await _safe_ws_send(websocket, {"type": "raw", "data": html_chunk}):
                            print(f"[AGENT] Client disconnected during PTY stream, stopping reader")
                            return
                        session.last_activity = now_utc_iso()

                except OSError as e:
                    print(f"[AGENT] PTY read error: {e}")
                    break

            await asyncio.sleep(0.1)  # Small sleep to yield control

    except Exception as e:
        print(f"[AGENT] PTY reader error: {e}")

    print(f"[AGENT] PTY reader task ended for session {session.session_id}")
    session.status = "completed"
    await _safe_ws_send(websocket, {"type": "completed", "data": None})


def background_process_reader(session: AgentSession):
    """Background thread that continuously reads from Claude Code process.
    This runs independently of WebSocket connections, allowing the agent to
    continue executing even if the portal disconnects or restarts.
    """
    print(f"[AGENT] Background reader started for session {session.session_id}")

    line_buffer = ""

    try:
        while session.process and session.process.poll() is None:
            try:
                # Try to read from stdout (non-blocking)
                raw_data = session.process.stdout.read(4096)
                if raw_data:
                    line_buffer += raw_data.decode('utf-8', errors='replace')

                    # Process complete lines
                    while '\n' in line_buffer:
                        line, line_buffer = line_buffer.split('\n', 1)
                        line = line.strip()
                        if not line:
                            continue

                        # Store in output buffer for reconnection
                        with agent_lock:
                            session.output_buffer.append(line)
                            session.last_activity = now_utc_iso()

            except (BlockingIOError, IOError):
                # No data available yet
                pass
            except Exception as e:
                print(f"[AGENT] Background reader error: {e}")
                break

            time.sleep(0.02)  # Small sleep to prevent busy-waiting

        # Process any remaining data
        try:
            remaining = session.process.stdout.read()
            if remaining:
                line_buffer += remaining.decode('utf-8', errors='replace')
                for line in line_buffer.split('\n'):
                    if line.strip():
                        with agent_lock:
                            session.output_buffer.append(line.strip())
        except:
            pass

    except Exception as e:
        print(f"[AGENT] Background reader fatal error: {e}")
        import traceback
        traceback.print_exc()

    print(f"[AGENT] Background reader ended for session {session.session_id}")
    with agent_lock:
        session.status = "completed"


async def streaming_reader_task(session: AgentSession, websocket: WebSocket):
    """Background task that broadcasts buffered output to this WebSocket.
    Reads from session.output_buffer which is populated by background_process_reader.
    Uses session.output_cursor to track position across multiple reader tasks.
    """
    print(f"[AGENT] Streaming reader task started for session {session.session_id}, cursor at {session.output_cursor}")

    try:
        while session.process and session.process.poll() is None:
            # Get new output from buffer using session's cursor
            with agent_lock:
                if session.output_cursor < len(session.output_buffer):
                    new_lines = session.output_buffer[session.output_cursor:]
                    session.output_cursor = len(session.output_buffer)
                else:
                    new_lines = []
            
            # Send new lines to WebSocket
            for line in new_lines:
                if not line.strip():
                    continue
                    
                try:
                    event = json.loads(line)
                    event_type = event.get("type", "")
                    print(f"[AGENT-STREAM] Event type: {event_type}")

                    if event_type == "assistant":
                        # The "assistant" event contains the COMPLETE message.
                        # This may come INSTEAD of content_block_delta (non-streaming)
                        # or AFTER content_block_delta (streaming, duplicate).
                        # We'll send it but mark it as "assistant_message" so frontend can dedupe if needed.
                        message = event.get("message", {})
                        content = message.get("content", [])
                        for block in content:
                            if block.get("type") == "text":
                                text = block.get("text", "")
                                if text:
                                    # Send as special type so frontend knows this is complete message
                                    if not await _safe_ws_send(websocket, {"type": "assistant_message", "data": text}):
                                        print(f"[AGENT] Client disconnected during stream, stopping reader")
                                        return
                            elif block.get("type") == "tool_use":
                                tool_name = block.get("name", "")
                                tool_input = block.get("input", {})

                                # Special handling for TodoWrite tool - send as dedicated message type
                                if tool_name == "TodoWrite":
                                    todos = tool_input.get("todos", [])
                                    if not await _safe_ws_send(websocket, {
                                        "type": "todo_write",
                                        "data": todos
                                    }):
                                        print(f"[AGENT] Client disconnected during stream, stopping reader")
                                        return
                                    print(f"[AGENT] TodoWrite: {len(todos)} todos")
                                    continue  # Don't send as generic tool_use

                                # Check if we need to request permission for this tool
                                if not session.skip_permissions:
                                    # Determine tool type for icon/display
                                    action_type = "bash" if tool_name.lower() == "bash" else "edit"

                                    # Format prompt text for display
                                    if tool_name.lower() == "bash":
                                        prompt_text = f"Execute: {tool_input.get('command', str(tool_input)[:100])}"
                                    elif tool_name.lower() in ("edit", "write"):
                                        prompt_text = f"Modify file: {tool_input.get('file_path', 'unknown')}"
                                    elif tool_name.lower() == "read":
                                        prompt_text = f"Read file: {tool_input.get('file_path', 'unknown')}"
                                    else:
                                        prompt_text = f"Use tool: {tool_name}"

                                    # Store pending permission
                                    session.pending_permission = {
                                        "tool": tool_name,
                                        "input": tool_input,
                                        "action_type": action_type,
                                        "prompt_text": prompt_text
                                    }
                                    session.status = "waiting_permission"

                                    # Send permission request to frontend
                                    if not await _safe_ws_send(websocket, {
                                        "type": "permission_request",
                                        "data": {
                                            "tool": tool_name,
                                            "input": tool_input,
                                            "action_type": action_type,
                                            "prompt_text": prompt_text
                                        }
                                    }):
                                        print(f"[AGENT] Client disconnected during stream, stopping reader")
                                        return
                                    print(f"[AGENT] Permission requested for {tool_name}: {prompt_text[:50]}...")
                                else:
                                    # Just send tool_use event (auto-approved)
                                    if not await _safe_ws_send(websocket, {
                                        "type": "tool_use",
                                        "data": {"name": tool_name, "input": tool_input}
                                    }):
                                        print(f"[AGENT] Client disconnected during stream, stopping reader")
                                        return
                    
                    elif event_type == "content_block_delta":
                        delta = event.get("delta", {})
                        if delta.get("type") == "text_delta":
                            text = delta.get("text", "")
                            if text:
                                if not await _safe_ws_send(websocket, {"type": "content", "data": text}):
                                    print(f"[AGENT] Client disconnected during stream, stopping reader")
                                    return
                        elif delta.get("type") == "thinking_delta":
                            thinking = delta.get("thinking", "")
                            if thinking:
                                if not await _safe_ws_send(websocket, {"type": "thinking", "data": thinking}):
                                    print(f"[AGENT] Client disconnected during stream, stopping reader")
                                    return

                    elif event_type == "user":
                        # User events contain tool results from Claude Code's tool execution
                        # Structure: {"type":"user","message":{"content":[{"type":"tool_result","content":"..."}]},"tool_use_result":{...}}
                        message = event.get("message", {})
                        # Handle case where message might be a list
                        if isinstance(message, list):
                            content_blocks = message
                        elif isinstance(message, dict):
                            content_blocks = message.get("content", [])
                        else:
                            content_blocks = []

                        tool_use_result = event.get("tool_use_result", {})
                        # Handle case where tool_use_result might be a list
                        if not isinstance(tool_use_result, dict):
                            tool_use_result = {}

                        print(f"[AGENT-STREAM] User event with {len(content_blocks)} content blocks, tool_use_result type: {tool_use_result.get('type', 'none')}")

                        for block in content_blocks:
                            if isinstance(block, dict) and block.get("type") == "tool_result":
                                tool_content = block.get("content", "")
                                if tool_content:
                                    print(f"[AGENT-STREAM] Sending tool_result, preview: {str(tool_content)[:100]}...")
                                    if not await _safe_ws_send(websocket, {"type": "tool_result", "data": tool_content}):
                                        print(f"[AGENT] Client disconnected during stream, stopping reader")
                                        return

                        # Also send structured file info if available (for diffs, file reads, edits)
                        if tool_use_result:
                            result_type = tool_use_result.get("type", "")

                            # Handle Read tool results (file content)
                            if result_type == "text" and tool_use_result.get("file"):
                                file_info = tool_use_result.get("file", {})
                                if not await _safe_ws_send(websocket, {
                                    "type": "file_result",
                                    "data": {
                                        "filePath": file_info.get("filePath", ""),
                                        "content": file_info.get("content", ""),
                                        "numLines": file_info.get("numLines", 0),
                                        "startLine": file_info.get("startLine", 1)
                                    }
                                }):
                                    print(f"[AGENT] Client disconnected during stream, stopping reader")
                                    return

                            # Handle Edit tool results (diffs with structuredPatch)
                            elif tool_use_result.get("structuredPatch"):
                                file_path = tool_use_result.get("filePath", "")
                                old_string = tool_use_result.get("oldString", "")
                                new_string = tool_use_result.get("newString", "")
                                patches = tool_use_result.get("structuredPatch", [])

                                # Build unified diff from structuredPatch
                                diff_lines = []
                                for patch in patches:
                                    old_start = patch.get("oldStart", 1)
                                    old_lines = patch.get("oldLines", 0)
                                    new_start = patch.get("newStart", 1)
                                    new_lines = patch.get("newLines", 0)
                                    diff_lines.append(f"@@ -{old_start},{old_lines} +{new_start},{new_lines} @@")
                                    diff_lines.extend(patch.get("lines", []))

                                diff_text = "\n".join(diff_lines)
                                print(f"[AGENT-STREAM] Sending edit_diff for {file_path}: {len(diff_lines)} lines")

                                if not await _safe_ws_send(websocket, {
                                    "type": "edit_diff",
                                    "data": {
                                        "filePath": file_path,
                                        "oldString": old_string,
                                        "newString": new_string,
                                        "diff": diff_text
                                    }
                                }):
                                    print(f"[AGENT] Client disconnected during stream, stopping reader")
                                    return

                    elif event_type == "tool_result":
                        # Legacy handling for direct tool_result events (may not be used)
                        tool_result = event.get("tool_result", {})
                        print(f"[AGENT-STREAM] Direct tool_result event, keys: {list(tool_result.keys())}")
                        content = tool_result.get("content", "")
                        if isinstance(content, list):
                            for block in content:
                                if isinstance(block, dict) and block.get("type") == "text":
                                    text = block.get("text", "")
                                    if text:
                                        if not await _safe_ws_send(websocket, {"type": "tool_result", "data": text}):
                                            print(f"[AGENT] Client disconnected during stream, stopping reader")
                                            return
                        elif isinstance(content, str) and content:
                            if not await _safe_ws_send(websocket, {"type": "tool_result", "data": content}):
                                print(f"[AGENT] Client disconnected during stream, stopping reader")
                                return

                    elif event_type == "result":
                        # The "result" event contains a summary/final output.
                        # This may duplicate content already sent via content_block_delta.
                        # Log it for debugging but don't send to avoid duplication.
                        result = event.get("result", "")
                        if result:
                            print(f"[AGENT-STREAM] Result event (not sending to avoid dupe): {result[:100]}...")
                    
                    elif event_type == "error":
                        error = event.get("error", {}).get("message", "Unknown error")
                        if not await _safe_ws_send(websocket, {"type": "error", "data": error}):
                            print(f"[AGENT] Client disconnected during stream, stopping reader")
                            return
                        
                except json.JSONDecodeError:
                    # Not JSON, send as raw
                    if not await _safe_ws_send(websocket, {"type": "raw", "data": line}):
                        print(f"[AGENT] Client disconnected during stream, stopping reader")
                        return
                except Exception as e:
                    print(f"[AGENT] Error processing line: {e}")
            
            await asyncio.sleep(0.1)

        # Process completed
        with agent_lock:
            session.status = "completed"
        await _safe_ws_send(websocket, {"type": "completed", "data": None})

    except Exception as e:
        print(f"[AGENT] Streaming reader error: {e}")
        import traceback
        traceback.print_exc()


@app.websocket("/ws/agent/{session_id}")
async def agent_websocket(websocket: WebSocket, session_id: str):
    """WebSocket endpoint for Claude Code CLI streaming.
    Uses streaming JSON mode (-p --output-format stream-json) for reliable output.
    Supports session continuity with --continue flag for follow-up messages.
    """
    print(f"[AGENT] WebSocket endpoint hit for session: {session_id}")
    await websocket.accept()
    print(f"[AGENT] WebSocket accepted for session: {session_id}")

    reader_task = None
    session = None

    try:
        while True:
            data = await websocket.receive_json()
            print(f"[AGENT] Received message type: {data.get('type')}")

            if data["type"] == "prompt":
                operator = data.get("operator", USERS_DEFAULT)
                # Default to blackbox_poc folder instead of home directory
                default_dir = "/home/ai-black-box-fc/Desktop/blackbox_poc./blackbox_poc"
                working_dir = data.get("working_dir") or default_dir
                prompt_text = data.get("text", "")
                model = data.get("model", "sonnet")  # Default to sonnet
                skip_permissions = data.get("skip_permissions", True)  # Default to skip (safe mode)
                print(f"[AGENT] RAW WebSocket data received: {data}")
                print(f"[AGENT] Extracted skip_permissions={skip_permissions} (type={type(skip_permissions).__name__})")

                if not prompt_text:
                    await _safe_ws_send(websocket, {"type": "error", "data": "No prompt provided"})
                    continue

                # Plan Task 4: inject fossil retrieval at session start.
                # We always emit a `provenance` event so the Android client UI
                # has a deterministic signal, even if retrieval returns empty
                # lists for an unknown operator.
                fossil_text, provenance = await _inject_fossil_context(
                    websocket,
                    operator_raw=operator,
                    user_text=prompt_text,
                    log_prefix="[AGENT]",
                )

                # Check if we have an existing session to continue
                with agent_lock:
                    session = AGENT_SESSIONS.get(session_id)

                # Wait for any previous process to complete
                if session and session.process and session.process.poll() is None:
                    print(f"[AGENT] Waiting for previous process to complete...")
                    # Wait up to 5 seconds for process to finish
                    for _ in range(50):
                        if session.process.poll() is not None:
                            break
                        await asyncio.sleep(0.1)
                    if session.process.poll() is None:
                        session.process.terminate()

                # Check for persisted session from previous server run
                persisted_session = PERSISTED_AGENT_SESSIONS.get(operator)
                is_resume_from_disk = False

                # Determine if this is a continuation or resume
                if session is not None and session.message_count > 0:
                    # Active session in memory - continue it
                    is_continuation = True
                    is_resume_from_disk = False
                    claude_session_id = session.claude_session_id
                elif persisted_session and not session:
                    # No active session but we have persisted data - resume from disk
                    is_continuation = False
                    is_resume_from_disk = True
                    claude_session_id = persisted_session.get("claude_session_id")
                    print(f"[AGENT] Found persisted session for {operator}, will resume: {claude_session_id[:8]}...")
                else:
                    # Brand new session
                    is_continuation = False
                    is_resume_from_disk = False
                    claude_session_id = str(uuid.uuid4())

                print(f"[AGENT] Session mode: continuation={is_continuation}, resume_from_disk={is_resume_from_disk}, message_count: {session.message_count if session else (persisted_session.get('message_count', 0) if persisted_session else 0)}, model: {model}, skip_permissions: {skip_permissions}")

                # Plan Task 4: only prepend fossil context to brand-new sessions.
                # Continuations and resume-from-disk already carry prior turns
                # via Claude Code CLI's `--continue` / `--resume` flags; re-
                # injecting fossils every message would blow the prompt budget.
                effective_prompt = prompt_text
                if not is_continuation and not is_resume_from_disk:
                    effective_prompt = compose_with_fossils(fossil_text, prompt_text)

                # Create new streaming process
                process = create_claude_streaming(
                    working_dir,
                    effective_prompt,
                    claude_session_id=claude_session_id if (is_resume_from_disk or not is_continuation) else None,
                    continue_session=is_continuation,
                    resume_session=is_resume_from_disk,
                    model=model,
                    skip_permissions=skip_permissions
                )

                if session is None:
                    # Create new session (or restore from persisted)
                    restored_msg_count = persisted_session.get("message_count", 0) if is_resume_from_disk else 0
                    session = AgentSession(
                        session_id=session_id,
                        operator=operator,
                        process=process,
                        pty_master=None,
                        mode="streaming",
                        working_directory=working_dir,
                        created_at=now_utc_iso(),
                        last_activity=now_utc_iso(),
                        status="running",
                        claude_session_id=claude_session_id,
                        message_count=restored_msg_count + 1,
                        model=model,
                        skip_permissions=skip_permissions,
                        provenance=provenance,
                    )
                    if is_resume_from_disk:
                        print(f"[AGENT] Restored session from disk with {restored_msg_count} previous messages")
                else:
                    # Update existing session
                    session.process = process
                    session.last_activity = now_utc_iso()
                    session.status = "running"
                    session.message_count += 1
                    session.model = model  # Update model in case user changed it
                    session.skip_permissions = skip_permissions  # Update permission mode
                    # Refresh provenance to reflect the latest user prompt
                    session.provenance = provenance

                with agent_lock:
                    AGENT_SESSIONS[session_id] = session

                # Save session state immediately so we don't lose it on crash
                save_operator_state()

                print(f"[AGENT] {'Resumed' if is_resume_from_disk else ('Continuing' if is_continuation else 'Created')} session (msg #{session.message_count}): {prompt_text[:50]}...")

                # Start background reader thread if not already running
                if session.background_reader is None or not session.background_reader.is_alive():
                    import threading
                    session.background_reader = threading.Thread(
                        target=background_process_reader,
                        args=(session,),
                        daemon=True,
                        name=f"agent-reader-{session_id[:8]}"
                    )
                    session.background_reader.start()
                    print(f"[AGENT] Started background reader thread for session {session_id[:8]}")

                # Add this websocket to the session's client list
                with agent_lock:
                    if websocket not in session.websocket_clients:
                        session.websocket_clients.append(websocket)

                # Start streaming reader in background task
                if reader_task is not None and not reader_task.done():
                    reader_task.cancel()
                reader_task = asyncio.create_task(streaming_reader_task(session, websocket))
                print(f"[AGENT] Started streaming reader task")

            elif data["type"] == "input":
                # Handle follow-up input as a continuation prompt
                input_text = data.get("text", "").strip()
                if not input_text:
                    await _safe_ws_send(websocket, {
                        "type": "info",
                        "data": "Empty input ignored"
                    })
                    continue

                print(f"[AGENT] Processing input as follow-up: {input_text[:50]}...")

                # Get existing session
                with agent_lock:
                    session = AGENT_SESSIONS.get(session_id)

                if session is None:
                    await _safe_ws_send(websocket, {
                        "type": "error",
                        "data": "No active session - start a new conversation"
                    })
                    continue

                # Wait for any previous process to complete
                if session.process and session.process.poll() is None:
                    print(f"[AGENT] Waiting for previous process to complete...")
                    for _ in range(50):
                        if session.process.poll() is not None:
                            break
                        await asyncio.sleep(0.1)
                    if session.process.poll() is None:
                        session.process.terminate()

                # Create continuation process with --continue flag
                process = create_claude_streaming(
                    session.working_directory,
                    input_text,
                    claude_session_id=None,
                    continue_session=True,  # Use --continue for follow-up
                    model=session.model,  # Use the session's model
                    skip_permissions=session.skip_permissions  # Use the session's permission mode
                )

                # Update session
                session.process = process
                session.last_activity = now_utc_iso()
                session.status = "running"
                session.message_count += 1

                with agent_lock:
                    AGENT_SESSIONS[session_id] = session

                # Save session state after each message
                save_operator_state()

                print(f"[AGENT] Continuing session (msg #{session.message_count}): {input_text[:50]}...")

                # Start background reader thread if not already running
                if session.background_reader is None or not session.background_reader.is_alive():
                    import threading
                    session.background_reader = threading.Thread(
                        target=background_process_reader,
                        args=(session,),
                        daemon=True,
                        name=f"agent-reader-{session_id[:8]}"
                    )
                    session.background_reader.start()
                    print(f"[AGENT] Started background reader thread for continuation")

                # Start streaming reader
                if reader_task is not None and not reader_task.done():
                    reader_task.cancel()
                reader_task = asyncio.create_task(streaming_reader_task(session, websocket))
                print(f"[AGENT] Started streaming reader task for follow-up")

            elif data["type"] == "end_session":
                # End the current session and clear persisted data
                with agent_lock:
                    session = AGENT_SESSIONS.get(session_id)
                    if session:
                        if session.process and session.process.poll() is None:
                            session.process.terminate()
                        session.status = "completed"
                        session.message_count = 0
                        del AGENT_SESSIONS[session_id]
                        session = None
                # Clear persisted session for this operator so they start fresh
                if operator in PERSISTED_AGENT_SESSIONS:
                    del PERSISTED_AGENT_SESSIONS[operator]
                    print(f"[AGENT] Cleared persisted session for operator: {operator}")
                # Save state to persist the cleared session
                save_operator_state()
                await _safe_ws_send(websocket, {"type": "session_ended", "data": "Session ended. Start a new conversation."})
                print(f"[AGENT] Session ended by user: {session_id}")

            elif data["type"] == "permission_response":
                # Handle permission response from frontend
                approved = data.get("approved", False)
                with agent_lock:
                    session = AGENT_SESSIONS.get(session_id)
                if session and session.process and session.process.stdin:
                    try:
                        response = "y\n" if approved else "n\n"
                        session.process.stdin.write(response.encode())
                        session.process.stdin.flush()
                        print(f"[AGENT] Sent permission response: {'approved' if approved else 'denied'}")
                        # Update session status
                        session.status = "running"
                        session.pending_permission = None
                    except Exception as e:
                        print(f"[AGENT] Failed to send permission response: {e}")
                        await _safe_ws_send(websocket, {
                            "type": "error",
                            "data": f"Failed to send permission response: {e}"
                        })

            elif data["type"] == "reconnect":
                # Reconnect to existing session to resume streaming
                operator = data.get("operator", USERS_DEFAULT)
                print(f"[AGENT] Reconnect request from operator: {operator}")

                with agent_lock:
                    session = AGENT_SESSIONS.get(session_id)

                if session is None:
                    await _safe_ws_send(websocket, {
                        "type": "error",
                        "data": "No active session found to reconnect to"
                    })
                    continue

                # Add this websocket to the session's client list
                with agent_lock:
                    if websocket not in session.websocket_clients:
                        session.websocket_clients.append(websocket)

                # If process is still running, start streaming reader
                if session.process and session.process.poll() is None:
                    # Start background reader thread if not already running
                    if session.background_reader is None or not session.background_reader.is_alive():
                        import threading
                        session.background_reader = threading.Thread(
                            target=background_process_reader,
                            args=(session,),
                            daemon=True,
                            name=f"agent-reader-{session_id[:8]}"
                        )
                        session.background_reader.start()
                        print(f"[AGENT] Started background reader for reconnected session")

                    # Start streaming reader task
                    if reader_task is not None and not reader_task.done():
                        reader_task.cancel()
                    reader_task = asyncio.create_task(streaming_reader_task(session, websocket))
                    print(f"[AGENT] Started streaming reader for reconnected client")

                    await _safe_ws_send(websocket, {
                        "type": "info",
                        "data": f"Reconnected to session (msg #{session.message_count}). Resuming stream..."
                    })
                else:
                    # Process completed, send notification
                    await _safe_ws_send(websocket, {
                        "type": "completed",
                        "data": None
                    })
                    print(f"[AGENT] Reconnected to completed session, notified client")

            elif data["type"] == "ping":
                await _safe_ws_send(websocket, {"type": "pong"})

    except WebSocketDisconnect:
        print(f"[AGENT] WebSocket disconnected: {session_id}")
        # Remove this websocket from session's client list
        with agent_lock:
            session = AGENT_SESSIONS.get(session_id)
            if session and websocket in session.websocket_clients:
                session.websocket_clients.remove(websocket)
                print(f"[AGENT] Removed websocket from session {session_id[:8]}, {len(session.websocket_clients)} clients remaining")
        # Note: Process continues running in background!
        print(f"[AGENT] Agent process continues running, can reconnect later")
    except Exception as e:
        print(f"[AGENT] WebSocket error: {e}")
        import traceback
        traceback.print_exc()
        # Also remove websocket on error
        with agent_lock:
            session = AGENT_SESSIONS.get(session_id)
            if session and websocket in session.websocket_clients:
                session.websocket_clients.remove(websocket)


@app.get("/agent/session/{operator}")
async def get_agent_session_for_operator(operator: str):
    """Get existing agent session for an operator."""
    with agent_lock:
        for session_id, session in AGENT_SESSIONS.items():
            if session.operator == operator and session.status != "completed":
                return {
                    "session": {
                        "session_id": session.session_id,
                        "status": session.status,
                        "working_directory": session.working_directory,
                        "created_at": session.created_at,
                        "last_activity": session.last_activity,
                        "apps": session.apps
                    },
                    "output_buffer": session.output_buffer
                }
    return {"session": None}


@app.get("/agent/apps")
async def list_agent_apps(operator: Optional[str] = None):
    """List registered apps, optionally filtered by operator."""
    with agent_lock:
        if operator:
            apps = [asdict(app) for app in APP_REGISTRY.values() if app.operator == operator]
        else:
            apps = [asdict(app) for app in APP_REGISTRY.values()]
    return {"apps": apps}


@app.get("/agent/commands")
async def list_slash_commands():
    """List available slash commands - both built-in and custom."""

    # Claude Code built-in commands (39 total from official docs)
    builtin_commands = [
        # Session Management
        {"name": "clear", "description": "Clear conversation history", "builtin": True},
        {"name": "compact", "description": "Compact conversation with optional focus instructions", "builtin": True, "options": ["[instructions]"]},
        {"name": "context", "description": "Visualize current context usage as a colored grid", "builtin": True},
        {"name": "exit", "description": "Exit the REPL", "builtin": True},
        {"name": "resume", "description": "Resume a previous conversation", "builtin": True},
        {"name": "rewind", "description": "Rewind conversation and/or code to a previous state", "builtin": True},

        # Model & Output
        {"name": "model", "description": "Select or change the AI model", "builtin": True, "options": ["haiku", "sonnet", "opus", "opusplan", "default"]},
        {"name": "output-style", "description": "Set the output style directly or from a menu", "builtin": True, "options": ["[style]"]},

        # Configuration & Setup
        {"name": "config", "description": "Open the Settings interface (Config tab)", "builtin": True},
        {"name": "hooks", "description": "Manage hook configurations for tool events", "builtin": True},
        {"name": "init", "description": "Initialize project with CLAUDE.md guide", "builtin": True},
        {"name": "mcp", "description": "Manage MCP server connections and OAuth", "builtin": True},
        {"name": "memory", "description": "Edit CLAUDE.md memory files", "builtin": True},
        {"name": "permissions", "description": "View or update permission settings", "builtin": True},
        {"name": "plugin", "description": "Manage Claude Code plugins", "builtin": True},
        {"name": "status", "description": "Open Settings interface showing version, model, account", "builtin": True},
        {"name": "statusline", "description": "Set up Claude Code's status line UI", "builtin": True},
        {"name": "terminal-setup", "description": "Install Shift+Enter key binding for newlines", "builtin": True},

        # Development Tools
        {"name": "add-dir", "description": "Add additional working directories", "builtin": True},
        {"name": "bashes", "description": "List and manage background tasks", "builtin": True},
        {"name": "cost", "description": "Show token usage statistics", "builtin": True},
        {"name": "doctor", "description": "Check Claude Code installation health", "builtin": True},
        {"name": "export", "description": "Export conversation to a file or clipboard", "builtin": True, "options": ["[filename]"]},
        {"name": "help", "description": "Get usage help for all available commands", "builtin": True},
        {"name": "sandbox", "description": "Enable sandboxed bash with filesystem/network isolation", "builtin": True},
        {"name": "stats", "description": "Visualize daily usage, session history, streaks", "builtin": True},
        {"name": "todos", "description": "List current TODO items", "builtin": True},
        {"name": "usage", "description": "Show plan usage limits and rate limit status", "builtin": True},

        # Code Review & Git
        {"name": "install-github-app", "description": "Set up Claude GitHub Actions for a repository", "builtin": True},
        {"name": "pr-comments", "description": "View pull request comments", "builtin": True},
        {"name": "review", "description": "Request code review", "builtin": True},
        {"name": "security-review", "description": "Security review of pending changes on current branch", "builtin": True},

        # Account & Info
        {"name": "bug", "description": "Report bugs (sends conversation to Anthropic)", "builtin": True},
        {"name": "ide", "description": "Manage IDE integrations and show status", "builtin": True},
        {"name": "login", "description": "Switch Anthropic accounts", "builtin": True},
        {"name": "logout", "description": "Sign out from your Anthropic account", "builtin": True},
        {"name": "privacy-settings", "description": "View and update your privacy settings", "builtin": True},
        {"name": "release-notes", "description": "View release notes", "builtin": True},

        # Advanced Features
        {"name": "agents", "description": "Manage custom AI subagents for specialized tasks", "builtin": True},
        {"name": "vim", "description": "Enter vim mode for alternating insert/command modes", "builtin": True},
    ]

    # Custom commands from .claude/commands directory
    custom_commands = []
    commands_dir = Path(".claude/commands")
    if commands_dir.exists():
        for md_file in sorted(commands_dir.glob("*.md")):
            name = md_file.stem  # filename without .md
            description = ""
            try:
                with open(md_file, 'r') as f:
                    first_line = f.readline().strip()
                    # Extract description from first heading or first line
                    if first_line.startswith('#'):
                        description = first_line.lstrip('#').strip()
                    else:
                        description = first_line[:100] if first_line else ""
            except Exception:
                pass
            custom_commands.append({"name": name, "description": description, "builtin": False})

    # Combine: custom commands first (more specific), then built-in
    all_commands = custom_commands + builtin_commands
    return {"commands": all_commands}


@app.post("/agent/apps/register")
async def register_app_manual(body: dict = Body(...)):
    """Manually register an app (for testing or persistent apps)."""
    name = body.get("name", "Unnamed App")
    port = body.get("port")
    directory = body.get("directory", "")
    operator = body.get("operator", "system")

    if not port:
        raise HTTPException(400, "Port is required")

    app_id = str(uuid.uuid4())
    app = RegisteredApp(
        app_id=app_id,
        name=name,
        port=port,
        directory=directory,
        session_id="manual",
        operator=operator,
        created_at=datetime.now().isoformat()
    )

    with agent_lock:
        APP_REGISTRY[app_id] = app

    # Persist to disk
    save_app_registry()

    print(f"[AGENT] Manually registered app {app_id}: {name} on port {port}")
    return {"success": True, "app": asdict(app)}


@app.delete("/agent/apps/{app_id}")
async def unregister_app(app_id: str):
    """Unregister an app from the registry."""
    with agent_lock:
        if app_id in APP_REGISTRY:
            app = APP_REGISTRY.pop(app_id)
            print(f"[AGENT] Unregistered app {app_id}: {app.name}")
            # Persist to disk
            save_app_registry()
            return {"success": True, "app_id": app_id}
        else:
            raise HTTPException(404, "App not found")


@app.api_route("/app-proxy/{port}/{path:path}", methods=["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"])
async def app_proxy(port: int, path: str, request: Request):
    """Reverse proxy to locally running apps created by Claude Code.
    This allows viewing apps through the Portal iframe without exposing ports.
    """
    # Validate port is reasonable
    if port < 1024 or port > 65535:
        raise HTTPException(400, "Invalid port number")

    target_url = f"http://localhost:{port}/{path}"

    # Handle query string
    if request.url.query:
        target_url += f"?{request.url.query}"

    try:
        async with httpx.AsyncClient(timeout=30.0, follow_redirects=True) as client:
            # Build headers (exclude hop-by-hop headers)
            headers = {}
            for key, value in request.headers.items():
                if key.lower() not in ('host', 'content-length', 'transfer-encoding', 'connection'):
                    headers[key] = value

            # Forward request
            if request.method == "GET":
                resp = await client.get(target_url, headers=headers)
            elif request.method == "POST":
                body = await request.body()
                resp = await client.post(target_url, content=body, headers=headers)
            elif request.method == "PUT":
                body = await request.body()
                resp = await client.put(target_url, content=body, headers=headers)
            elif request.method == "DELETE":
                resp = await client.delete(target_url, headers=headers)
            elif request.method == "PATCH":
                body = await request.body()
                resp = await client.patch(target_url, content=body, headers=headers)
            elif request.method == "OPTIONS":
                resp = await client.options(target_url, headers=headers)
            else:
                resp = await client.request(request.method, target_url, headers=headers)

            content = resp.content
            content_type = resp.headers.get("content-type", "application/octet-stream")

            # Rewrite relative URLs in HTML responses
            if "text/html" in content_type:
                try:
                    html = content.decode('utf-8', errors='replace')
                    # Rewrite href, src, action attributes that start with /
                    html = re.sub(r'(href|src|action)=["\']/', f'\\1="/app-proxy/{port}/', html)
                    content = html.encode('utf-8')
                except Exception as e:
                    print(f"[APP-PROXY] HTML rewrite error: {e}")

            # Build response headers
            response_headers = {}
            for key, value in resp.headers.items():
                if key.lower() not in ('transfer-encoding', 'content-encoding', 'content-length'):
                    response_headers[key] = value

            # Force no-cache to ensure fresh content through proxy
            response_headers['Cache-Control'] = 'no-store, no-cache, must-revalidate, max-age=0'
            response_headers['Pragma'] = 'no-cache'
            response_headers['Expires'] = '0'

            return Response(
                content=content,
                status_code=resp.status_code,
                headers=response_headers,
                media_type=content_type
            )

    except httpx.ConnectError:
        raise HTTPException(503, f"Cannot connect to app on port {port}. Is it running?")
    except httpx.TimeoutException:
        raise HTTPException(504, f"Request to app on port {port} timed out")
    except Exception as e:
        print(f"[APP-PROXY] Error: {e}")
        raise HTTPException(500, f"Proxy error: {str(e)}")


# -----------------------------------------------------------------------------
# System Metrics Endpoint
# -----------------------------------------------------------------------------

# Track network I/O for rate calculation
_last_net_io = None
_last_net_time = None

@app.get("/system/metrics")
async def get_system_metrics():
    """Get real-time system metrics for BlackBox system monitor."""
    global _last_net_io, _last_net_time

    try:
        # CPU metrics
        cpu_percent = psutil.cpu_percent(interval=0.1)
        cpu_count = psutil.cpu_count()
        load_avg = psutil.getloadavg() if hasattr(psutil, 'getloadavg') else [0, 0, 0]

        # CPU Temperature (Linux only, may not work on all systems)
        cpu_temp = 0
        try:
            if hasattr(psutil, 'sensors_temperatures'):
                temps = psutil.sensors_temperatures()
                if temps:
                    # Try common sensor names
                    for name in ['coretemp', 'k10temp', 'cpu_thermal', 'cpu-thermal']:
                        if name in temps:
                            cpu_temp = temps[name][0].current
                            break
                    # If no match, use first available
                    if cpu_temp == 0 and temps:
                        first_sensor = list(temps.values())[0]
                        if first_sensor:
                            cpu_temp = first_sensor[0].current
        except Exception as e:
            print(f"[METRICS] Temperature read error: {e}")

        # Memory metrics
        memory = psutil.virtual_memory()

        # Disk metrics (root partition)
        disk = psutil.disk_usage('/')

        # Network metrics with rate calculation
        net_io = psutil.net_io_counters()
        current_time = time.time()

        upload_rate = 0
        download_rate = 0

        if _last_net_io and _last_net_time:
            time_delta = current_time - _last_net_time
            if time_delta > 0:
                upload_rate = (net_io.bytes_sent - _last_net_io.bytes_sent) / time_delta
                download_rate = (net_io.bytes_recv - _last_net_io.bytes_recv) / time_delta

        _last_net_io = net_io
        _last_net_time = current_time

        # System info
        hostname = socket.gethostname()
        platform_info = f"{platform.system()} {platform.release()}"
        uptime = time.time() - psutil.boot_time()

        # Top processes by CPU
        processes = []
        for proc in psutil.process_iter(['pid', 'name', 'cpu_percent', 'memory_percent']):
            try:
                pinfo = proc.info
                processes.append({
                    'pid': pinfo['pid'],
                    'name': pinfo['name'],
                    'cpu_percent': pinfo['cpu_percent'] or 0,
                    'memory_percent': pinfo['memory_percent'] or 0
                })
            except (psutil.NoSuchProcess, psutil.AccessDenied):
                pass

        # Sort by CPU usage and take top 10
        processes.sort(key=lambda x: x['cpu_percent'], reverse=True)
        top_processes = processes[:10]

        return {
            'hostname': hostname,
            'platform': platform_info,
            'uptime': uptime,
            'cpu': {
                'percent': cpu_percent,
                'cores': cpu_count,
                'load_avg': list(load_avg),
                'temperature': cpu_temp
            },
            'memory': {
                'total': memory.total,
                'used': memory.used,
                'available': memory.available,
                'percent': memory.percent
            },
            'disk': {
                'total': disk.total,
                'used': disk.used,
                'free': disk.free,
                'percent': disk.percent
            },
            'network': {
                'upload_rate': upload_rate,  # bytes/sec
                'download_rate': download_rate,  # bytes/sec
                'upload_total': net_io.bytes_sent,
                'download_total': net_io.bytes_recv
            },
            'processes': top_processes
        }

    except Exception as e:
        print(f"[METRICS] Error collecting metrics: {e}")
        raise HTTPException(500, f"Failed to collect system metrics: {str(e)}")


@app.delete("/agent/session/{session_id}")
async def terminate_agent_session(session_id: str):
    """Terminate an agent session and cleanup."""
    with agent_lock:
        session = AGENT_SESSIONS.get(session_id)
        if session:
            if session.process and session.process.poll() is None:
                session.process.terminate()
                try:
                    session.process.wait(timeout=5)
                except:
                    session.process.kill()

            if session.pty_master:
                try:
                    os.close(session.pty_master)
                except:
                    pass

            del AGENT_SESSIONS[session_id]
            print(f"[AGENT] Terminated session {session_id}")
            return {"status": "terminated"}

    return {"status": "not_found"}


