#!/usr/bin/env python3
from __future__ import annotations

"""
task_routes.py - Task listing, status, fossil search endpoints
"""

# Standard library imports
from typing import Dict, Any, Optional, List
from pathlib import Path
import os

# External library imports
from fastapi import HTTPException
from pydantic import BaseModel
import requests

# Local imports
from Orchestrator.checkpoint import app
from Orchestrator.models import task_db
from Orchestrator.startup import AudioAnalysisIn

# Additional imports (auto-generated by dependency audit)
from Orchestrator.config import VOL_PATH, GOOGLE_API_KEY
from Orchestrator.fossils import load_snapshot_index
from Orchestrator.models import TaskType, TaskStatus
from Orchestrator.monitoring import semantic_search
from Orchestrator.tasks import create_task, update_task
from Orchestrator.volume import read_volume_bytes

# Pydantic model for synchronous analysis
class SyncAnalysisIn(BaseModel):
    file_url: str  # URL like /ui/uploads/xyz.jpg
    prompt: Optional[str] = None  # Optional custom prompt
    media_type: Optional[str] = None  # Optional: image, video, audio (auto-detected if not provided)


@app.get("/tasks/list")
def list_tasks(operator: Optional[str] = None, all: bool = False):
    """List tasks with smart filtering.
    By default, returns only:
    - Active tasks (pending/processing)
    - Recently completed tasks (last 10 minutes)
    This dramatically reduces response size for mobile/Tailscale while still
    allowing placeholder polling to detect completions.
    Use ?all=true to get full task history.
    """
    all_tasks = task_db.get_all_tasks(operator)

    # If all=true, return everything (for debugging/admin)
    if all:
        filtered_tasks = all_tasks
    else:
        # Smart filter: active + recently completed
        from datetime import datetime, timezone, timedelta
        cutoff_time = datetime.now(timezone.utc) - timedelta(minutes=10)

        filtered_tasks = [
            t for t in all_tasks
            if t.status in ['pending', 'processing']  # Always show active
            or (
                t.status in ['completed', 'failed']  # Show recent completed
                and t.updated_at  # Has update timestamp
                and datetime.fromisoformat(t.updated_at.replace('Z', '+00:00')) > cutoff_time
            )
        ]

    return {
        "tasks": [{
            "task_id": t.task_id,
            "task_type": t.task_type,
            "status": t.status,
            "progress": t.progress,
            "created_at": t.created_at,
            "updated_at": t.updated_at,
            "result_url": t.result_url,
            "operator": t.operator,
            "prompt": t.prompt[:100] if t.prompt else None
        } for t in filtered_tasks],
        "total_tasks": len(all_tasks),
        "filtered_count": len(filtered_tasks)
    }

@app.get("/tasks/status/{task_id}")
@app.get("/tasks/{task_id}")  # Alias for MCP compatibility
def get_task_status(task_id: str):
    """Get status of a specific task"""
    task = task_db.get_task(task_id)
    if not task:
        raise HTTPException(status_code=404, detail="Task not found")

    return {
        "task_id": task.task_id,
        "task_type": task.task_type,
        "status": task.status,
        "progress": task.progress,
        "created_at": task.created_at,
        "updated_at": task.updated_at,
        "result_url": task.result_url,
        "result_data": task.result_data,
        "error_message": task.error_message
    }

@app.post("/tasks/cancel-all")
def cancel_all_stuck_tasks():
    """Cancel all pending/processing tasks by marking them as failed."""
    all_tasks = task_db.get_all_tasks()
    cancelled = 0
    for t in all_tasks:
        if t.status in (TaskStatus.PENDING, TaskStatus.PROCESSING):
            update_task(t.task_id, status=TaskStatus.FAILED, error_message="Manually cancelled by operator")
            cancelled += 1
    return {"cancelled": cancelled}

# -----------------------------------------------------------------------------
# Recent Snapshots (chronological, newest-first — for Android Timeline)
# -----------------------------------------------------------------------------
@app.get("/api/snapshots/recent")
def api_snapshots_recent(limit: int = 30, operator: str = ""):
    """Return most recent snapshots in chronological order (newest first).
    Reads from the in-memory snapshot index — lightweight, no volume parsing.
    Returns snap_id, operator, timestamp, type, and a snippet preview.
    """
    try:
        from Orchestrator.fossils import load_snapshot_index, read_volume_bytes, VOL_PATH

        index = load_snapshot_index()
        if not index:
            return {"results": [], "count": 0}

        # Filter by operator if specified
        if operator:
            items = [(sid, meta) for sid, meta in index.items() if meta.get("operator") == operator]
        else:
            items = list(index.items())

        # Sort by snap_id descending (SNAP-YYYYMMDD-NNNNN — date+seq gives chronological order)
        def sort_key(item):
            try:
                parts = item[0].split('-')
                return (int(parts[1]), int(parts[2]))
            except (ValueError, IndexError):
                return (0, 0)

        items.sort(key=sort_key, reverse=True)
        items = items[:limit]

        # Extract snippets from volume using byte offsets
        vol_bytes = read_volume_bytes(VOL_PATH) if items else b""
        # Headers/boilerplate lines to skip when extracting preview snippet
        SKIP_PREFIXES = (
            '===', 'CROSS-FILE', 'Tail', 'COUNT=', 'UFL:', 'Result:',
            'VOLUME TRACKER', 'Next:', 'TBD', '---', '===============',
            'OPERATOR:', 'TYPE:', 'SNAP-', 'TARGET_ID=',
            'Mode:', 'Timestamp:', 'Model:', 'Provider:', 'Tokens:',
            'Session:', 'Voice:', 'Backend:', 'Duration:',
            '[user]', '[assistant]', 'role:', 'content:',
        )
        import re
        # Pattern to find user message in Raw Session Log: [N] timestamp operator=X user: MESSAGE
        USER_MSG_RX = re.compile(r'\[\d+\]\s+\S+\s+operator=\S+\s+user:\s*(.+)', re.IGNORECASE)

        results = []
        for snap_id, meta in items:
            snippet = ""
            if vol_bytes:
                try:
                    start = meta.get("byte_start", 0)
                    end = meta.get("byte_end", start + 4000)
                    # Read up to 4KB to reach past headers into Raw Session Log
                    chunk = vol_bytes[start:min(end, start + 4000)].decode('utf-8', errors='replace')

                    # Strategy 1: Find user message in Raw Session Log
                    m = USER_MSG_RX.search(chunk)
                    if m:
                        snippet = m.group(1).strip()[:200]
                    else:
                        # Strategy 2: Find first line after "SNAPSHOT BODY" that isn't metadata
                        body_idx = chunk.find('SNAPSHOT BODY')
                        if body_idx >= 0:
                            lines = chunk[body_idx:].split('\n')
                            for line in lines:
                                stripped = line.strip()
                                if not stripped or len(stripped) < 15:
                                    continue
                                if any(stripped.startswith(p) for p in SKIP_PREFIXES):
                                    continue
                                if stripped.startswith('Kernel') or stripped.startswith('Context') or \
                                   stripped.startswith('- ') or stripped.startswith('Raw Session'):
                                    continue
                                snippet = stripped[:200]
                                break
                except Exception:
                    pass

            results.append({
                "snap_id": snap_id,
                "operator": meta.get("operator", ""),
                "timestamp": meta.get("timestamp", ""),
                "type": meta.get("type", "normal"),
                "snippet": snippet,
            })

        return {"results": results, "count": len(results)}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

# -----------------------------------------------------------------------------
# Single Snapshot Fetch (for Android Timeline detail view)
# -----------------------------------------------------------------------------
@app.get("/fossil/snapshot/{snap_id}")
def fossil_get_snapshot(snap_id: str):
    """Fetch full content of a single snapshot by ID."""
    try:
        from Orchestrator.fossils import get_snapshot_by_id
        result = get_snapshot_by_id(snap_id)
        if result is None:
            raise HTTPException(status_code=404, detail=f"Snapshot {snap_id} not found")
        return result
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

# -----------------------------------------------------------------------------
# Semantic Search Endpoint (for MCP)
# -----------------------------------------------------------------------------
@app.get("/fossil/hybrid")
def fossil_hybrid_search(q: str, operator: str = "", limit: int = 10):
    """Hybrid semantic + keyword search on snapshots.
    Uses Google embeddings stored in each snapshot for semantic similarity,
    combined with keyword matching for best results.
    """
    try:
        # Use semantic search with embeddings
        semantic_results = semantic_search(q, operator=operator, k=limit)

        if not semantic_results:
            return {"results": [], "message": "No results found or embeddings not available"}

        # Load index and volume for fetching content
        index = load_snapshot_index()
        vol_bytes = read_volume_bytes(VOL_PATH)

        results = []
        for snap_id, similarity in semantic_results:
            if snap_id not in index:
                continue

            meta = index[snap_id]

            # Get snippet of content
            start = meta.get("byte_start", 0)
            end = meta.get("byte_end", 0)
            snippet = ""
            if start < len(vol_bytes) and end <= len(vol_bytes):
                snap_bytes = vol_bytes[start:end]
                snap_text = snap_bytes.decode('utf-8', errors='replace')
                # Get first 500 chars as snippet
                snippet = snap_text[:500] + "..." if len(snap_text) > 500 else snap_text

            results.append({
                "snap_id": snap_id,
                "operator": meta.get("operator", "unknown"),
                "timestamp": meta.get("timestamp", ""),
                "type": meta.get("type", "normal"),
                "similarity": round(similarity, 4),
                "snippet": snippet
            })

        return {
            "query": q,
            "operator": operator or "all",
            "count": len(results),
            "results": results
        }
    except Exception as e:
        print(f"[FOSSIL] Hybrid search error: {e}")
        import traceback
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/analyze/audio")
async def analyze_audio(inp: AudioAnalysisIn):
    """Queue audio analysis task - Block 3"""
    try:
        task = create_task(
            TaskType.AUDIO_ANALYSIS,
            operator=inp.operator,
            input_file=inp.file_path,
            result_data={"prompt": inp.prompt}
        )
        return {
            "task_id": task.task_id,
            "status": task.status,
            "message": "Audio analysis queued"
        }
    except Exception as e:
        print(f"ERROR: Failed to queue audio analysis: {e}")
        raise HTTPException(status_code=500, detail=str(e))


# -----------------------------------------------------------------------------
# Synchronous Media Analysis Endpoint (for Agent Mode Attachments)
# -----------------------------------------------------------------------------

# MIME type mappings for Gemini Files API
MIME_TYPE_MAP = {
    # Images
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".png": "image/png",
    ".gif": "image/gif",
    ".webp": "image/webp",
    ".bmp": "image/bmp",
    # Videos
    ".mp4": "video/mp4",
    ".webm": "video/webm",
    ".mov": "video/quicktime",
    ".avi": "video/x-msvideo",
    ".mkv": "video/x-matroska",
    # Audio
    ".mp3": "audio/mpeg",
    ".wav": "audio/wav",
    ".m4a": "audio/aac",
    ".aac": "audio/aac",
    ".ogg": "audio/ogg",
    ".flac": "audio/flac",
    ".aiff": "audio/aiff",
}

# Media type detection from extension
MEDIA_TYPE_FROM_EXT = {
    ".jpg": "image", ".jpeg": "image", ".png": "image", ".gif": "image",
    ".webp": "image", ".bmp": "image",
    ".mp4": "video", ".webm": "video", ".mov": "video", ".avi": "video", ".mkv": "video",
    ".mp3": "audio", ".wav": "audio", ".m4a": "audio", ".aac": "audio",
    ".ogg": "audio", ".flac": "audio", ".aiff": "audio",
}

# Default prompts by media type
DEFAULT_PROMPTS = {
    "image": "Describe this image in detail. Include all visual elements, text, objects, people, colors, composition, and any notable features. Be comprehensive.",
    "video": "Analyze this video. Describe the visual content, any actions or movements, the setting, and notable elements. Provide a detailed summary of what happens in the video.",
    "audio": "Transcribe and analyze this audio. Include the spoken content (transcript), speaker identification if multiple voices, emotional tone, background sounds, and any other relevant audio details.",
}


def _upload_to_gemini_files(file_path: Path, mime_type: str) -> str:
    """Upload a file to Gemini Files API and return the file URI."""
    if not GOOGLE_API_KEY:
        raise HTTPException(status_code=400, detail="GOOGLE_API_KEY not configured")

    file_bytes = file_path.read_bytes()
    num_bytes = len(file_bytes)

    # Step 1: Initialize resumable upload
    upload_url_response = requests.post(
        "https://generativelanguage.googleapis.com/upload/v1beta/files",
        headers={
            "x-goog-api-key": GOOGLE_API_KEY,
            "X-Goog-Upload-Protocol": "resumable",
            "X-Goog-Upload-Command": "start",
            "X-Goog-Upload-Header-Content-Length": str(num_bytes),
            "X-Goog-Upload-Header-Content-Type": mime_type,
            "Content-Type": "application/json"
        },
        json={"file": {"display_name": file_path.name}},
        timeout=30
    )
    upload_url_response.raise_for_status()
    upload_url = upload_url_response.headers.get("x-goog-upload-url")

    if not upload_url:
        raise Exception("No upload URL received from Gemini Files API")

    # Step 2: Upload the actual bytes
    upload_response = requests.post(
        upload_url,
        headers={
            "Content-Length": str(num_bytes),
            "X-Goog-Upload-Offset": "0",
            "X-Goog-Upload-Command": "upload, finalize"
        },
        data=file_bytes,
        timeout=300
    )
    upload_response.raise_for_status()
    file_info = upload_response.json()
    return file_info["file"]["uri"]


def _analyze_with_gemini(file_uri: str, mime_type: str, prompt: str) -> str:
    """Analyze a file using Gemini generateContent API."""
    generate_url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-3-pro-preview:generateContent"
    generate_payload = {
        "contents": [{
            "parts": [
                {"text": prompt},
                {"file_data": {"mime_type": mime_type, "file_uri": file_uri}}
            ]
        }]
    }

    generate_response = requests.post(
        generate_url,
        headers={
            "x-goog-api-key": GOOGLE_API_KEY,
            "Content-Type": "application/json"
        },
        json=generate_payload,
        timeout=120
    )
    generate_response.raise_for_status()
    result = generate_response.json()

    # Extract text from response
    try:
        text = result["candidates"][0]["content"]["parts"][0]["text"]
        return text
    except (KeyError, IndexError) as e:
        print(f"[SYNC_ANALYZE] Failed to extract text from Gemini response: {e}")
        print(f"[SYNC_ANALYZE] Response: {result}")
        raise Exception("Failed to extract analysis from Gemini response")


@app.post("/analyze/sync")
async def analyze_sync(inp: SyncAnalysisIn):
    """Synchronous media analysis for agent mode attachments.

    Takes a file URL (like /ui/uploads/xyz.jpg), analyzes it via Gemini,
    and returns the analysis immediately. Supports images, videos, and audio.

    This endpoint is designed for the agent mode attachment pipeline where
    files need to be analyzed before being passed to the Claude Code CLI.
    """
    try:
        print(f"[SYNC_ANALYZE] Starting analysis for: {inp.file_url}")

        # Convert URL to local path
        if inp.file_url.startswith("/ui/uploads/"):
            filename = inp.file_url.replace("/ui/uploads/", "")
            file_path = Path("Portal/uploads") / filename
        elif inp.file_url.startswith("http"):
            # Handle full URLs - extract filename
            filename = inp.file_url.split("/")[-1]
            file_path = Path("Portal/uploads") / filename
        else:
            file_path = Path(inp.file_url)

        if not file_path.exists():
            raise HTTPException(status_code=404, detail=f"File not found: {file_path}")

        # Detect media type and MIME type from extension
        ext = file_path.suffix.lower()
        mime_type = MIME_TYPE_MAP.get(ext, "application/octet-stream")
        media_type = inp.media_type or MEDIA_TYPE_FROM_EXT.get(ext, "unknown")

        if media_type == "unknown":
            raise HTTPException(status_code=400, detail=f"Unsupported file type: {ext}")

        print(f"[SYNC_ANALYZE] Detected media_type={media_type}, mime_type={mime_type}")

        # Use provided prompt or default
        prompt = inp.prompt or DEFAULT_PROMPTS.get(media_type, "Describe this content in detail.")

        # Upload to Gemini Files API
        print(f"[SYNC_ANALYZE] Uploading to Gemini Files API...")
        file_uri = _upload_to_gemini_files(file_path, mime_type)
        print(f"[SYNC_ANALYZE] Uploaded: {file_uri}")

        # Analyze with Gemini
        print(f"[SYNC_ANALYZE] Analyzing with Gemini...")
        analysis = _analyze_with_gemini(file_uri, mime_type, prompt)
        print(f"[SYNC_ANALYZE] Analysis complete ({len(analysis)} chars)")

        return {
            "success": True,
            "file_url": inp.file_url,
            "media_type": media_type,
            "analysis": analysis
        }

    except HTTPException:
        raise
    except Exception as e:
        print(f"[SYNC_ANALYZE] Error: {e}")
        import traceback
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=str(e))


